### ISSUE TITLE
Config validation doesn't check what version is actually used

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#10]
Validation of [config](https://github.com/elastisys/compliantkubernetes-apps/blob/main/bin/common.bash#L71) doesn't really check what version you use. Instead it just picks the latest tag, no matter how far back in history that is. This is very dangerous since it looks like someone running the latest bleeding edge non-release are actually on a supported tag in the config.

It would be better to clearly warn the user when not running supported release. It must still be possible to run non-tagged versions of course for development. In these cases the version could be set to the current commit sha or simply `dev`.

Bonus: Don't just check what commit is checked out, but also if the directory is "clean" (i.e. are there any non-committed changes). If there are, add `+dirty` to the version to indicate this.

Suggested fix: If no tag is available, set the version to `dev` and print a warning for the user.

**Comment by tordsson** [comment]
Duplicated of #189
