### ISSUE TITLE
Index per namespace not working

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#1000]
**Describe the bug**
The index per namespace is broken in the latest version of apps with the new fluentd image that we have built.
The problem is that the elasticsearch_dynamic output is not in the new image or if it's failing the elasticsearch check, I can't remember.

**To Reproduce**
1. Checkout apps 0.21
2. Enable index per namespace
3. Observe error messages in fluentd
4. Notice that no logs from namespaces are indexed

**Expected behavior**
The feature should work in the new apps version

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version 0.21

**Additional context**

**Comment by robinAwallace** [comment]
https://github.com/elastisys/compliantkubernetes-apps/pull/1005
