### ISSUE TITLE
[5] Alternate CD solution - simple CronJob

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#1004]
**What should be investigated.**

We are somewhat unconvinced about using Tekton for automatic security patching and updates of compliantkubernetes apps. Let's dig more before taking a decision.

Investigate: simple kubernetes CronJob

Try to timebox this task to 5 days.

and assess the following:

* Long-term “Health”
  * Governance; prefer in this order: CNCF project, community-driven, end-user-driven (e.g., Apple, Uber, Zalando)
  * License; prefer in this order: Apache 2.0, another open source license
  * Security patching history / policy
  * Popularity / adoption (GitHub contributors / commits / stars, who uses it?)
* MUST HAVEs:
  * Well documented.
  * Reliable.
  * Runs in a Kubernetes cluster.
  * Watches a Git repo and triggers an update.
  * Small resource footprint.
  * Can run our devbox.
* NICE TO HAVEs:
  * Has some notion of secrets management.
  * Watches a Docker repo and triggers an update.
  * Can be used for application developer CD too.
    * Has a pretty UI.
    * Has a good DX -- to evaluate this, think of what we would need to put in public docs, and how much first-line support burden you would expect.
* InfoSec questions:
  * How easy is it to understand and review **access control**?
  * How easy is it to collect **logs** to investigate if things go wrong?
  * How easy is it to trigger **alerts** if things go wrong?
  * How easy is it to perform **security patching**?
  * How easy is it to perform **upgrades**?
* Hands-on:
  * Actually try to upgrade WC and SC with $candidate
* Implications:
  * What changes are necessary in Compliant Kubernetes, e.g., `helm install`?

**What artifacts should this produce.**

* An investigation doc detailing what was done, the results and links to the docs listed below.
* A big Google Sheet with one row per candidate and all assessment criteria.
* A Google Presentation with one slide per candidate: pros, cons, and own thoughts for each solution.

**Comment by raviranjanelastisys** [comment]
PR opened - https://github.com/elastisys/ck8s-ops/pull/2359
