### ISSUE TITLE
Upgrade falco-exporter to v0.7.0

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-apps#1016]
**What Chart should be upgraded?**

upstream/falco-exporter

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by davidumea** [comment]
This is already "done", falco exporter has been bumped to v0.7.0 and their falco-exporter chart has been bumped to v0.8.0 (both latest)

**Comment by Pavan-Gunda** [comment]
I will close this now.
