### ISSUE TITLE
[2] Upgrade Grafana to v9.1.6

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-apps#1018]
**What Chart should be upgraded?**
upstream/grafana

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

lots of features and bugfixes - 8.2.3 to 9.1.6
Notes: thing to consider, milestone to 8.5.4 is 90 percent complete

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by viktor-f** [comment]
Both user grafana and ops grafana
