### ISSUE TITLE
[2] Upgrade harbor to v2.6.0

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-apps#1019]
**What Chart should be upgraded?**
upstream/harbor 

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [x] Other: *Write the reason here*

lots of enhancements, new features, and bug fixes, and one breaking change in 2.5.1
**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by viktor-f** [comment]
Harbor 2.6.0 is now out, so upgrade to that instead.
https://github.com/goharbor/harbor/releases/tag/v2.6.0
