### ISSUE TITLE
Wasteful docker builds in pipeline

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#102]
The [pipeline](https://github.com/elastisys/compliantkubernetes-apps/blob/main/.github/workflows/pipeline.yml#L28) has a test matrix for the unit tests that includes building this [docker file](https://github.com/elastisys/compliantkubernetes-apps/blob/main/pipeline/Dockerfile). This build is done in parallel across all test cases in the matrix (8 in total). Additionally, the build is repeated 4 times in the pipeline (once for each `uses: ./pipeline`), but for these repetitions it is not such a big deal since caching is used.

To avoid wasting github actions minutes (that we pay for) and spam mirrors for the packages we use, I suggest refactoring this so that the docker image is build first in a separate job and pushed to a registry. The test matrix can then use this image instead of building it repeatedly.

**Comment by Xartos** [comment]
We are not paying anymore for the minutes and we are not using (at the time of writing) any matrix runs anymore
