### ISSUE TITLE
[5] Upgrade Kube-prometheus-stack to v40.3.1

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-apps#1020]
**What Chart should be upgraded?**

upstream/Kube-prometheus-stack, also you may need to add new alerts (e.g. config-reloaders.yaml, kubernetes-system-controller-manager.yaml, kubernetes-system-scheduler.yaml)

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by viktor-f** [comment]
Check the changelog for all of the kube-prometheus-stack components, especially api changes (should at least be some api changes for alertmanager). Try to be thorough when testing these upgrades to make sure that everything still works.
