### ISSUE TITLE
Upgrade Open search dashboards to v2.0.0

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-apps#1021]
**What Chart should be upgraded?**

upstream/opensearch-dashboards

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [x] Other: *Write the reason here*

Many CVEs are mitigated
**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by Xartos** [comment]
This will be done at the same time as [this](https://github.com/elastisys/compliantkubernetes-apps/issues/1022)
