### ISSUE TITLE
[2] Possible to Alert when hitting field limit in opensearch

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#1031]
**What should be investigated.**
I would like to know if there is any possibility of getting an alert when the [field limit](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-settings-limit.html) has been hit for an index with the metrics we currently have got?
Is it perhaps possible to piggyback off any fluentd metrics?

**What artifacts should this produce.**
Yes or No on if it is possible to do in any reasonable manner.
If yes, an example showing the solution would be nice.

**Comment by robinAwallace** [comment]
It be worth looking at a exporter for opensearch
https://github.com/aparo/opensearch-prometheus-exporter
