### ISSUE TITLE
Grafana dashbord for resource request/limit per node

### ISSUE THREAD

**Issue by robinAwallace** [elastisys/compliantkubernetes-apps#1045]
**Is your feature request related to a problem? Please describe.**

To get a better understanding of resource capacity that the nodes have left, it would be good to have a dashboard showing the resource request and limits per node.
Much like the dashboard `kubernetes-cluster-status` which shows the resource request and limits for the complete cluster per namespace. But this new dashboard should be per node instead.

**Describe the solution you'd like**

There should exist a dashboard to show per node how much the request and limits are.

**Describe alternatives you've considered**

Keep working with `kubectl top node`

**Additional context**

The dashboard should work with node names and not ips. As it is more intuitive which node one is looking at. 

**Definition of done:**
When could this feature be considered done.

When it is possible to see the resource request and limits set for a specific node in grafana.

**Comment by viktor-f** [comment]
There is already two graphs in `kubernetes-cluster-status`: one showing cpu requests and one showing memory requests. But there is nothing for limits.

**Comment by robinAwallace** [comment]
I missed that part in `kubernetes-cluster-status` but there is no way to filter on a node name.

**Comment by viktor-f** [comment]
You can filter it a bit by just clicking on the names of the node under the graph.

**Comment by robinAwallace** [comment]
I would not say that is good enough or Intuitiv enough for every one.
