### ISSUE TITLE
Links to other web UIs on the Welcome pages (Grafana and OpenSearch) are not working

### ISSUE THREAD

**Issue by llarsson** [elastisys/compliantkubernetes-apps#1051]
**Describe the bug**

When I click the links to the other web UIs in both the Grafana and OpenSearch Welcome pages, they fail to work. But for different reasons!

**To Reproduce**

1. Go to your Grafana and OpenSearch Welcome pages.
2. Click on, for instance, the other UI's link.
    * In case of the Grafana Welcome page, the link looks right, but just doesn't actually lead to the page.
    * In the OpenSearch case, the link is actually broken, in that it doesn't lead to e.g. grafana.long-running.ck8s-dev.com, but rather, https://opensearch.long-running.dev-ck8s.com/app/grafana.long-running.dev-ck8s.com -- obviously, that's not right.

**Expected behavior**

I expect the links to work, just like the ones to the compliantkubernetes.io documentation.

**Version (add all relevant versions):**

 - Compliant Kubernetes apps version 0.22.0 (as per what the Welcome page says, so thanks for that!), I haven't tested any other, but I also think this is the first that features the Welcome page.

**Additional context**

You can see this problem live on the long-running cluster if you wish.

**Comment by crssnd** [comment]
should be fixed on the main branch
I will close the issue, but please re-open it if necessary
