### ISSUE TITLE
Opensearch readiness probe

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#1052]
**Is your feature request related to a problem? Please describe.**
Opensearch(-master pods) does not have any readiness or liveliness probes. This means that the opensearch process can be down (this has happened) wile the pod is still ready.

**Describe the solution you'd like**
Add some readiness probe and maybe liveliness probe to indicate when the pod is having issues.

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
The opensearch pods have readiness probes and maybe liveliness probes.

**Comment by viktor-f** [comment]
There is an ongoing PR upstream: https://github.com/opensearch-project/helm-charts/pull/172

**Comment by crssnd** [comment]
I will close it as this was fixed.
