### ISSUE TITLE
Add option to set kubeconfig path via config

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#1062]
**Is your feature request related to a problem? Please describe.**
Kubeconfig path is currently hard-coded to `.state/kube_config_sc.yaml` and `.state/kube_config_wc.yaml`. Though I can be overrided with the KUBECONFIG env var. It could be good to be able to set another default path without using the env var.

**Describe the solution you'd like**
Add a new config option to `sc-config.yaml` and `wc-config.yaml`. Keep the default the same as now.

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
We have a new config option for setting the path to kubeconfig files.

**Comment by crssnd** [comment]
https://github.com/elastisys/ck8s-ops/issues/2289
