### ISSUE TITLE
[2] Expose extra users configurer option

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#1067]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it would be nice to be able to define static users in OpenSearch through the config file, especially now when we've added a simpler means to run the securityadmin.

**Describe the solution you'd like**
I would like the option to append to the configurers list of users so we could define static users.

**Describe alternatives you've considered**
Manage the users manually, which in the long run will be more work, and wouldn't allow us to benefit from the securityadmin.

**Definition of done:**
The option to add extra users is exposed.

**Comment by Xartos** [comment]
@aarnq Could you give an example of what config that should be exposed so we can understand the size of the issue?

**Comment by aarnq** [comment]
It would add the config option `opensearch.extraUsers`, in the same way as we already have for `extraRoles` and `extraRoleMappings`, which would add to [the list of users already created by the opensearch-configurer](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/opensearch/configurer.yaml.gotmpl#L56-L77).
