### ISSUE TITLE
[3] Enforce helm chart linting

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#107]
We currently do not fail on linting errors in the helm charts. See [this](https://github.com/elastisys/compliantkubernetes-apps/blob/main/.github/workflows/pipeline.yml#L49).
Remove the `continue-on-error` setting to enforce the linter and fix any issues you find.

See also #105. We may want to run `helmfile template` instead or in addition to `helmfile lint` but this is not strictly part of this issue.

Definition of done: The pipeline fails if there are linting/templating errors.

**Comment by tordsson** [comment]
Limit linting to internal charts only, not upstream ones.
