### ISSUE TITLE
[1] Init moved values when it should not

### ISSUE THREAD

**Issue by robinAwallace** [elastisys/compliantkubernetes-apps#1071]
UPDATED: check if this still is an issue in the latest release. If it isn't an issue anymore then we can close this issue. Otherwise, re-create this issue with more updated information

~**Describe the bug**~
~A clear and concise description of what the bug is.~

~The init command moved values from sc-config to common-config when it should not. It also messed up the values.~

**To Reproduce**
~Steps to reproduce the behavior:~
~1. Check out `v0.21.2`~
~2. Add this for opensearch in `sc-config.yaml`~
```
opensearch:
  additionalTemplates:
    example.template.json: |-
      {
        "index_patterns": [
          "example-template*"
        ],
        "template": {
          "settings": {
            "mapping.total_fields.limit": "1000"
          }
        }
      }
```
~3. run `bin/ck8s init`~
~4. See `planningbackend.template.json` be removed from sc-config and new values added to common-config~

~**Expected behavior**~
~A clear and concise description of what you expected to happen.~

~It should not move the values from sc-config to common-config~

~**Screenshots**~
~If applicable, add screenshots to help explain your problem.~

~**Version (add all relevant versions):**~
~ - Compliant kubernetes apps version v0.21.2~

~**Additional context**~
~Add any other context about the problem here.~

**Comment by Xartos** [comment]
@robinAwallace Updated the description to have this issue just verify that this isn't a problem anymore and in that case close it

**Comment by robinelastisys** [comment]
This doesn't seem to be a problem anymore!
