### ISSUE TITLE
Look through falco again and filter more alerts

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#1080]
**Is your feature request related to a problem? Please describe.**
We have done a few improvements to the falco rules, so that more of the "regular operations" of the cluster is filtered and don't start any alarm. But there are still some left that would be good to filter, in order to reduce the spam.

**Describe the solution you'd like**
Time box this issue to 3 days. In that time you should try to looks through the dalco alerts that are generated in our clusters (use some existing clusters in addition to a dev cluster). Then try to filter as many harmless alerts as possible by modifying the falco rules. Focus on the alerts that trigger the most often and the ones that are the easiest to filter.
After 3 days, if you did not have time to filter everything, then write a follow up issue with the ones that are left.

**Describe alternatives you've considered**
to not time box this issue. But we do not really know how much work this is, so a time boxed version sounds good as a start.

**Additional context**
Some previous issues:
https://github.com/elastisys/compliantkubernetes-apps/issues/896
https://github.com/elastisys/compliantkubernetes-apps/issues/897
https://github.com/elastisys/compliantkubernetes-apps/issues/898

**Definition of done:**
- We have less alerts for harmless events.
- We have a follow up issue that details the remaining work to reduce the remaining harmless alerts to (close to) zero.

**Comment by crssnd** [comment]
I did this as part of this [PR](https://github.com/elastisys/compliantkubernetes-apps/pull/1101)
I will close this and open more specific issues if needed.
