### ISSUE TITLE
[5] Add NetworkPolicies for rook and ceph

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#1135]
This task include creating NetworkPolicies for rook and ceph. This includes:
- the whole rook-ceph namespace

This is a subtask to https://github.com/elastisys/compliantkubernetes-apps/issues/654. See that issue for a more detailed instruction, including definition of done.

**Comment by raviranjanelastisys** [comment]
Was able to fix the ingress /egress traffic rules accordingly and NP dashboard looks like below . Bottom right is known traffic and doesn't break any functionality 

![image](https://user-images.githubusercontent.com/75951259/199667866-a7ad4057-6581-41c0-b3fd-d4bf2f317299.png)

**Comment by raviranjanelastisys** [comment]
Enabled the Ceph Dasboard too - https://github.com/elastisys/compliantkubernetes-kubespray/pull/236

**Comment by raviranjanelastisys** [comment]
Tested with other NP enabled too , i don't see any network drops :) 

![image](https://user-images.githubusercontent.com/75951259/200264435-2fb07482-21c6-47a7-b18c-726a35bdc711.png)

**Comment by raviranjanelastisys** [comment]
Worked on some more scenarios like below when `rook-ceph` and other NP enabled !! 
- deploying the apps with NP enabled (Maybe while on-boarding new customer)
- While adding the new nodes and how the OSD network behaves and accordingly set the rules to work 
- Draining the nodes and see how the `rook-ceph` network behaves when moving to other worker nodes and accordingly set the rules 

![image](https://user-images.githubusercontent.com/75951259/201307526-a9490f2c-5779-4745-b5a9-325fc945af3f.png)

**Comment by raviranjanelastisys** [comment]
PR opened - https://github.com/elastisys/compliantkubernetes-apps/pull/1291

**Comment by raviranjanelastisys** [comment]
Done some more testing and discussed with @Xartos !! While draining the node in future (via kubespray) , there you might see some egress packets drops between `mon` pods but we have already allowed the rule and it doesn't affects the functionality and works fine !! Although , restarting pods helped back to `0` egress packet drops 

![image](https://user-images.githubusercontent.com/75951259/204297070-9cdd56cf-28fa-4812-b3eb-1bec3e0943d5.png)
