### ISSUE TITLE
[5] Let's get ready for Pod Security Admission

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#1147]
**What should be investigated.**

Pod Security Policies were removed in Kubernetes 1.25 and are replaced with [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/). I made a quick analysis and, as far as I understood, we need to make the following changes:

- Remove PSPs from all Charts
- Add the [correct namespace labels](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/)

Please proceed as follows:

- Install two Kubernetes 1.25 clusters.
- While not working; adjust Helm Charts.
- Check that the correct profile is applied to non-privileged and user namespaces. E.g., one should not be able to run a root or privileged container in the `production` namespace.

**What artifacts should this produce.**

* An investigation report, highlighting challenges and changes needed to make Compliant Kubernetes compatible with Kubernetes 1.25.

**Comment by raviranjanelastisys** [comment]
Thanks !! As discussed with SM's , Will take this in CS - Q4 !!
