### ISSUE TITLE
[1] Welcome dashboard is no longer the default home page in opensearch

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-apps#1154]
**Describe the bug**

In apps `v0.25.0` opensearch is no longer the default home page when you log in.

**To Reproduce**

1. Upgrade a ck8s cluster to apps `v0.25.0`
2. Go to opensearch.< domain >
3. Note that the dashboard is not the default home page, although if you go to the dashboard manually it has been updated to include the newest changes i.e. "Apps Version: v0.25.0".

**Expected behavior**

When you log in to opensearch you should see the welcome dashboard as home page.

**Version (add all relevant versions):**

 - Compliant kubernetes apps version `v0.25.0`

**Additional context**

Possibly make a patch release for `v0.25.0` with a fix for this.

**Comment by robinelastisys** [comment]
Solved and pushed as part of https://github.com/elastisys/compliantkubernetes-apps/pull/1151 !
