### ISSUE TITLE
Troubleshooting scripts - Logging

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#1193]
**Is your feature request related to a problem? Please describe.**

Compliant Kubernetes needs more troubleshooting scripts to help operators quickly figure out faults in an environment.
We could use some checks for the logging stack so we can quickly assert that it works as it should.

**Describe the solution you'd like**

Check and present these in some nice way:

**OpenSearch:**
- Check cluster status
- Check snapshot status
- Check breakers
- Check indices
- Check aliases
- Check mappings
- *Already have an alert* - Check mappings count
- *Should also be an alert* - Check shard allocation / skew
- Check index state management
- Check users and roles
- Check object store access

**Fluentd:**
- Check connection to OpenSearch

*If time permits or create a separate issue:*

**OpenSearch Dashboards:**
- Check type conflicts in index patterns
- Check authentication issues
    - *401 loop*
    
**Fluentd:**
- Using logs from all Fluentd pods:
    - Filter logs to highlight errors or warnings and the reason
    - Check if there has been a mapping conflict

**Describe alternatives you've considered**

Alternatives would be to check manually and ensure that the config is correct.

**Additional context**

Note that it could be good to have the option of doing these as targeted tests, since some make take considerably longer time.

**Definition of done:**

List of tests implemented under the `test` command.

**Comment by ayoubeddafali** [comment]
For the second part ( Opensearch dashboards & fluentd ), a separate issue has been created #1341
