### ISSUE TITLE
Upgrade cert-manager to v1.11.0

### ISSUE THREAD

**Issue by lucianvlad** [elastisys/compliantkubernetes-apps#1221]
**What Chart should be upgraded?**

jetstack/cert-manager

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [X] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by raviranjanelastisys** [comment]
We have new release of cert-manager - `v1.11.0` - Maybe you can use this - https://github.com/cert-manager/cert-manager/releases/tag/v1.11.0
