### ISSUE TITLE
Upgrade gatekeeper to version v3.9.0

### ISSUE THREAD

**Issue by lucianvlad** [elastisys/compliantkubernetes-apps#1224]
**What Chart should be upgraded?**

upstream/gatekeeper [chart](https://github.com/open-policy-agent/gatekeeper/blob/v3.9.0/charts/gatekeeper/Chart.yaml)

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by raviranjanelastisys** [comment]
We have a new release of Gatekeeper - `v3.11.0` -  https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.11.0 . maybe you can update this newer version
