### ISSUE TITLE
Upgrade Ingress-nginx to v1.7.1

### ISSUE THREAD

**Issue by lucianvlad** [elastisys/compliantkubernetes-apps#1225]
**What Chart should be upgraded?**

[upstream/ingress-nginx](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/Chart.yaml)

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by raviranjanelastisys** [comment]
Please upgrade the chart to `4.4.2`  - https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-4.4.2 , which also upgrade the app version to `1.5.1` and fixed alot of security CVE
