### ISSUE TITLE
Upgrade Starbord-operator to v0.15.11

### ISSUE THREAD

**Issue by lucianvlad** [elastisys/compliantkubernetes-apps#1228]
**What Chart should be upgraded?**

upstream/starbord-operator [chart](https://github.com/aquasecurity/starboard/blob/main/deploy/helm/Chart.yaml)

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by raviranjanelastisys** [comment]
upgrade this charts to `v0.15.11` -  https://github.com/aquasecurity/starboard/releases/tag/v0.15.11 as it fixes the CVE vulnerability too .
