### ISSUE TITLE
[1] Upgrade prometheus-blackbox-exporter to v0.23.0

### ISSUE THREAD

**Issue by lucianvlad** [elastisys/compliantkubernetes-apps#1230]
**What Chart should be upgraded?**

upstream/prometheus-blackbox-exporter [chart-7.7.0](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/Chart.yaml)

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by raviranjanelastisys** [comment]
Please upgrade to the chart version `v0.23.0` -  https://github.com/prometheus/blackbox_exporter/releases/tag/v0.23.0 as it has some security CVE fixes !!!
