### ISSUE TITLE
[2] Tutorial: Produce Compliant Kubernetes on top of vanilla Kubernetes tutorial

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#124]
Acceptance criteria:
- A Markdown document
  - Allows someone familiar with Kubernetes, Helm, Helmfile and sops to deploy a service cluster.
  - Allows someone familiar with Kubernetes, Helm, Helmfile and sops to deploy two workload clusters, pointing to the previous service cluster.
  - Tutorial should encourage "secure" practices, e.g., encrypted or out-of-tree secrets.

**Comment by tordsson** [comment]
First, do this using the apps CLI. Later on, we can show the manual steps.

**Comment by tordsson** [comment]
Can be replaced by: https://github.com/elastisys/compliantkubernetes-apps/issues/191 and/or https://github.com/elastisys/compliantkubernetes-apps/issues/192

**Comment by tordsson** [comment]
Will be redundant once #225 is done

**Comment by tordsson** [comment]
Closing (obsolete).
