### ISSUE TITLE
[1] Dex id token expiration time configurable?

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-apps#1242]
**What should be investigated.**

Can we make dex id token expiration time configurable?

In the dexidp helm chart there is no option to configure how fast the id token should expire, is there a reasonable solution to go around this?

**What artifacts should this produce.**

There should be a written investigation with a conclusion whether this is doable in an easy way. If doable, then another issue for a fix should be created.

**Comment by Xartos** [comment]
There seems to be some [config options](https://github.com/dexidp/dex/blob/master/examples/config-dev.yaml#L78-L85) for this in dex at least, so we should quite easily be able to add this

**Comment by cristiklein** [comment]
@davidumea PM Cristian here. :smile: Do you know why they want to make Dex token expiration time configurable?

The point of having a token with a short life-time is to improve data protection. In many companies, employees are "forced" to do OpenID authentication (which may include 2FA) at least once a day. This adds another layer of protection, e.g., a lost laptop or a mis-copy-pasted token is less of a security nightmare.

I'm not saying it is wrong for the customer to ask for longer token expiration time, but it is a [smell](https://en.wikipedia.org/wiki/Code_smell), i.e., a request that may indicate a deeper problem.

**Comment by viktor-f** [comment]
In the discussion that prompted this issue we were asked for enforcing a shorter expiration time.

**Comment by Pavan-Gunda** [comment]
I like that one of our customers wanted shorter expiry. 

After hearing about a ticket for configuring the expiration of tokens from one of the customers, I just blindly assumed it would be about a longer expiration time.
