### ISSUE TITLE
[2] Upstream: Simplify Harbor setup

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#125]
We configure Harbor with OIDC. Currently that requires an init container to call a Harbor API, which feels brittle. This task consists in investigating and upstreaming OIDC configuration of Harbar via a ConfigMap.

Please follow how the `POSTGRESQL_HOST` variable is being configured, and try to mimic that for OIDC variables:
1. It is set in a ConfigMap: https://github.com/goharbor/harbor-helm/blob/1acd0c7ef61c22ea90c877735517c5e6b7f10b17/templates/core/core-cm.yaml#L17
2. That ConfigMap is exposed via environment variables here: https://github.com/goharbor/harbor-helm/blob/1acd0c7ef61c22ea90c877735517c5e6b7f10b17/templates/core/core-dpl.yaml#L61
3. It is converted into an internal Harbor variable here: https://github.com/goharbor/harbor/blob/master/src/common/config/metadata/metadatalist.go#L107

The same could be done for OIDC variables. My understanding is that we "only" need to add them an EnvKey attribute here:
https://github.com/goharbor/harbor/blob/master/src/common/config/metadata/metadatalist.go#L136

Acceptance criteria:
- I can use the upstream Harbor Chart and upstream Harbor image to setup OIDC via `values.yaml` in a robust and easy-to-understand manner.

**Comment by Xartos** [comment]
Looking into this I quite quickly realized that this was not as simple as you described, so I found an similar issue and asked there. And it seems like there's a proposal on the way for this from the maintainers already https://github.com/goharbor/harbor/issues/13911

**Comment by cristiklein** [comment]
I think this is great! We engaged with upstream, learned about their roadmap and offered to help. I would mark this issue as "waiting for upstream" or close it. If we close it, we can either reopen it later, or open a new issue linked to the present one. Any preference @Xartos ?

**Comment by Xartos** [comment]
I think we can close this one and once the proposal is in, we can create a new issue.

**Comment by cristiklein** [comment]
Perfect! Please do so. Just to make sure we don't miss this, I subscribed to the upstream thread as well.
