### ISSUE TITLE
Fix so apply on Harbor is idempotent

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#1286]
**Describe the bug**
Currently some value in the Harbor release is generated on apply so it constantly changes.

**To Reproduce**
Apply Harbor
*Installs*
Apply Harbor again
*Installs again*

**Expected behavior**
Apply Harbor
*Installs*
Apply Harbor again
*Already installed*

**Version (add all relevant versions):**
 - v0.26.x

**Comment by Xartos** [comment]
This should be fixed by this one https://github.com/elastisys/compliantkubernetes-apps/pull/1320
