### ISSUE TITLE
[1] Opensearch `alerting_full_access` role missing permissions

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-apps#1325]
**Describe the bug**
Since the upgrade of Opensearch/Opensearch dashboards in ck8s `v0.26` the users with the `alerting_full_access` role can no longer see notification channels. Seems like there was a new cluster permission introduced that we have not added to ck8s yet.

**To Reproduce**
1. Log in to Opensearch dashboards with a user that has the `all_access` role
2. Create a notification channel
3. Log in to Opensearch as a user without the `all_access` role, but that has the `alerting_full_access` role.
4. Try to view the notification channel that you just created

**Expected behavior**
The user should be able to see notification channels.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.26+

**Desired solution**
Add this cluster_permission to the `alerting_full_access` role:
- `cluster:admin/opensearch/notifications/*`

**Comment by lucianvlad** [comment]
- Logged in in opensearch with `all_access` role.
- Created a monitoring channel:
![image](https://user-images.githubusercontent.com/88718063/208918958-1a48dacf-66fa-4fc6-8168-4342817bbb37.png)

- Changed the securityadmin and added the missing cluster_permission `- cluster:admin/opensearch/notifications/*` 
- Removed the following lines from `sc-c0nfig.yaml` in the CK8S_CONFIG_PATH :
```
-  extraRoles:
-    - role_name: alerting_full_access
-      definition:
-        cluster_permissions:
-          - cluster_monitor
-          - cluster:admin/opendistro/alerting/*
-        index_permissions:
-          - allowed_actions:
-              - indices_monitor
-              - indices:admin/aliases/get
-              - indices:admin/mappings/get
-            index_patterns:
-              - kubernetes-*
-              - kubeaudit-*
```
- Applied the changes and tested. I was able to view the previously created notification channel using the `alerting_full_access` role:
![image](https://user-images.githubusercontent.com/88718063/208919753-10195f79-90c2-4a05-a0d0-04be272337de.png)

![image](https://user-images.githubusercontent.com/88718063/208920136-eb0c4d57-a040-426c-a5b7-9d4495b56fe6.png)
