### ISSUE TITLE
Enable long-term storage of audit and authlogs

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-apps#1339]
**Is your feature request related to a problem? Please describe.**
For customers who need to comply with Patientdatalagen a 30 day log retention is not enough. We need to enable long-term storage (5 years) of kubernetes audit logs and the SSH authlogs.

**Describe the solution you'd like**
Retention time for auth/audit logs should be configurable to allow for long-term storage (normally 5 years but might be even longer in some cases).
The audit logs needs to be cleaned up (we are only interested in when a human user accesses the system, not machine interactions) and compressed.
The compressed logs should then be stored in an s3 bucket. Note that the customer does not need access to this bucket.

**Describe alternatives you've considered**
Giving the customer access to their log and doing this themselves. This is not compliant with us being a data processor afiak.

**Additional context**

**Definition of done:**
It is possible to enable long-time retention of audit/auth logs.

**Comment by aarnq** [comment]
Fixed by #1392
