### ISSUE TITLE
Make it possible to show zone/node spread for pods in grafana

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#1345]
**Is your feature request related to a problem? Please describe.**
Users might want to be able to easily see how well their pods are spread across zones/nodes.

**Describe the solution you'd like**
I have assumed that the grafana dashboard would be for a specific deployment/statefulset. But you could perhaps in addition/instead do it for all deployments/statefulsets in a namespace/cluster.

To visualize node-spread it should be enough to use the metric `kube_pod_info`, which includes info about which node a pod is running on. To visualize zone spread I don't think we have any metric that shows which zone a pod or a node is in. But kube-state-metrics can expose node labels and we usually have the labels `topology.kubernetes.io/zone` and `failure-domain.beta.kubernetes.io/zone` to show which zone a node is in. So adding --metric-labels-allowlist=nodes=[topology.kubernetes.io/zone] should be enough to get the missing info. Then we can combine that with the info about which node a pod is running on.

Not sure how to visualize this in a good way in grafana.

**Describe alternatives you've considered**

**Additional context**
[Documentation with `kube-state-metrics` arguments.](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/cli-arguments.md)

**Definition of done:**
There is a grafana dashboard that can show how a deployment/statefulset is spread across zones/nodes.

**Comment by Zash** [comment]
Does this look like a start?

![image](https://github.com/elastisys/compliantkubernetes-apps/assets/197474/521b01ef-dc4f-47aa-94c8-660b1ebd6f04)

**Comment by viktor-f** [comment]
The main idea here was to make it a bit more focused on a per deployment/statefulset level. So instead of showing how the spread is for all pods I want to know how well the pods in a single deployment is spread out. For a given deployment, are the pods spread across different nodes or are they clumped together.
If possible then it would be nice to be able to see some general metric for each deployment/statefulset so that I can see which have a "good" spread and which have a "bad" spread, then I can maybe see some more details for the "bad" ones.
