### ISSUE TITLE
NFS-client-provisioner chart deprecated

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#136]
The [nfs-client-provisioner](https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner) helm chart that we use is deprecated and no longer supported.
Maybe we could adopt it and become maintainers of it?

In any case, we will need to replace the deprecated chart with something.

**Comment by tordsson** [comment]
Investigate options:
1. Contribute Helm chart to https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/tree/master/deploy ? 
2. Search for alternative chart
3. Create own Helm chart

**Comment by lentzi90** [comment]
> Investigate options:
> 
> 1. Contribute Helm chart to https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/tree/master/deploy ?
> 2. Search for alternative chart
> 3. Create own Helm chart

Since there is already a chart (it is just abandoned) I would say the options are:

1. Search for alternative chart
2. Adopt the chart and find a new home for it

The second option could mean that we contribute it to the [nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/tree/master/deploy) and that we promise to maintain it there. (I doubt the current maintainers of that repo want to do it or they would already have done it.) Alternatively we could put it in our own elastisys/charts, then it is very clearly our responsibility to maintain it.

**Comment by lentzi90** [comment]
Closed as we are moving away from NFS. See #423
