### ISSUE TITLE
[0] Rename Elasticsearch Grafana dashboard

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#1382]
**Is your feature request related to a problem? Please describe.**
We are running Opensearch nowadays but the Grafana dashboard is still called [Elasticsearch](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/grafana-ops/dashboards/elasticsearch-dashboard.json).

**Describe the solution you'd like**
I'd like us to rename the dashboard to Opensearch.
Also consider if the descriptions should be updated.

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
Said dashboard in Grafana as been renamed.

**Comment by aarnq** [comment]
I think we should rename the release for elasticsearch exporter as well to keep everything in line.
