### ISSUE TITLE
Move the csi-cinder-controllerplugin to the elastisys node

### ISSUE THREAD

**Issue by raviranjanelastisys** [elastisys/compliantkubernetes-apps#1397]
**Is your feature request related to a problem? Please describe.**
Based on this ADR https://github.com/elastisys/compliantkubernetes/pull/489 - Move the `csi-cinder-controllerplugin` to the elastisys node 

**Describe the solution you'd like**
Move the `csi-cinder-controllerplugin` to the elastisys node 

**Describe alternatives you've considered**
N/A
**Additional context**
N/A
**Definition of done:**
`csi-cinder-controllerplugin` moved to the elastisys node

**Comment by viktor-f** [comment]
Closing in favor of https://github.com/elastisys/compliantkubernetes-kubespray/issues/255
