### ISSUE TITLE
Replace starboard-operator with trivy-operator

### ISSUE THREAD

**Issue by robinelastisys** [elastisys/compliantkubernetes-apps#1419]
**Is your feature request related to a problem? Please describe.**
The resurrection of this issue came as a [result](https://github.com/elastisys/ck8s-arch/issues/6) of our arch-meeting 2023-03-30.

https://github.com/elastisys/compliantkubernetes-apps/issues/1316  and  https://github.com/elastisys/compliantkubernetes-apps/pull/1414.

To fix this, we may want to update from using Starboard to using Trivy as suggested to get new updates and features:
> We've announced our plans to discontinue Starboard and merge it into [Trivy](https://github.com/aquasecurity/trivy).
https://github.com/aquasecurity/starboard

This project and pull request introduces a feature called "slow" added to the "trivy-operator". 
> "this flag is to use less CPU/memory for scanning though it takes more time than normal scanning. It fits small-footprint".
https://github.com/aquasecurity/trivy-operator/pull/747

The step to replace starboard-operator with trivy-operator have been [investigated](https://github.com/elastisys/ck8s-ops/pull/3734).

**Describe the solution you'd like**
Our Starboard configs, values and functionality is replaced by Trivy by closely looking into and following instructions and changes.

**Describe alternatives you've considered**
That we keep Starboard and accept that we have crashed from time to time.

**Definition of done:**
Starboard is replaced by Trivy to the best of our ability and that it functions correctly.

**Comment by crssnd** [comment]
this issue should be completed first https://github.com/elastisys/ck8s-ops/issues/2814

**Comment by robinelastisys** [comment]
> this issue should be completed first [elastisys/ck8s-ops#2814](https://github.com/elastisys/ck8s-ops/issues/2814)

Aaah awesome! Didnt know we already had that issue! :-)
