### ISSUE TITLE
[5]Add structural config validation

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#1427]
**Is your feature request related to a problem? Please describe.**
We have large configs which makes it easy to miss details when setting values.

**Describe the solution you'd like**
I want to see structural config validation with reusable blocks for common occurrences:
- `enabled`
- `imageRegistry`/`imageRepository`/`imageTag` - to prepare for eventual support for registry mirrors.
- `replicas`
- `resources`
- `tolerations`
- `affinity`
- etc.

It would also help us to standardise how we work and add options to the config to make it easier to manage and maintain.

**Additional context**
And try to do it in a such way that it doesn't take too long time within bash.

**Definition of done:**
Improved structural validation of the config.

**Comment by Zash** [comment]
And with those additional PRs, this is **really** done! 🎉
