### ISSUE TITLE
Add blackbox exporter dashboard and add probes from WC to SC

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#1437]
**Is your feature request related to a problem? Please describe.**
It would be of great interest to add a dashboard for blackbox exporter to easily see the performance of probes within an environment, both in terms of DNS resolve and TCP connect.

Furthermore it would be nice with probes going from the WC to public SC endpoints to monitor how well it can communicate with it.

**Describe the solution you'd like**
- Added dashboard for blackbox exporter
- Added probes in WC against public target in SC

**Definition of done:**
Both points added above.

**Comment by Ajarmar** [comment]
See https://grafana.com/grafana/dashboards/7587-prometheus-blackbox-exporter/

**Comment by aarnq** [comment]
> > Furthermore it would be nice with probes going from the WC to public SC endpoints to monitor how well it can communicate with it.
> 
> Should this be a separate issue?

I don't think it needs to be since there shouldn't be too much work to adapt the current probes to be checking from both clusters. But a separate PR would be preferred.

**Comment by aarnq** [comment]
> So what's a good target URL to hit?

You can reuse the one defined for SC in https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/prometheus-blackbox-exporter-sc.yaml.gotmpl
Skipping the in cluster addresses.
