### ISSUE TITLE
Helm error when running `./bin/ck8s dry-run wc`

### ISSUE THREAD

**Issue by Havoc24k** [elastisys/compliantkubernetes-apps#1466]
**Describe the bug**
`./bin/ck8s dry-run wc` command fails with multiple errors on helm file `/compliantkubernetes-apps/helmfile/50-applications.yaml:`

This snippet is the first error on the stack, I am not pasting the full error output so that I don't clutter the bug report, but I have the full error output saved locally.
```
Comparing release=hnc-controller, chart=charts/hnc/controller
********************

        Release was not present in Helm.  Diff will show entire contents as new.

********************

Listing releases matching ^calico-default-deny$
Listing releases matching ^fluentd-aggregator$
Listing releases matching ^kured$
Listing releases matching ^kured-secret$
Listing releases matching ^velero$
in /home/[REDACTED]/elastisys/compliantkubernetes-apps/helmfile/50-applications.yaml: 15 errors:
err 0: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: diff (4 bytes)
  2: upgrade (7 bytes)
  3: --allow-unreleased (18 bytes)
  4: ciskubebench-exporter (21 bytes)
  5: charts/starboard/ciskubebench-exporter (38 bytes)
  6: --version (9 bytes)
  7: 0.1.0 (5 bytes)
  8: --namespace (11 bytes)
  9: monitoring (10 bytes)
  10: --values (8 bytes)
  11: /tmp/helmfile2095254489/monitoring-ciskubebench-exporter-values-6fdb85b6f4 (74 bytes)
  12: --color (7 bytes)
  13: --reset-values (14 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
  Error: plugin "diff" exited with error
```

**To Reproduce**
1.  Run `./bin/ck8s dry-run wc`

**Expected behavior**

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.29.0
 - "kernelVersion": "5.15.0-1031-aws",
 - "osImage": "Ubuntu 22.04.2 LTS",
 - "containerRuntimeVersion": "containerd://1.6.8",
 - "kubeletVersion": "v1.24.6",
 - "kubeProxyVersion": "v1.24.6",
 - "operatingSystem": "linux",
 - "architecture": "arm64"

**Additional context**
Workload cluster and Service cluster created using kubespray with no errors on AWS EC2 instances.

**Comment by Havoc24k** [comment]
I think I found the cause of this behavior. Based on this commit https://github.com/elastisys/compliantkubernetes-apps/commit/2cae85e3c758f8885c27c3aa2528900ec9915bcb the `dry-run` command will not work due to the lack of support CRDs.

Indeed, when I run `./bin/ck8s apply wc` the error is not being produced.

**Comment by viktor-f** [comment]
Thanks for the report. Sorry for the late reply.
Yes, as you found the `dry-run` command will not work properly before the first install (more particularly before installing the CRDs, as you noted). Supporting `dry-run` before the first apply is not something I think we are planning on supporting (at least not anytime soon).
