### ISSUE TITLE
Enforce TTL on Jobs

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#1483]
**Is your feature request related to a problem? Please describe.**
It is not uncommon to see finished (completed/uncompleted) jobs in a Kubernetes environment lingering forever due to one of the reasons that this can happen (bad history policy, cronjobs updated/removed etc.).
These lingering jobs put unnecessary pressure on the API server and causes bloat metrics.

**Describe the solution you'd like**
In [k8s 1.23 the TTL controller](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) entered stable state.
Also see job [docs](https://kubernetes.io/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically).

In the job spec it is possible to specify `ttlSecondsAfterFinished` which limits the lifetime of a job that has finished execution.

The solution we like is
* Mutate job deployments setting the `ttlSecondsAfterFinished` to a standard of let's say 14 days if not already set.

**Describe alternatives you've considered**
NA

**Additional context**
I feel that this is ADR worthy

We need to update the public docs.
Not sure where the best place is to mention it though.

**Definition of done:**
We are using mutations via Gatekeeper to add the TTL to jobs specs to prevent lingering jobs in Kubernetes created by users and by us.

**Comment by OlleLarsson** [comment]
- [x] Implement in apps
- [x] Update public documentation
- [ ] Write adr

**Comment by Xartos** [comment]
@OlleLarsson Will this be fix by this pr? https://github.com/elastisys/compliantkubernetes/pull/554

**Comment by OlleLarsson** [comment]
yes
