### ISSUE TITLE
[2] Create functions to check versions in the migration library

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#1518]
**Is your feature request related to a problem? Please describe.**
We do not have an easy way of checking the installed version of something within the environment and we should add helper functions to do this.

**Describe the solution you'd like**
Helm helper functions to pull out required information about a release in helm.

**Additional context**
There are probably other functions that could be useful, for example a refresh function to rollback to the current release to reset any manual modifications done to it.

**Definition of done:**
More helper functions added to the migration library.

**Comment by Zash** [comment]
Is this already done in #1461 ? https://github.com/elastisys/compliantkubernetes-apps/pull/1461/files#diff-2ed3d57af802889b01640a6a2c7204b6a253d07fcf7a3fe4df108ad11a3bd994 looks like the functions requested?
