### ISSUE TITLE
[1] Move rclone out of kube-system

### ISSUE THREAD

**Issue by robinelastisys** [elastisys/compliantkubernetes-apps#1544]
**What should be done?**
Suggests that  rclone can be moved out of kube-system. Continue our work by moving rclone out of kube-system and make sure everything works correctly.

**What result should this produce?**
The rclone chart should be moved and its functionality be as expected.

**Comment by Xartos** [comment]
Sugessted solution for this: Move each job to its respective component namespace (i.e. rclone sync job for opensearch into the opensearch-system namespace)
