### ISSUE TITLE
[1] Inconsistent indentation in node-local-dns chart

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#156]
The resource requests/limits are indented 2 spaces more than they should.
See [this line](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/node-local-dns/templates/node-local-dns.yaml#L145).

To be clear, this does not affect the application in any way. It is just an inconsistency.

**Comment by cristiklein** [comment]
Closing. We [updated the Chart](https://github.com/elastisys/compliantkubernetes-apps/commit/a7f4b30a6a3b772f7bbda81cc8b96ac0e3425415) from upstream in the meanwhile.
