### ISSUE TITLE
Test script shows fluentd cronjobs missing

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-apps#1594]
**Describe the bug**
Test scripts check for fluentd cronjobs are returning false error.

Output from script:
```console
<env-name>-audit-<env-name>-sc-compaction		missing ❌
<env-name>-audit-<env-name>-sc-retention	        missing ❌
<env-name>-audit-<env-name>-wc-compaction		missing ❌
<env-name>-audit-<env-name>-wc-retention		missing ❌
<env-name>-sc-logs-logs-compaction	               	missing ❌
<env-name>-sc-logs-logs-retention                       missing ❌
```

But the cronjobs do exist in the environment, although with different names:
```
audit-<env-name>-sc-compaction
audit-<env-name>-sc-retention
audit-<env-name>-wc-compaction
audit-<env-name>-wc-retention
sc-logs-logs-compaction
sc-logs-logs-retention
```

**To Reproduce**
1. Run `ck8s test sc`
2. See error output for cronjob tests
3. Check cronjobs in SC in `fluentd-system` ns
4. See that they do exist

**Expected behavior**
The test script should search for the correct cronjob names.

**Version (add all relevant versions):**
  - Compliant kubernetes apps version `v0.29.1`

**Comment by crssnd** [comment]
this should be fixed in v0.30.0, can you please check
