### ISSUE TITLE
Grafana dashboard for capacity in the clusters

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-apps#1625]
**Is your feature request related to a problem? Please describe.**
Update the current capacity dashboard to include info such as capacity across node groups and create a simpler dashboard for the customer so they can keep track of the usage.

**Describe the solution you'd like**
A new dashboard in grafana and some alerting rules (up for discussion)

**Additional context**

**Definition of done:**
We have a new dashboard to see spare capacity, preferably in node groups.

**Comment by aarnq** [comment]
It would be nice if this would be able to show the overhead on nodes for critical services so we could work around optimising that a bit.

**Comment by Pavan-Gunda** [comment]
Closing in favor of https://github.com/elastisys/compliantkubernetes-apps/issues/1864
