### ISSUE TITLE
[5] Thanos errors - ingesting out of order metrics

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#1637]
**Describe the bug**:

We have seen a problem in several environments where thanos stops ingesting metrics from prometheus, logging:

```log
level=warn ts=2023-06-16T04:09:57.634671053Z caller=writer.go:131 component=receive component=receive-writer msg="Error on ingesting out-of-order samples" numDropped=2
level=warn ts=2023-06-16T04:09:57.634756741Z caller=writer.go:139 component=receive component=receive-writer msg="Error on ingesting samples that are too old or are too far into the future" numDropped=3
```
Prometheus then logs:

```logs
ts=2023-06-16T04:10:00.136Z caller=dedupe.go:112 component=remote level=error remote_name=2640d6 url=http://thanos-receiver-receive.thanos.svc.cluster.local:19291/api/v1/receive msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 409 Conflict: 2 errors: forwarding request to endpoint thanos-receiver-receive-1.thanos-receiver-receive-headless.thanos.svc.cluster.local:10901: rpc error: code = AlreadyExists desc = store locally for endpoint thanos-receiver-receive-1.thanos-receiver-receive-headless.thanos.svc.cluster.local:10901: conflict; forwarding request to endpoint thanos-receiver-receive-0.thanos-receiver-receive-headless.thanos.svc.cluster.local:10901: rpc error: code = AlreadyExists desc = store locally for endpoint thanos-receiver-receive-0.thanos-receiver-receive-headless.thanos.svc.cluster.local:10901: conflict"
```

This generally starts together with node reboots from kured, but I think it's connected to restarts of either the thanos receiver pods or possibly the prometheus pods. When this happens it is possible to "fix" this by deleting the prometheus pods to restart them, but that will drop all metrics from when the problem started to when the prometheus pods are deleted and restarted.

**To Reproduce**:

Steps to reproduce the behaviour:

These steps have not been verified to always trigger this problem.

1. Restart thanos receiver pod (or maybe prometheus pod)
1. See that thanos stops receiving metrics

**Expected behaviour**:

Thanos should be able to handle these situations without getting stuck and without dropping any metrics.

**Screenshots**:

**Version (add all relevant versions)**:

- Compliant Kubernetes apps version 0.29.1

**Additional context**:

**Comment by OlleLarsson** [comment]
Also note that enabling [vertical compaction](https://thanos.io/tip/components/compact.md/#vertical-compactions) seem to be a necessity when enabling the ingestion of out-of-order samples.

**Comment by crssnd** [comment]
also present with the new Thanos version
