### ISSUE TITLE
[1] trivy - does it run a cleanup job

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#1670]
**What should be investigated.**
Trivy creates quite a lot of object in the cluster (e.g vulnerabilityreports, configauditreports). We want to know if it also has a cleanup job to remove the old, unused or outdated one.

**Definition of Done**
- check if trivy has a cleanup job for the old objects
- if yes check if it's configured correctly so it will not allow unnecessary objects to build up

**Comment by robinelastisys** [comment]
Conclusion:

Trivy's TTL function is working just fine. As long as "scannerReportTTL"  isn't empty and holds a valid value, scans will be renewed when the times runs out.
