### ISSUE TITLE
[2] Calico accountant does not work with Ubuntu 22.04

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#1676]
**Describe the bug**:

Calico accountant is not able to gather network policy metrics from nodes running Ubuntu 22.04. It is working on nodes running Ubuntu 20.04.

**To Reproduce**:

Steps to reproduce the behaviour:

1. Have at least one node in the cluster running on Ubuntu 22.04
1. Go to the network policy dashboard in grafana and see that there are no metrics for the pods running on those nodes.

**Expected behaviour**:

Metrics should be gathered on nodes running Ubuntu 22.04.

**Screenshots**:

**Version (add all relevant versions)**:

- Compliant Kubernetes apps version 0.30, 0.31

**Additional context**:

**Comment by aarnq** [comment]
I found the reason, the current image uses the legacy backend for iptables and on 22.04 the nft backend is used. So we either need to modify calico accountant to be able to optionally run with nft or maintain two separate images.
