### ISSUE TITLE
coredns - generating a lot of logs when error

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#1691]
**Describe the bug**:

When coredns (including node-local-dns) has network issues (e.g with the upstream) it will generate a huge amount of logs (thousands) in a short period of time, and overload both fluentd and opensearch.

We want to see if we can decrease the number of error log that it generates, reducing the noise.

**Definition of Done:**
- in care of network issues coredns will generate less error logs, causing less noise

**Comment by llarsson** [comment]
If we're not using the "errors" module, but instead the "log" module, then I understand why we are getting a ton of errors.

If we use the "errors" module instead, it has settings for consolidating error messages, so you don't get this explosion of error printouts.

https://coredns.io/plugins/errors/

> Option consolidate allows collecting several error messages matching the regular expression REGEXP during DURATION. After the DURATION since receiving the first such message, the consolidated message will be printed to standard output with log level, which is configurable by optional option LEVEL. Supported options for LEVEL option are warning,error,info and debug.
>
>2 errors like '^read udp .* i/o timeout$' occurred in last 30s
>
>Multiple consolidate options with different DURATION and REGEXP are allowed. In case if some error message corresponds to several defined regular expressions the message will be associated with the first appropriate REGEXP.
>
>For better performance, it’s recommended to use the ^ or $ metacharacters in regular expression when filtering error messages by prefix or suffix, e.g. ^failed to .*, or .* timeout$.

**Comment by Elias-elastisys** [comment]
The error logs can easily be consolidated like the following example:

```
errors {
    consolidate 5m ".* i/o timeout$" warning
}
```
Although this hides the IP that caused the error:
```
# Before
coredns-645b46f4b6-tsrdv coredns [ERROR] plugin/errors: 2 . NS: read udp 10.233.76.200:36434->1.1.1.1:53: i/o timeout

# After
coredns-645b46f4b6-tsrdv coredns [WARNING] plugin/errors: 110 errors like '.* i/o timeout$' occurred in last 5m0s
```
Is this fine? Also are there other errors than i/o timeout that usually get spammed?

Also to update this for coredns, I assume I would have to change in upstream kubespray or is there some config in ck8s that I'm missing?
