### ISSUE TITLE
[3] prometheus - drop unused metrics

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#1736]
**What should be investigated.**
We want to see that metrics that we currently collect from our applications are not currently used in dashboard or alerts (or by our users).

**Definition of Done**
- create a list of metrics that are not used by our alerts and dashboards
- dropped this metrics if they will not affect the users

**Comment by OlleLarsson** [comment]
Checked the possibility of removing metrics, aka components that support [metric_relabel_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs)

Possible:
- bitnami/fluentd
- harbor
- ingress-nginx
- node-local-dns
- kube-prometheus-stack
- grafana
- elasticsearch-exporter
- thanos
- fluentd-elasticsearch

Not possible:
- cert-manager
- dex
- gatekeeper
- calico-accountant
- calico-felix
- kured
- velero
- tekton
- hnc (?)

**Comment by OlleLarsson** [comment]
No metrics dropped!
A resulting Epic has been created as a result of this ivenstigation on how metrics _could_ be dropped.
