### ISSUE TITLE
[2] Deleting subnamespaces removes resources in the wrong order

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-apps#1746]
**Describe the bug**:

As an application developer, deleting subnamespaces that has resources with finalizers remaining will prevent me from being able to remove the finalizers, because the `workload-admin` rolebinding in the namespaces gets removed as the namespaces terminates.

Also, networkpolicies should be deleted after pods because if a pod is stuck in terminating state because of finalizers, patching the pod is not allowed by gatekeeper constraints, because the pod is no longer attached to a networkpolicy.

**To Reproduce**:

Steps to reproduce the behaviour:

As an application developer, so not cluster-admin privileges
1. Create a subnamespace
1. Create some resource e.g. a pod and add some finalizer to it.
1. Delete the subnamespaceanchor
1. See that the namespace gets stuck in "terminating" state and you no longer have permissions to remove the finalizers.

**Expected behaviour**:

As an application developer, I should be able to clean up finalizers after trying to delete a subnamespace.

**Version (add all relevant versions)**:

- Compliant Kubernetes apps version `v0.31`

**Comment by simonklb** [comment]
> Also, networkpolicies should be deleted after pods because if a pod is stuck in terminating state because of finalizers, patching the pod is not allowed by gatekeeper constraints, because the pod is no longer attached to a networkpolicy.

This _sounds_ to me like a separate issue. Could you confirm if that is the case or if this strictly has to do with subnamespace deletion?

**Comment by simonklb** [comment]
> As an application developer, deleting subnamespaces that has resources with finalizers remaining will prevent me from being able to remove the finalizers, because the `workload-admin` rolebinding in the namespaces gets removed as the namespaces terminates.

If I understand the issue correctly this also doesn't sound like a problem specifically related to subnamespaces but RBAC in general. If the a rolebinding is created in a namespace and that rolebinding is necessary to remove the finalizers you have set yourself up for a deadlock if you're not careful when you delete that namespace. Please correct me if I'm wrong though.

**Comment by simonklb** [comment]
Related upstream issue: https://github.com/kubernetes/kubernetes/issues/115070

**Comment by simonklb** [comment]
Moving this issue to `Blocked/stale` as it's not clear to me that this is something we could fix other than informing users to be more careful when deleting namespaces, i.e. make sure to delete all the workloads first.

**Comment by simonklb** [comment]
Closing this since AFAICT there is no difference between the deletion order of normal namespaces and subnamespaces. Please track the upstream issue linked above if you want to follow the progress of this. Feel free to reopen if you disagree.
