### ISSUE TITLE
[0] Show documentation URL in Gatekeeper error messages

### ISSUE THREAD

**Issue by llarsson** [elastisys/compliantkubernetes-apps#1748]
**Is your feature request related to a problem? Please describe.**

The problem is that we have Gatekeeper-enforced safeguards in place that people might not understand.

**Describe the solution you'd like**

If a request would violate a safeguard, Gatekeeper will stop it. We should help users understand what went wrong by putting links to our documentation in the error message.

So instead of this:

```
$ kubectl run nginx --image=nginx --restart=Never
Warning: [require-harbor-repo] container "nginx" has an invalid image repo "nginx", allowed repos are ["harbor.long-running.dev-ck8s.com", "quay.io/jetstack/cert-manager-acmesolver", "quay.io/metallb/controller:v0.13.7", "jaegertracing/jaeger-tracegen"]
Error from server (Forbidden): admission webhook "validation.gatekeeper.sh" denied the request: [require-resource-requests] Container "nginx" has no resource requests
[container-image-must-not-have-disallowed-tags] container <nginx> didn't specify an image tag <nginx>
```

...imagine if each error message linked to the appropriate safeguard that we have put in place.

**Describe alternatives you've considered**

Not doing it, I suppose. But stuff like "has no resource requests" is a very short and unhelpful way of putting it, so it would be better if it was more helpful and also linked to the docs, which we can easily improve upon as well.

**Definition of done:**

- [ ] All the safeguards that we put in place have appropriate links in their error messages (see screenshot below for which these are)
- [ ] Optional: It is made clear that we are the ones making the rules, by using a prefix such as `elastisys-` for each rule
- [ ] Deploying to the long-running cluster, so that we can see this running live

![image](https://github.com/elastisys/compliantkubernetes-apps/assets/1425662/7e864cc3-f112-4517-9844-cdea1a9b62a1)

Ideally, instead of `[container-image-must-not-have-disallowed-tags] container <nginx> didn't specify an image tag <nginx>`, it would be: `[elastisys-container-image-must-not-have-disallowed-tags] The container named <nginx> didn't specify an image tag. Elastisys Compliant Kubernetes requires all images to have tags to avoid the implicit :latest tag. Read more at https://elastisys.io/compliantkubernetes/user-guide/safeguards/enforce-no-latest-tag/`

**Comment by cristiklein** [comment]
Smart!

**Comment by llarsson** [comment]
This really has two tasks in it, namely:

- [ ] The actual textual changes (should be super small, given it's a handful of strings that need changing) 
- [ ] Deploying to the long-running cluster, so that we can see this running live
