### ISSUE TITLE
Self-managed Flux family of components

### ISSUE THREAD

**Issue by llarsson** [elastisys/compliantkubernetes-apps#1754]
**Is your feature request related to a problem? Please describe.**

If one has invested a lot of time into making CD processes smooth with the Flux family of components (definitely Flux itself, possibly Flagger, and potentially more as discovered in conjunction with external stakeholders), it would be lovely to use the self-managed CRD feature (https://github.com/elastisys/compliantkubernetes-apps/pull/1716) to let Customers self-manage these components.

**Describe the solution you'd like**

The dream? That Customers can just go to https://fluxcd.io/flux/installation/bootstrap/github/ and install Flux using the official CLI. And that they then look toward the top of that bar and go "oh yeah, we need Flagger, too", and install that as well.

And that it all just works flawlessly. :smile: 

**Describe alternatives you've considered**

I seem to recall some internal discussion about maybe adding [Flamingo](https://github.com/flux-subsystem-argo/flamingo), which combines Flux and Argo in some fashion. The internal architecture forum discussion ticket for that is [here](https://github.com/elastisys/ck8s-arch/issues/30).

Given that if you're familiar with Flux, you want **actual Flux**, I would prefer not a "kind of Flux" but **actual Flux**.

**Additional context**

N/A

**Definition of done:**

- [ ] Self-managed CRD/cluster resources are in place such that a Customer, using their normal permissions, can follow the official Flux installation procedure using the CLI -- let's target GitHub compatibility first and foremost (I don't know if these differ substantially)
- [ ] **(optional)** ... as above, but for Flagger as well
- [ ] Documentation on our .io site for this self-managed service (to be in the appropriate repo)

**Comment by llarsson** [comment]
This, of course, requires us to understand if the security implications are within what we deem acceptable or not.

https://fluxcd.io/flux/security/#controller-permissions

Who would give such a verdict? Is that an @ayoub-eddafali task? :thinking:

**Comment by llarsson** [comment]
> However in a [soft multi-tenancy setup](https://github.com/fluxcd/flux2-multi-tenancy), Flux does not reconcile a tenant’s repo under the cluster-admin role. Instead, you specify a different service account in your manifest, and the Flux controllers will use the Kubernetes Impersonation API under cluster-admin to impersonate that service account [2](https://fluxcd.io/flux/security/#fn:2). In this way, policy restrictions for this service account are applied to the manifests being reconciled. If the binding is not defined for the correct service account and namespace, it will fail. The roles and permissions for this multi-tenancy approach are described in detail here: https://github.com/fluxcd/flux2-multi-tenancy.

This sounds like what we offer. If we can have the Flux controllers use the Customer's (restricted) user-admin role, then that would be pretty great, wouldn't it?

Perhaps that requires us to check for that setting when they install, using OPA, and reject if they try to circumvent it? I don't know. Just throwing ideas out there.

**Comment by anders-elastisys** [comment]
I tested Flamingo before, there is some documentation on it in the knowledge-base repo [here](https://github.com/elastisys/knowledge-base/tree/main/flamingo-ck8s).

**Comment by llarsson** [comment]
Thanks for linking that, @anders-elastisys! However, the way I understand Flamingo, it's basically replacing Argo CD with "this feels kind of like Argo CD" as implemented by Flux CD, instead. The architecture forum was against this, and wanted to go ahead with pure Argo instead.

**Comment by viktor-f** [comment]
> From https://fluxcd.io/flux/security/#controller-permissions
> 
> > However in a [soft multi-tenancy setup](https://github.com/fluxcd/flux2-multi-tenancy), Flux does not reconcile a tenant’s repo under the cluster-admin role. Instead, you specify a different service account in your manifest, and the Flux controllers will use the Kubernetes Impersonation API under cluster-admin to impersonate that service account [2](https://fluxcd.io/flux/security/#fn:2). In this way, policy restrictions for this service account are applied to the manifests being reconciled. If the binding is not defined for the correct service account and namespace, it will fail. The roles and permissions for this multi-tenancy approach are described in detail here: https://github.com/fluxcd/flux2-multi-tenancy.
> 
> This sounds like what we offer. If we can have the Flux controllers use the Customer's (restricted) user-admin role, then that would be pretty great, wouldn't it?
> 
> Perhaps that requires us to check for that setting when they install, using OPA, and reject if they try to circumvent it? I don't know. Just throwing ideas out there.

@llarsson I might not be reading this correctly. But that sound like flux still needs cluster-admin permissions and that it just impersonates specific service accounts for some actions. If that is correct then the customer would not be able to install it since they do not get cluster-admin privileges.

**Comment by llarsson** [comment]
@viktor-f, I also read it the way you do. Hmm. :thinking: 

Perhaps this would be a special case where we would have to treat at least part of Flux as a "privileged application" instead, in that we would install the needed part for them, because they would not be able to install it themselves.

Because the division that is displayed here (taken from https://github.com/fluxcd/flux2-multi-tenancy) matches what we would typically want:

![image](https://github.com/elastisys/compliantkubernetes-apps/assets/1425662/b8c3be12-4bce-4c63-ad53-e9e60525ad91)

The Tenant in that division doesn't need more permissions than we are comfortable giving them.

**Comment by viktor-f** [comment]
If we install it for them then I think we need to be sure that they then cannot abuse the flux installation to escalate their privileges. We also want to be sure that this does not create a large amount of overhead for us, if this is supposed to be a self-managed app, e.g. I don't want a ticket every time they create a new namespace because they need us to allow them to use flux there. But I guess that is something that would be tested in this task, so we do not need to speculate on that now.

**Comment by llarsson** [comment]
Well, this looks very promising!

![image](https://github.com/elastisys/compliantkubernetes-apps/assets/1425662/9dd0acaa-1d60-4f83-b788-cce872d17a61)

**Comment by llarsson** [comment]
https://fluxcd.io/flux/components/kustomize/kustomizations/#remote-clusterscluster-api

> If you wish to target clusters created by other means than CAPI, you can create a ServiceAccount on the remote cluster, generate a KubeConfig for that account and then create a secret on the cluster where kustomize-controller is running.

**Comment by llarsson** [comment]
There has been security-related discussion about this one, and someone from @elastisys/scrum-masters will get into this ticket to help describe the security-related implications that we need to address for this to be possible to take forward. So, @AlbinB97 and @Mlundm, expect some help with newly formulated requirements.

In summary, there are two possible approaches to investigate, and they are ordered in order of preference:

1. “Running Flux inside the cluster, but without ClusterAdmin permissions”, which would be that it's about making a hole for this using CRD-self-management and then making sure that permissions can be reduced, so that a customer could still self-manage the entire Flux system themselves, if at all possible.
2. “Run Flux outside of the cluster, and manage resources in the cluster from there”. This seems very possible, and is a “fully-supported use-case”, as one of the maintainers puts it https://github.com/fluxcd/flux2/discussions/2258 -- while this is perhaps the easiest for us to implement, given that it's supposedly a supported use-case, it is also the least convenient for customers. That's why it's not at the top of the list.

**Comment by viktor-f** [comment]
I will be the contact from the MSE team for this task.

The last comment from @llarsson captured the things we currently want to investigate. Let me know if you have any questions about the two approaches. Please let me know once you have investigated the first approach and we can discuss what you have found.
