### ISSUE TITLE
[1] Pipeline cant access secrets

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-apps#184]
The pipeline doesnt seem to read keys from the secrets.yaml file, for example when linting the ck8sdash chart.

`in /github/workspace/helmfile/01-applications.yaml: failed to render values files "values/ck8sdash-common.yaml.gotmpl": failed to render [values/ck8sdash-common.yaml.gotmpl], because of template: stringTemplate:14:20: executing "stringTemplate" at <.Values.dex.kubeloginClientSecret>: map has no entry for key "kubeloginClientSecret"`

This is probably due to an issue with sops not correctly accessing the PGP-key, as a quick debugging attempt turned up the following error message:

```
Failed to get the data key required to decrypt the SOPS file.
Group 0: FAILED
  529D964DE0BBD900C4A395DA09986C297F8B7757: FAILED
    - | could not decrypt data key with PGP key:
      | golang.org/x/crypto/openpgp error: Could not load secring:
      | open /root/.gnupg/secring.gpg: no such file or directory;
      | GPG binary error: exit status 2
Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful, but none were.
```
Fix the error and turn on linting for ck8sdash and kubeapi-metrics

**Definition of done:** the pipeline goes through the lint stage without errors even if charts that need secrets are linted.

**Comment by Xartos** [comment]
If you are running the pipeline in this repo it shouldn't work since we do not have any secrets in this repo. Please check the pipelines repo

**Comment by Xartos** [comment]
On closer inspection, we seem to have a test PGP key here https://github.com/elastisys/compliantkubernetes-apps/blob/main/pipeline/sops-pgp-setup.bash
So I guess there is some issue with the linter script accessing it.

**Comment by tordsson** [comment]
Still relevant as the pipeline has been moved inside apps repo?

**Comment by viktor-f** [comment]
> Still relevant as the pipeline has been moved inside apps repo?

This is not the end-to-end pipeline that we moved. This issue is refering to the UnitTests-pipeline https://github.com/elastisys/compliantkubernetes-apps/blob/main/.github/workflows/pipeline.yml
