### ISSUE TITLE
[2]Make nginx be able to read only tls secrets from all namespaces.

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-apps#1854]
**Describe the bug**:
Recently a lot of vulnerabilities were discovered in Ingress-nginx that could let an application developer inject code via annotations and obtain the credentials of ingress-nginx controller. By default, this credentials has access to reading all secrets in the cluster. 

Create an OPA policy and restrict nginx's credential so it does not have access to critical secrets such as cloud credentials or just make it so that it only is able to read tls secrets.

**Version (add all relevant versions)**:

- Compliant Kubernetes apps version 33 and below.

**Comment by davidumea** [comment]
This is not possible to solve with gatekeeper since the [Kubernetes admission API](https://github.com/kubernetes/kubernetes/blob/v1.28.3/pkg/apis/admission/types.go#L157-L166) doesn't check for "READ" (get/list/watch) operations.

Will likely opt for solving this with RBAC.

**Comment by davidumea** [comment]
https://github.com/elastisys/compliantkubernetes-apps/pull/1865
