### ISSUE TITLE
[5] Fix ck8s version validate

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#189]
The current version validation does not work anymore as it [tries to find the latest tag on main](https://github.com/elastisys/compliantkubernetes-apps/blob/main/bin/common.bash#L70-L74). The problem now is that we do not have all tags on main. The current way to get around it is to use `global.version: any` in the configs.

I don't know how this should be fixed but the goal is to be able to specify a tag and not just `any` in the configs.

**Comment by tordsson** [comment]
Pending larger configuration management discussion
