### ISSUE TITLE
[1] Upgrade falco to version v0.36.2

### ISSUE THREAD

**Issue by lucianvlad** [elastisys/compliantkubernetes-apps#1908]
**What Chart should be upgraded?**:

upstream/falco https://github.com/falcosecurity/charts/blob/falco-3.8.5/charts/falco/Chart.yaml

Make sure to also update the [falco-sidekick](https://github.com/falcosecurity/charts/blob/master/falcosidekick/Chart.yaml)

**Why should this Chart be upgraded?**:

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

**Acceptance criteria**:

- I checked the migration of the new Chart:
  - [ ] I upgraded a Chart and determined that no migration steps are needed.
  - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by viktor-f** [comment]
As part of this issue, please also look at updating the falco rules to [v3.0.0](https://github.com/falcosecurity/rules/releases/tag/falco-rules-3.0.0).
