### ISSUE TITLE
[2] Upgrade trivy-operator

### ISSUE THREAD

**Issue by lucianvlad** [elastisys/compliantkubernetes-apps#1909]
**What Chart should be upgraded?**:

upstream / trivy-operator https://github.com/aquasecurity/trivy-operator/releases/tag/v0.17.1

**Why should this Chart be upgraded?**:

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

**Acceptance criteria**:

- I checked the migration of the new Chart:
  - [ ] I upgraded a Chart and determined that no migration steps are needed.
  - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by viktor-f** [comment]
As part of this issue I'd also like us to expose config to set scan job resources: https://github.com/elastisys/compliantkubernetes-apps/blob/36842695dd80cf80ebed4fa9d2438190b41ab210/helmfile.d/upstream/aquasecurity/trivy-operator/values.yaml#L381
