### ISSUE TITLE
[3] Tutorial: Compliant Kubernetes on Exoscale SKS

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#191]
Acceptance criteria:

- https://compliantkubernetes.io/operator-manual/lifecycle/exoscale-sks contains prose and code which allows someone to set up Compliant Kubernetes on Exoscale SKS.
- Said document contains code that can be copy-pasted.
- Said code has all "hard-coded" file locations, paths, key names, cluster names, etc. in shell variables.

**Comment by OlleLarsson** [comment]
Still relevant?

**Comment by cristiklein** [comment]
I'd say no. @tordsson
