### ISSUE TITLE
[3] Tutorial: Compliant Kubernetes on OVH Managed Kubernetes

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#192]
Acceptance criteria:

- https://compliantkubernetes.io/operator-manual/lifecycle/ovh-kubernetes contains prose and code which allows someone to set up Compliant Kubernetes on OVH Managed Kubernetes
- Said document contains code that can be copy-pasted.
- Said code has all "hard-coded" file locations, paths, key names, cluster names, etc. in shell variables.

**Comment by Xartos** [comment]
@cristiklein I'm guessing https://compliantkubernetes.io/operator-manual/lifecycle/ovh-kubernetes actually means https://compliantkubernetes.io/operator-manual/ovh-kubernetes ?

**Comment by cristiklein** [comment]
@Xartos You are guessing correctly. :smile: Thanks for noticing.
