### ISSUE TITLE
[3] Release 0.10.0

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#193]
Fork from master, QA/bugfixing and create the release 0.10.0 

Included tasks: 
- Document bug fixes: 1 day
- Automate Harbor + OPA checks: 1 day
- Upgrading apps: 1 day

**Comment by tordsson** [comment]
Investigate need for hot cluster where every PR is tested to complement the daily (nightly) pipelines...

**Comment by tordsson** [comment]
See also https://github.com/elastisys/compliantkubernetes-apps/issues/209
