### ISSUE TITLE
[1] Formally deprecate ck8s-cluster and promote kubespray

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#195]
We have been leaning more and more toward kubespray for cluster life-cycle management. Despite this, we still mention ck8s-cluster in the readme and do not mention kubespray anywhere.
To make it easier to understand how to get started and to avoid guiding users to ck8s-cluster, we should make these things clear in the readme. Preferrably, this could be done after we have [investigated a possible migration path from ck8s-cluster to kubespray](https://github.com/elastisys/ck8s-ops/issues/47) and moved the pipeline to kubespray. Then we could also describe how to move from ck8s-cluster to kubespray.

Definition of done: There is no mention of ck8s-cluster in this repo and there is a short description (or link) to explain how to set up a cluster to run compliantkubernetes-apps in.

**Comment by tordsson** [comment]
Deprecate ck8s-base-vm as well?

**Comment by OlleLarsson** [comment]
Sure, i created https://github.com/elastisys/ck8s-base-vm/issues/29
