### ISSUE TITLE
Apply chaos engineering on Thanos Receive

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#1984]
### Proposed feature

We want to investigate the behaviour of Thanos Receive during failures, we want to ensure that it can keep ingesting metrics even if a replica goes down, and we want to ensure that it can recover once a cluster is healthy again without issues.

### Proposed alternatives

I want us to setup tests using a framework like chaos-mesh or similar and our Thanos setup, and test various failure scenarios to get better understanding of the resilience of our setup.

### Additional context

We have previously seen that Thanos Recieve (both ingesting and routing) can have very high memory spikes during both failure and recovery events. This needs to be tested in multiple configurations:
- The effect of rate limiting on remote-write has
- The effect of having additional ingesting Thanos Recieve replica so ingestion can continue even with failure
- [The effect of swapping hash algorithm used for the routing Thanos Recieve to the new recommended Ketama](https://thanos.io/tip/components/receive.md/#series-distribution-algorithms)

### Definition of done

- [ ] Investigation document and recommendation for improvements to our deployment of Thanos.

**Comment by LundqvistAndre** [comment]
We have found an issue with the thanos receiver and consensus around 2 node setup, were there a reason for only 2 instances, since the solution we found is to increase the number of instance to 3.

**Comment by viktor-f** [comment]
@Pavan-Gunda tested 3 replicas at one point in this task https://github.com/elastisys/ck8s-ops/issues/3510 (it's in ops, so unfortunately you don't have access to it).
@Pavan-Gunda what was the conclusions of those tests?

**Comment by Pavan-Gunda** [comment]
> @Pavan-Gunda tested 3 replicas at one point in this task [elastisys/ck8s-ops#3510](https://github.com/elastisys/ck8s-ops/issues/3510) (it's in ops, so unfortunately you don't have access to it). @Pavan-Gunda what was the conclusions of those tests?

I know we've installed/tested this to see if we can reuse the same bucket and if it possible to implement it in general. We found that it is possible to reuse the same bucket and setup thanos with replication factor and replicas set to 3 and there is no other migration path needed. This setup is currently running in lr-safespring.
