### ISSUE TITLE
[5] Rework configuration templates

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#2018]
### Proposed feature

Currently we write infrastructure provider defaults during init, we should move this into plain configuration files that we merge during init instead.

We should also consider merging the sc and wc secrets as that is whats done anyway.

### Proposed alternatives

So the `config/` dir instead contains:

- `flavours/<flavours...>/`
- `providers/<infrastructure-providers...>/`
- `common-config.yaml`
- `sc-config.yaml`
- `wc-config.yaml`
- `secrets.yaml`

And then the init scripts will for flavours lookup if such a flavour exists under `config/flavours/` and similar for infrastructure providers in `config/providers/`.

### Additional context

If we would want to, for example to add commonality for OpenStack providers, we could add a `meta.yaml` which we could declare other flavours or providers to drag into the merge.

### Definition of done

- [ ] Reworked configuration templates

**Comment by Ajarmar** [comment]
This is labeled as a 2-person task, but you can start on it with one person.
