### ISSUE TITLE
[2] Upgrade Velero chart

### ISSUE THREAD

**Issue by AlbinB97** [elastisys/compliantkubernetes-apps#2031]
### Chart to upgrade

vmware-tanzu/velero

### Reason for upgrade

- [X] Security patching
- [X] Upgrade to allow new features
- [X] Upgrade to prevent future issues
- [ ] Other - _Write the reason below_

### Additional context

Velero has been updated to fix CVEs. There's also some new features that could be useful, take a look at the changes here: https://github.com/vmware-tanzu/velero/releases

### Acceptance criteria

- I checked the migration of the new chart version:
  - [ ] The upgrade does not require migration steps
  - [ ] The upgrade requires migration steps
- I tested the functionality of the new chart version:
  - [ ] The upgrade does not change current functionality
  - [ ] The upgrade changes current functionality

**Comment by anders-elastisys** [comment]
@Elias-elastisys as there was no chart released using Velero version v1.13.1, it currently uses v1.13.0. So if this is still needed I suggest that we either add templating for overriding the image version, or we update the chart once [this version is released](https://github.com/vmware-tanzu/helm-charts/pull/557).
