### ISSUE TITLE
Option to manage node authorized SSH keys in apps

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-apps#2047]
### Proposed feature

Currently we let whatever K8s installer is used manage which SSH keys are authorized on the underlying nodes.

There should be an option to manage this through apps config.

### Proposed alternatives

We should manage this by accepting a list of SSH keys in the apps config, which is then put in a configmap, this configmap can then be mounted as a volume on each node in a specified location (e.g. `~/.ssh/authorized_keys`) via a daemonset.

### Additional context

It should work like the [file-copier chart](https://github.com/elastisys/compliantkubernetes-apps/tree/main/helmfile.d/charts/file-copier) except it should have its own trigger to be enabled.

It would probably be best to add it this feature to the same chart.

### Definition of done

Node authorized SSH keys can be managed through apps config.

**Comment by cristiklein** [comment]
Thanks @davidumea . I feel this needs a discussion in the arch forum.

Personally, I'm rather hesitant. I kind of like the idea of setting up Compliant Kubernetes and access to it layer-by-layer:

- Infrastructure
- Kubernetes
- Apps

I see a risk that setting up SSH keys from a layer above might violate [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).
