### ISSUE TITLE
[2] Add configuration option to "user api server" status in blackbox exporter

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#207]
**Is your feature request related to a problem? Please describe.**
The current configuration assumes that the workload cluster api server is available at `https://kube-apiserver.{{ .Values.global.baseDomain }}:/healthz`. This is a problem primarily if you are running multiple workload clusters, then blackbox exporter will at best monitor one of them. If the apiserver is not connected to this URL, then the metric will say that the apiserver is failing and the uptime dashboard will also show this (even though the apiserver(s) might work as expected).

**Describe the solution you'd like**
Add config that allows us to specify any amount of apiservers that blackbox should check.
Also make sure that the uptime dashboard can show the status of multiple apiservers. 

**Describe alternatives you've considered**
The only other alternative I see is to have an option to disable this metric, so that it at least does not give any misinformation.

**Additional context**
This is how the uptime dashboard looks now in my setup.
![broken-blackbox](https://user-images.githubusercontent.com/58632240/105812403-5fbb7100-5fae-11eb-965b-0adc8bae12bf.png)

**Definition of done:**
There is config that allows us to specify any number of apiservers to check.
The uptime dashboard can show uptime for multiple apiservers.

**Comment by lentzi90** [comment]
As part of this issue, please also make blackbox exporter [verify TLS](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/blackbox.yaml.gotmpl#L23) based on the [global config](https://github.com/elastisys/compliantkubernetes-apps/blob/main/config/config/sc-config.yaml#L8).

**Comment by tordsson** [comment]
Will be replaced by: https://github.com/elastisys/ck8s/issues/102
