### ISSUE TITLE
Admin namespaces not installed and ready before other charts

### ISSUE THREAD

**Issue by Elias-elastisys** [elastisys/compliantkubernetes-apps#2070]
### Experienced behaviour

Several times now when I have run `./bin/ck8s apply sc` on a completely fresh cluster, the apply has failed because some namespace is not available as the rest of the charts are getting installed. For example:

```
FAILED RELEASES:
NAME                                        CHART                                              VERSION
kube-state-metrics-extra-resource-metrics   charts/kube-state-metrics-extra-resource-metrics

STDERR:
  Error: create: failed to create: namespaces "monitoring" not found

COMBINED OUTPUT:
  Release "kube-state-metrics-extra-resource-metrics" does not exist. Installing it now.
  Error: create: failed to create: namespaces "monitoring" not found
```

Re-running apply will then work correctly as the namespaces have had time to finish applying.

### Expected behaviour

I expect apply on a fresh cluster to work without issues.

### Steps to reproduce

1. Create a new cluster
2. Run `/bin/ck8s apply sc`

### Compliant Kubernetes Apps Version

v0.36.1

### Kubernetes Version

v1.28.6

**Comment by cristiklein** [comment]
We determined that the issue is at two levels:

1. QA is done via devbox, which means that we don't really test if the apps scripts work without devbox.
2. Some ordering of the Charts is done from within devbox, whereas it should be done from apps.

@Elias-elastisys will talk to @aarnq to figure out what's the best way forward.

**Comment by simonklb** [comment]
This feels like a regression because I did not experience this before, even without devbox in play.

**Comment by Elias-elastisys** [comment]
> This feels like a regression because I did not experience this before, even without devbox in play.

This is new in 0.36 because before that we still used the old bootstrap command for the namespaces. Now namespaces are just another chart in helmfile.

**Comment by Elias-elastisys** [comment]
I talked to Andre. It turns out this was more so an issue with CAPI environments, and CAPI not being supported by devbox yet. This release that failed is only installed for CAPI, so it was missed that it didnt have the correct dependencies set up. 

Andre suggested better testing instead of changing the QA process as there are frameworks for helmfile testing that could ensure that stuff like this is caught before even getting to QA. Andre will look into that.

As for devbox, we both feel as if it still doing too many manual steps or doing things in weird order that we should still discuss and change or move to apps. But since this was not the main source of this issue it is not as urgent.

**Comment by cristiklein** [comment]
Thanks for the update!
