### ISSUE TITLE
[2] Change velero config to use CSI and data movement

### ISSUE THREAD

**Issue by Elias-elastisys** [elastisys/compliantkubernetes-apps#2076]
### Proposed feature

Change velero config to use CSI and data movement. 
Requires v1.13.1 and this issue: https://github.com/elastisys/compliantkubernetes-apps/issues/2075
As well as snapshot controller from Kubespray or CAPI

Make sure its configurable so that we can switch slowly, and so that we can use both old and new backup solution for some time.
Arch topic for context: https://github.com/elastisys/ck8s-arch/issues/151

### Definition of done

- [ ] CSI and volume snapshot data movement enabled
- [ ] Gatekeeper mutations for helper pods

**Comment by anders-elastisys** [comment]
[This PR](https://github.com/elastisys/compliantkubernetes-apps/pull/2121) will add templating for switching uploader type. Part of this issue should be to update the config and migrate from `restic` to `kopia`.
