### ISSUE TITLE
Standalone cluster for development

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#212]
It would be very nice to be able to create a cluster for development purposes with all the correct policies and restrictions that comes with a full blown ck8s environment. This would be useful not just for internal development but also for customers that want development or test environments that mimics ck8s. Additionally, it would be a nice proof that ck8s-cluster works as a standalone project/product!

I have come up with the following things that would be needed for this:

~- Get rid of DNS, it is not useful for ck8s-cluster on its own. elastisys/ck8s-cluster-old#76~
~- Get rid of S3 buckets, they are not useful for a bare cluster. elastisys/ck8s-cluster-old#75~
Fixed by kubespray: ~- Move Gatekeeper to ck8s-cluster, or create instructions for how to set it up here manually.~
- Configure a "customer user" with limited privileges and create a kubeconfig for this user?
Fixed by kubespray: ~- Move cert-manager to ck8s-cluster? It is a pretty fundamental application, maybe it could be considered part of the cluster?~ 
- Prometheus? It may be needed to test and develop prometheus metrics and alerts, how can we support this?

**Comment by tordsson** [comment]
Telepresence can be a partial solution here: https://www.telepresence.io/tutorials/kubernetes-rapid

**Comment by tordsson** [comment]
ck8s-devbox and increased maturity overall makes this less important.

**Comment by cristiklein** [comment]
Can we close this, thanks to the long-running cluster?

**Comment by OlleLarsson** [comment]
Closing this as we have apps on kind now :)
