### ISSUE TITLE
[1] Default for proxy protocol

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#214]
**Describe the bug**
We don't provide a default value for `useProxyProtocol` even though it should basically always be set to `false` now when using kubespray.

**To Reproduce**
1. Initialize a config repo
2. Note that `ingressNginx.controller.config.useProxyProtocol` is set to `set-me`.

**Expected behavior**
Since `false` is the upstream default and we rarely use anything other, I think the default for us should also be `false`.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version: v0.9.0

**Additional context**
We previously used the proxy protocol on certain cloud providers when ck8s-cluster set up a HAProxy instance in front of the cluster. This is no longer the case since we are switching to kubespray.

**Comment by OlleLarsson** [comment]
Turns out that it is acutally set to either `true` or `false` after `./bin/ck8s init`.
But still the false for safespring needs to be changed from true to false.
