### ISSUE TITLE
[2] Collect the config files when calling diagnostic script

### ISSUE THREAD

**Issue by salehsedghpour** [elastisys/compliantkubernetes-apps#2154]
### Proposed feature

 > [!warning]
        > **This is a public repository, ensure not to disclose:**
        >
        > - [x] personal data beyond what is necessary for interacting with this issue, nor
        > - [x] business confidential information, such as customer names.

To better support SME customer, we discussed initially to collect the config files (X-config.yaml) when calling ` ./bin/ck8s diagnostics` script.  

### Proposed alternatives

It can basically fetch the values from configs and encrypt them with the existing keys and finally add them to the output.

### Definition of done

- [ ] Running `./bin/ck8s diagnostics` results in config files (sc-config, wc-config and common-config) being collected and encrypted as part of the output.
- [ ] This new feature is covered by public documentation

**Comment by OlleLarsson** [comment]
Hi @salehsedghpour please update the issuey to not disclose any private internal information (github repos and documents) here as this is a public repository

**Comment by salehsedghpour** [comment]
Thanks for highlighting this @OlleLarsson
