### ISSUE TITLE
[1] Rclone jobs stuck in running as their pods stop after some time

### ISSUE THREAD

**Issue by lucianvlad** [elastisys/compliantkubernetes-apps#2173]
### Experienced behaviour

Discovered that rclone jobs remain stuck in running and their associated pods are stopped after about 10 minutes.
When rerunning the jobs and looking at the logs, for some of them I got the error just before the pod is terminated:
```
INFO  : Signal received: terminated
ERROR : indices/iGoJDsmKQxiyk42HiYIZ8w/0/__NT8ET9A4Tvu3LD3KRZ2T0w: Failed to copy: multipart upload failed to upload part: RequestCanceled: request context canceled
caused by: context canceled
INFO  : Exiting...
```
On some got less:
```
INFO  : Signal received: terminated
INFO  : Exiting...
```
And most of the pods just exited with nothing in the logs.
After that the jobs are stuck in running.
This was observed in many different environments on different Infra Providers all running variations of apps v0.38 including the branch [v0.38.1+rclone-netpol-fix+harbor-alert-fix](https://github.com/elastisys/compliantkubernetes-apps/compare/v0.38.1+rclone-netpol-fix+harbor-alert-fix)

### Expected behaviour

The rclone job runs without issues till completion

### Steps to reproduce

Create a  rclone job from existing cronjobs (a good candidate would be opensearch cronjob)
If the job runs for more than 10 min's it will fail as described above.

### Compliant Kubernetes Apps Version

v0.38.*

**Comment by Pavan-Gunda** [comment]
Atleast some of these jobs are getting killed because we set a hard deadline on jobs for 600s [here](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile.d/charts/rclone/values.yaml#L8C1-L8C22). Should we make this configurable ? @viktor-f @OlleLarsson

**Comment by viktor-f** [comment]
I'm not really sure what is reasonable for a rclone job. But I'd be ok with increasing that default and making it configurable.

**Comment by lucianvlad** [comment]
Currently many of our rclone jobs are incomplete so this means we are not confirming to what we say [here](https://elastisys.io/compliantkubernetes/user-guide/backup/#protection-of-backups) which is also linked in the TOS [here](https://github.com/elastisys/terms?tab=readme-ov-file#a24-backup-and-disaster-recovery)
