### ISSUE TITLE
[2] Changing s3 endpoint does not update all velero objects

### ISSUE THREAD

**Issue by davidumea** [elastisys/compliantkubernetes-apps#2204]
### Experienced behaviour

When changing s3 endpoint in an existing environment, velero still tries to push volume backups to the old endpoint.

This is because the `backuprepositories.velero.io` objects still have the `resticIdentifier` spec pointing to the old endpoint, this does not get updated when the s3 endpoint is changed in config.

### Expected behaviour

All velero objects that use s3 endpoint should be updated when s3 endpoint is changed in config. Velero should push all backups to the endpoint that is configured.

### Steps to reproduce

1. Make sure that the environment has some volumes (to be restored).
2. Create a velero backup `velero backup create --from-schedule velero-daily-backup --wait`.
3. Change `objectStorage.s3.regionEndpoint` to a new endpoint.
4. Apply apps.
5. (Optional, to make the problem more obvious) Delete the old s3 location.
6. Create a velero backup `velero backup create --from-schedule velero-daily-backup --wait`.
7. See velero backup errors.
8. See that the `backuprepositories.velero.io` objects still have the old endpoint specified.

### Compliant Kubernetes Apps Version

v0.38.2

### Kubernetes Version

v1.28.6

**Comment by Zash** [comment]
Could reproduce on the `release-0.38` branch but on the `main` branch (and presumably on Apps 0.39.x) Velero will "re-establish on BSL change" when changing the S3 location and then update the `backuprepositories` objects after a few minutes.

This was done on a local kind cluster with a `defaultVolumeType=local` annotation added to the `storageclasses.storage.k8s.io/standard` object.
