### ISSUE TITLE
[2] Rclone : Offsite backup support for the primary ck8s cluster on azure

### ISSUE THREAD

**Issue by raviranjanelastisys** [elastisys/compliantkubernetes-apps#2206]
### Proposed feature

We need to implement offsite backup support for our primary Azure cluster using Rclone. This will ensure that our data is securely backed up to an offsite location, providing redundancy and protection against data loss.

### Proposed alternatives

N/A

### Additional context

N/A

### Definition of done

 Azure offsite backup support are thoroughly addressed and integrated in our apps

**Comment by Zash** [comment]
Tested rclone in various configurations

- [x] primary on azure, sync to (openstack) s3
- [x] rclone sync in opposite direction
- [x] primary on (openstack) s3, sync to azure
- [x] rclone sync in opposite direction

**Comment by Zash** [comment]
Tested rclone in various configurations

- [x] primary on azure, sync to (openstack) s3
- [x] rclone sync in opposite direction
- [x] primary on (openstack) s3, sync to azure
- [x] rclone sync in opposite direction

**Comment by Zash** [comment]
#2219 contains some fixes for some configurations that are likely uncommon or they would likely have been noticed earlier, nothing directly related to azure
