### ISSUE TITLE
[3] Implement ADR-0006: "Use Standard Kubeconfig Mechanisms"

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#221]
See full rationale in the ADR: https://github.com/elastisys/compliantkubernetes/blob/adr-kube-context/docs/adr/0006-use-standard-kubeconfig-mechanisms.md

**Definition of done:**

* I can use standard Kubeconfig mechanisms to install the service cluster or workload cluster on two vanilla Kubernetes clusters.
* Documentation is updated accordingly.

**Comment by raviranjanelastisys** [comment]
This issue will be addressed here - https://github.com/elastisys/ck8s-ops/issues/1191. so closing it
