### ISSUE TITLE
[3] Investigation: Create container vulnerability dashboard

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#222]
Once we are done with #182 , it would be great to have a Grafana dashboard that shows some information about the vulnerability posture of the cluster. Potential questions to answer:

* How many vulnerable images am I running? Which ones are these?
* What Pods are running vulnerable images?
* What is the severity of those vulnerabilities?

**Implementation hint**: Maybe use [Starboard](https://github.com/aquasecurity/starboard) and export some metrics with Prometheus's pushgateway.

**Definition of done:**

* We see a screenshot of a Grafana dashboard illustrating the position of vulnerable images in the cluster.
* We know what steps are required to complete this task.

**Comment by cristiklein** [comment]
Potential alternative to Starboard: https://engine.anchore.io/docs/

**Comment by viktor-f** [comment]
Did a test of `starboard` yesterday. It was rather easy to setup (though there are probably things to tweak) and easy to make it automatically scan every image in the cluster.
The problem is that it does not expose any prometheus metrics regarding the results of the scans. So to make it work for us we would need to check if the maintainers could add those metrics or add them ourselves (either in startboard or some external exporter).

**Comment by cristiklein** [comment]
Nice! We could write a small script that runs as a CronJob and push to [PushGateway](https://github.com/prometheus/pushgateway/blob/master/README.md).

```
cat <<EOF | curl --data-binary @- http://pushgateway.example.org:9091/metrics/job/some_job/instance/some_instance
# TYPE some_metric counter
some_metric{label="val1"} 42
# TYPE another_metric gauge
# HELP another_metric Just an example.
another_metric 2398.283
EOF
```

If these is still time in this issue, please explore this, since we might want to use this technique when converting daily tasks into dashboards.

**Comment by viktor-f** [comment]
Results from the investigation can be found here: https://github.com/elastisys/compliantkubernetes-apps/tree/vf/vulnerability-scan-investigation/vulnerability-dashboard

Image from prototype dashboard:
![vulnerability-dashboard](https://user-images.githubusercontent.com/58632240/116230739-4f0aca80-a758-11eb-8b6c-1be8eb399180.png)
