### ISSUE TITLE
[3] Investigate and Fix Issue with Old Image Remaining in Trivy Panel

### ISSUE THREAD

**Issue by raviranjanelastisys** [elastisys/compliantkubernetes-apps#2226]
### Description

We have encountered an issues where the vulnerability report for an old images are not deleted when the image was updated in Grafana's Trivy panel. Despite updating to the new image, the old vulnerability report persisted, causing the dashboard to display outdated information.

I have manually removed the old vulnerability reports as a temporary fix, and the dashboard no longer shows the old image. However, we need to investigate the root cause to prevent this issue from occurring in the future.

- Investigate the root cause of why the old vulnerability report was not deleted.
- Implement a permanent fix to ensure old vulnerability reports are automatically deleted when images are updated.
- Roll out the fix in future application releases.

### Additional context

This issue can cause confusion and may lead to incorrect assessment of the current security posture due to outdated vulnerability reports.

### Definition of done

A permanent fix will be rolled out based on the findings of the investigation.

**Comment by viktor-f** [comment]
If it is not possible to make trivy remove old vulnerability reports as fast as we want, then maybe we can update the grafana dashboards to exclude the old reports. But I would prefer that trivy just deleted the old reports.

**Comment by OlleLarsson** [comment]
@robinelastisys didn't find any issues, nor did @Ajarmar in the long-running env. Closing for now, might reopen if found as an issue again.
