### ISSUE TITLE
[1] Investigate: Unify user- and ops- Grafana/Kibana dashboards

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#223]
**Is your feature request related to a problem? Please describe.**

We currently export two dashboards:

* A "user" dashboard under `grafana.$DOMAIN`
* An "ops" dashboard under `grafana.ops.$DOMAIN`

One of them has OpenID integration, the other not. Otherwise they seem pretty much identical.

**Describe the solution you'd like**

I would like to better understand the reason why we have two dashboards. Then I would like to look for way to unite the two.

**Definition of done:**

* We know what are the use-cases for two dashboards.
* We have a solution for supporting those use-cases with a single dashboard.
* We have a clear list of steps to unifying the two dashboards or, if really not feasible, we know why we need two dashboards.

**Comment by pettersv** [comment]
Investigate if it is possible to "Hide" ops dashboards from users using one grafana instance and OIDC groups?

**Comment by tordsson** [comment]
Elastisys ops (of managed service) prefers to keep some internal dashboards

**Comment by crssnd** [comment]
I want to have a discussion with @Xartos to understand better some dex integration aspects.

**Comment by cristiklein** [comment]
We have decided to keep user- and ops- Grafana dashboards separated. We do this to protect ops dashboards from accidental user editing, which would be more difficult if we had to rely on Grafana's access control.

However, for the sake of transparency towards our users, the user Grafana will be configured (and updated) with the same dashboards as the ops one.
