### ISSUE TITLE
[1] SC log retention uses wrong service account

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#224]
**Describe the bug**

The sc log retention cronJob tries to use a service account that does not exist
```
Warning  FailedCreate  5m10s (x9 over 27m)     job-controller  Error creating: pods "sc-logs-retention-1612396800-" is forbidden: error looking up service
 account fluentd/fluentd-aggregator: serviceaccount "fluentd-aggregator" not found
 ```

**To Reproduce**
1. Deploy a cluster
2. Wait for sc log retention to run or start a manual job from the cronJob
3. Check the status of the job, it should say that it failed with a similar error to the error above.

**Expected behavior**
The job should be able to create the pod and use a service account that exists.

To fix it we need to change this line: https://github.com/elastisys/compliantkubernetes-apps/blob/ee8e5c0dc226df4008e079803df58d599ce84898/helmfile/charts/sc-logs-retention/values.yaml#L13
The two service accounts available are `default` and `fluentd-forwarder`

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.9.0 and `main` as of writing this issue.

**Additional context**

**Comment by Xartos** [comment]
Changing this to `fluentd-forwarder` works as a workaround for already running clusters. But I guess the question could be if we would like to have a separate service account for this or if we want to reuse existing ones.
