### ISSUE TITLE
[5] Run on top of EKS-D

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#225]
**Is your feature request related to a problem? Please describe.**

There seems to be a use-case for running Compliant Kubernetes on top of [EKS-D](https://distro.eks.amazonaws.com/users/install/kops/), which is kops based.

**Describe the solution you'd like**

1. Follow EKS-D instructions.
2. `./bin/ck8s init`
3. `./bin/ck8s apply`

Futhermore,:

* Documentation should clarify AWS pre-requisites in terms of permissions and resource usage, and/or pre-checks.
* Integration should leverage Route53 (and potentially) NLB and ACM for easy-of-use.

**Definition of done:**

* Documentation on compliantkubernetes.io shows how to run Compliant Kubernetes on top of EKS-D.

**Comment by tordsson** [comment]
See if https://github.com/elastisys/tutorials-and-blogposts/issues/4 is still relevant before closing this.
