### ISSUE TITLE
[3] Velero fails to restore subnamespace

### ISSUE THREAD

**Issue by simonklb** [elastisys/compliantkubernetes-apps#2321]
### Experienced behaviour

When restoring a subnamespace Velero fails with:
```
Errors:
  Velero:   error creating namespace velero-test: admission webhook "namespaces.hnc.x-k8s.io" denied the request: namespaces "velero-test" is forbidden: cannot set or modify tree label "production.tree.hnc.x-k8s.io/depth" in namespace "velero-test"; these can only be managed by HNC
```

See: https://github.com/elastisys/compliantkubernetes-apps/pull/2269#discussion_r1761356767

### Expected behaviour

Restoring Velero backups that include subnamespaces should succeed.

### Steps to reproduce

cd tests
make run-end-to-end/velero

### Compliant Kubernetes Apps Version

v0.40.0

**Comment by Ajarmar** [comment]
@elastisys/goto-security Is this issue something that we can fix or is it a bug in Velero? See the discussion in the linked comment in the issue.

**Comment by OlleLarsson** [comment]
close @lunkan93 ?
