### ISSUE TITLE
[3] Support group claims for google in dex

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#233]
**Is your feature request related to a problem? Please describe.**

AFAIK we do not support group claims for google in dex

**Describe the solution you'd like**

I would like to have group claims in dex. I think the problem is that we use the `type: oidc` for the connector instead of `type: goolge` here: https://github.com/elastisys/compliantkubernetes-apps/blob/c980f6c2e8825d0563fc92da2f79b2a32eb6d924/helmfile/values/dex.yaml.gotmpl#L28
If we switch the type and add some more config I think we can get it to work. See this documentation: https://dexidp.io/docs/connectors/google/

**Describe alternatives you've considered**

The only other solution I see is to not support group claims until (if ever) google/dex makes changes to support it even while using `type: oidc`.

**Additional context**

**Definition of done:**
When could this feature be considered done.

This is done when I can setup a cluster with google as my IDP and get group claims that then work with kubernetes/grafana/...

**Comment by vanneback** [comment]
We also need to:
* add a secret with the service account created like this https://github.com/elastisys/dex-with-google-accounts/blob/main/google-sa-secret.yml.
* Create the service account in google (add docs about this)
* Add sure the following attributes to kubespray: 
```
kube_oidc_username_claim: "email"
kube_oidc_groups_claim: "groups"
```

See the blogpost soon released https://github.com/elastisys/tutorials-and-blogposts/pull/20
and the example repo https://github.com/elastisys/dex-with-google-accounts for more info.

**Comment by llarsson** [comment]
It seems to me that @vanneback has done all the background reading already and would have a very easy time in adding this support. I am claiming this one for CNOSA and assigning @vanneback :)

**Comment by llarsson** [comment]
To my understanding, this is solved in https://elastisys.com/elastisys-engineering-how-to-use-dex-with-google-accounts-to-manage-access-in-kubernetes/

@Pavan-Gunda , you got groups working for this, right?

**Comment by Pavan-Gunda** [comment]
yes

**Comment by Pavan-Gunda** [comment]
if we add the config and secrets as @vanneback mentioned [here](https://github.com/elastisys/compliantkubernetes-apps/issues/233#issuecomment-802672467). we should be able to have dex working with google groups
