### ISSUE TITLE
Make config validation smarter

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#24]
The current [validation](https://github.com/elastisys/compliantkubernetes-apps/blob/main/bin/common.bash#L116) requires _all_ configration parameters to be present in the configuration file.
Consider the scenario where a user has set `opa.enabled: false`, `harbor.enabled: false`, our current implementation still requires all available variables for harbor and opa to be in the users configuration file.

I would suggest that the validation is made smarter, whereby it skips additional checks if enabled flags for applications are set to false.

**Comment by crssnd** [comment]
With the introduction of default config and common config, it feels like this issue is done. Though not everything mentioned here is solved. Please open a new issue if you feel like something important still needs to be done.
