### ISSUE TITLE
[5] Spike: Show us how to customize Prometheus alerts and Grafana dashboards using Jsonnet

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#242]
**Context**

As part of the discussion on how to customize Prometheus alerts and Grafana dashboards, we stumbled across this [community proposal](https://docs.google.com/document/d/12CThd7eGiJHXd7oe7LPNBjw5Lv0fv-NkgVvW_2WGzAM/edit?usp=sharing). This seems to be [already implemented](https://github.com/prometheus-operator/kube-prometheus/blob/master/docs/developing-prometheus-rules-and-grafana-dashboards.md). The tech stack is based on [jsonnet](https://jsonnet.org/).

**What should be investigated.**

1. Focus on the service cluster (re-use our existing workload cluster setup). Do allow yourself to change the Prometheus remote writer on the workload cluster if it simplifies the investigation.
2. Disable alerts and dashboards in `compliantkubernetes-apps`. In particular, keep cert-manager and ingress-nginx. (Harbor, Elasticsearch and Kibana can be thrown out too, if it simplifies the investigation.)
3. Show us how to set up Prometheus/Grafana with the setup suggested upstream.
4. Show us what this setup includes by default.
5. Show us how to customize this setup, by adding an alert and a dashboard.

**What artifacts should this produce.**

1. Produce something you can demo in front of the whole team during a 50-minutes time-slot, including questions.
2. Produce a tutorial on how to do steps 3-5. (Markdown with copy-paste-able code in the tutorials repo.)
3. Produce a short video (screencast with voice-over) showing 3-5.

**Comment by cristiklein** [comment]
Might be relevant for the investigation:
- https://github.com/bitnami/kube-prod-runtime/blob/master/manifests/components/prometheus.jsonnet
- https://github.com/bitnami-labs/kubernetes-grafana-dashboards

**Comment by lentzi90** [comment]
See the blog post merged here: https://github.com/elastisys/tutorials-and-blogposts/pull/26
