### ISSUE TITLE
[1] Remove metrics from fluentd

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#246]
**Is your feature request related to a problem? Please describe.**
We export metrics from fluentd in our workload clusters. They can grow to a very high cardinality because there are a few metrics for each container in the cluster. With a low/normal amount of containers this should not be a problem. But there is an issue with the exporter that it does not stop sharing metrics that are no longer relevant (e.g. metrics for a container in a pod that has been deleted), see https://github.com/fluent/fluent-plugin-prometheus/issues/20. Combine this with conjobs that run often and you get a lot of metrics, e.g. in a cluster that ran a job every 5 minutes the metrics had grown to ~24000 timeseries.

Also note that we right now do not use these metrics in any way, e.g. we do not have any dashboards that use them.

**Describe the solution you'd like**
I suggest that we disable the metrics from fluentd entierly. It's the easiest solution and since we don't really use the metrics today there isn't a large impact.
The relevant config is here: https://github.com/elastisys/compliantkubernetes-apps/blob/64ee6ef2850d4a7107332b51ae4f06cf430c662a/helmfile/values/fluentd-wc.yaml.gotmpl#L35-L38
and here: https://github.com/elastisys/compliantkubernetes-apps/blob/64ee6ef2850d4a7107332b51ae4f06cf430c662a/helmfile/values/fluentd-user.yaml.gotmpl#L32-L35

**Describe alternatives you've considered**
We could try to filter which metrics we gather from fluentd.
Alternatively we could try to control which containers we monitor.

**Additional context**
![fluentd-metrics](https://user-images.githubusercontent.com/58632240/108212341-09b19780-712e-11eb-9f4d-29d544061158.png)

**Definition of done:**
This task is done when the amount of metrics from fluentd has been reduced drastically or when they have been removed entierly.

**Comment by OlleLarsson** [comment]
This is high prio!
