### ISSUE TITLE
Add support for Azure block storage

### ISSUE THREAD

**Issue by vanneback** [elastisys/compliantkubernetes-apps#247]
**Is your feature request related to a problem? Please describe.**
To fully support Azure we need to add a storage class which supports azure storage.

**Describe the solution you'd like**
Azure storage should be implemented as a storageclass in the bootstrap directory.

**Definition of done:**
The option of choosing azure storage is available in the config.
The azure storageclass is available in the bootstrap.

**Comment by tordsson** [comment]
Storage class as part of cluster or apps?

**Comment by OlleLarsson** [comment]
Is this something that we want to support?

**Comment by OlleLarsson** [comment]
Dropping azure support
