### ISSUE TITLE
Add azure as an option in the init command

### ISSUE THREAD

**Issue by vanneback** [elastisys/compliantkubernetes-apps#248]
**Is your feature request related to a problem? Please describe.**
To support Azure it should be an option in the init command.

**Describe the solution you'd like**
Azure should be added as an option when running `ck8s init`. This should set sane defaults for azure in the config files created.
This includes Ingress service of type LoadBalancer, azure object storage, azure storageclass.

**Additional context**
Related #247, Related #132 

**Definition of done:**
Azure is a supported option in `ck8s init` and it sets sane defaults for a basic Azure installation.

**Comment by vanneback** [comment]
Another decent solution is to not use azure object storage but use rook instead. Still the init command is needed but only changing the defaults of storageclass to rook.

**Comment by Xartos** [comment]
I think this might be a bit too big for one task. It could be split into one task for each integration (LB, object storage, csi).

**Comment by vanneback** [comment]
Yes the related issues is adding the storage provider and object storage. This task is just to add the init option with sane defaults. The LB will work by default if the ingress service is set to LoadBalancer, provided that the cluster is set up correctly.

**Comment by OlleLarsson** [comment]
Dropping azure support
