### ISSUE TITLE
SC log only removes files and not the buckets

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#252]
**Describe the bug**
After the cron job of sc-log-retention has completed, the buckets will still exist (Although without files).

**To Reproduce**

1. Wait until you have enough logs for the log retention to start do remove buckets
1. Let the retention job complete
1. Inspect the storage, and you'll see that the bucket still exists

**Expected behavior**
Expected the buckets older than the retention date to be removed

**Probable cause**
When the retention job is suppose to deletes the bucket, it only cleans the files since it uses `aws s3 rm`, [_see here_](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/sc-logs-retention/scripts/logs-retention.sh#L52), while it should use `aws s3 rb`, _see [this](https://docs.aws.amazon.com/cli/latest/reference/s3/index.html#single-local-file-and-s3-object-operations) and [this](https://docs.aws.amazon.com/cli/latest/reference/s3/index.html#directory-and-s3-prefix-operations)_

Alternatively we can change this to use `s3cmd` which will work using `s3cmd rm --recursive`

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.9.0

**Additional context**

**Comment by OlleLarsson** [comment]
What do you mean, why should the bucket be removed?

**Comment by Xartos** [comment]
> What do you mean, why should the bucket be removed?
> Do you mean that prefixes are still left?
> 
> ```
> ❯ s3cmd -c ~/.s3cfg-exo.ini ls s3://olle-dev-sc-logs/logs/
>                        DIR   s3://olle-dev-sc-logs/logs/20210211/
>                        DIR   s3://olle-dev-sc-logs/logs/20201209/
> ```

It's me that's having a brain fart.
It's exactly that. But I think that it might be that fluentd just has more data in its buffer than we have retention. So it backs it up to s3 after it's deleted. And this is no issue, the retention script will just remove it the next time it runs so this is no bug.
