### ISSUE TITLE
Multi tenancy alerts for API server down

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#253]
**Describe the bug**
In an environment with multiple workload clusters, we currently configure DNS to point to the SC only, as per https://github.com/elastisys/compliantkubernetes-apps/issues/126. This means that the blackbox exporter that is supposed to reach the workload API server to check its health fails, since the DNS points to SC and SC doesn't expose the health endpoint in this way.

The blackbox exporter is configured [here](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/blackbox.yaml.gotmpl#L49). Note that it targets `.Values.global.baseDomain`, which normally would point to the WC. (Only specific subdomains would point to SC for things like Kibana.)

**To Reproduce**
1. Initialize an environment with multiple workload clusters.
2. Deploy SC and optionally some WCs
3. Go to Grafana and check the uptime dashboard.
4. See that the user API server is reported to be down. If you check the blackbox exporter, you will notice that it is using the base domain that points to SC.

**Expected behavior**
The uptime dashboard should show the status of all WC API servers correctly.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.9.0

**Additional context**

The WC API server health endpoint is exposed using [this chart](https://github.com/elastisys/compliantkubernetes-apps/tree/main/helmfile/charts/kubeapi-metrics) in the helmfile [here](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/01-applications.yaml#L559). This is because the API server doesn't respond to external health checks so we go through a basic auth protected ingress to get the status from inside the cluster instead.

**Comment by viktor-f** [comment]
This seems like a duplicate of https://github.com/elastisys/compliantkubernetes-apps/issues/207. They are at least very related.

**Comment by lentzi90** [comment]
Ah did not see that one. Thanks @viktor-f I'll close this as a duplicate then. :slightly_smiling_face:
