### ISSUE TITLE
Upgrade to opendistro 1.13

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#258]
[od 1.13](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/v1.13.0/release-notes/opendistro-for-elasticsearch-release-notes-1.13.0.md) has been released. Now based on es/kibana 7.10.2.

Procedure:
- Check release notes
- Update our fork
- Test
- Build new chart and push to our chart repository
- Update helm chart version in applications.yaml

**Note** that this release contains breaking changes affecting us as it is not longer possible to specify ISM policy id in index templates.
- https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/v1.13.0/release-notes/opendistro-for-elasticsearch-release-notes-1.13.0.md#index-management
- https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/v1.13.0/release-notes/opendistro-for-elasticsearch-release-notes-1.13.0.md#index-management-1
 
This means that we need to change our [default ISM policies and index templates](https://github.com/elastisys/opendistro-build/tree/main/helm/opendistro-es/files/configurer) accordingly to this change. This change will have to be noted clearly in our release notes.

**Comment by tordsson** [comment]
deprecated by #588.
