### ISSUE TITLE
Upgrade cert-manager to 1.4

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#273]
**Is your feature request related to a problem?**
v1.2 of cert-manager has been released.
https://github.com/jetstack/cert-manager/releases/tag/v1.2.0

**Describe the solution you'd like**
That we'd upgrade to this version to get the latest of features.

**Describe alternatives you've considered**
None.

**Additional context**

**Definition of done:**
- Cert-manager helm chart upgraded to version that's running 1.12 by default.
- Our cert-manager resources upgraded to adhere to any api changes in the new version.

**Comment by lentzi90** [comment]
Bump to v1.3

**Comment by Xartos** [comment]
Bump to v1.4

[CHANGELOG](https://github.com/jetstack/cert-manager/releases/tag/v1.4.0)
This release includes `RunAsNonRoot` which we should strive to use for all deployments.
