### ISSUE TITLE
Can we replace deprecated dex helm chart with the official one

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#274]
**What should be investigated.**
Can we replace [stable/dex](https://github.com/helm/charts/tree/master/stable/dex) be replaces with [dex/dex](https://github.com/dexidp/helm-charts/tree/master/charts/dex)?

**What artifacts should this produce.**
- Either a new issue replacing the helm chart
- or a document with fixes that are needed so that @cristiklein can decide wheather or not we should contribute them or just wait for 'em to be fixed.

**Comment by sagikazarmark** [comment]
FYI we've created a new (official) chart that uses an untagged version of Dex: https://github.com/dexidp/helm-charts/tree/master/charts/dex

We should be able to reach 0.1.0 in the coming weeks which is going to be considered the first stable(ish) version. Until then, feedback is welcome.
