### ISSUE TITLE
[3] Use external-dns to automate DNS setup steps

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#280]
**What should be investigated.**

Can we / should we use [external-dns](https://github.com/kubernetes-sigs/external-dns) to simplify DNS setup?

**What artifacts should this produce.**

A demo showing us how external-dns would look like on a few cloud providers, e.g., Exoscale, SafeSpring, OVH.

**Comment by tordsson** [comment]
Aim to make external-dns optional
