### ISSUE TITLE
[1] Use emptyDir when Prometheus is used as a metrics forwarder

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#285]
**Is your feature request related to a problem? Please describe.**

Please see [ADR-0007](https://compliantkubernetes.io/adr/0007-make-monitoring-forwarders-storage-independent/) for full discussion.

**Describe the solution you'd like**

Change the default Prometheus setup on the workload cluster, so it does not depend on the underlying storage provider.

**Definition of done:**

* Prometheus no longer needs a PVC.

**Comment by cristiklein** [comment]
@jakubkrzywda Since it affects your current project, would you have bandwidth to pick this up?

**Comment by jakubkrzywda** [comment]
> @jakubkrzywda Since it affects your current project, would you have bandwidth to pick this up?

Seems like a good fit, but it might take a couple of weeks until I will work on it.
