### ISSUE TITLE
Document current state of access control

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#299]
**Is your feature request related to a problem? Please describe.**

We now have a solid story when it comes to CISO dashboards. We need something similar for access control.

**Describe the solution you'd like**

Documentation (including screenshots and non-edited screencasts) that show:

- [ ] What is access control? Why is it important? How does it fit with regulatory requirements?
- [ ] How is access control performed with the Kubernetes API? What is the user's experience, what is the operator's experience?
- [ ] How is access control performed with Harbor?
- [ ] How is access control performed with Grafana?
- [ ] How is access control performed with Kibana?

**Definition of done:**

* Documentation on compliantkubernetes.io to fulfill the access control story from a CISO's PoV.
* Screenshots and non-edited screencasts (please use full-screen terminal and browser, with either 4K or FullHD).

**Comment by tordsson** [comment]
Capture differences between in-service configuration (Harbor does the exact mapping, using an admin role in Harbor) and from-kubernetes configuration (as done in Kibana).

**Comment by tordsson** [comment]
Document current state (incl. any limitations) and create separate issues to document specifics for individual services, including screen casts (use full screen with 4k or FHD resolution).

**Comment by cristiklein** [comment]
As discussed during our arch meeting 2021-03-12, I wanted to note that this task is on the critical path to using OpenID everywhere and reducing secrets.

**Comment by cristiklein** [comment]
80% solved by: https://compliantkubernetes.io/operator-manual/access-control/

https://github.com/elastisys/compliantkubernetes/pull/126

I recommend closing this issue and re-opening a new one later, if we are still not satisfied with the story.
