### ISSUE TITLE
[3] Investigation: Deprecation awareness dashboard

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#303]
**Is your feature request related to a problem? Please describe.**

It is difficult for users to realize when they use deprecated APIs. Educating them would allow operators to move to new versions of Kubernetes without anxiety to break anything.

**Describe the solution you'd like**

Expose [`apiserver_requested_deprecated_apis`](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/metrics/metrics.go#L68) or some [OPA-based magic](https://opensource.com/article/20/3/deprek8) in a Grafana Dashboard.

**Definition of done:**

* Screenshots with what could be obtained if low-hanging fruits are explored.

**Comment by tordsson** [comment]
This seems like a very useful tool that digs a bit deeper on the topic: https://github.com/FairwindsOps/pluto

**Comment by OlleLarsson** [comment]
Exposing `apiserver_requested_deprecated_apis ` probably isn't too helpful.
![image](https://user-images.githubusercontent.com/12396964/112951085-47490d80-913b-11eb-82b9-35fba89b37df.png)

**Comment by cristiklein** [comment]
@OlleLarsson Please clarify. Isn't the screenshot you attached showing the deprecated APIs that are currently in use? Are there any counts associated with them?

**Comment by OlleLarsson** [comment]
Regarding counts, not that i can see.
![image](https://user-images.githubusercontent.com/12396964/112952495-d7d41d80-913c-11eb-83b2-00f0d753eb48.png)
It only shows ingresses once, but there are three ingress reources in my cluster
```bash
❯ pluto detect-helm -owide
NAME                                         NAMESPACE        KIND      VERSION              REPLACEMENT            DEPRECATED   DEPRECATED IN   REMOVED   REMOVED IN  
dex/dex                                      dex              Ingress   extensions/v1beta1   networking.k8s.io/v1   true         v1.14.0         false     v1.22.0     
opendistro-es/opendistro-es-client-service   elastic-system   Ingress   extensions/v1beta1   networking.k8s.io/v1   true         v1.14.0         false     v1.22.0     
opendistro-es/opendistro-es-kibana-ing       elastic-system   Ingress   extensions/v1beta1   networking.k8s.io/v1   true         v1.14.0         false     v1.22.0     
```

My thinking that it is not useful for a user is that it does not show name of the deprecated objects.

I'm looking into Pluto that Johan mentioned, and If I were a user I would probably just run that application once or twice every now and then to check my local kubernetes yaml manifests and helm charts.

**Comment by OlleLarsson** [comment]
Just tested Pluto a bit quickly in the repo and against the service cluster.
Seems useful but it's not really useful for creating an "awareness" dashboard.

```bash
❯ pluto detect-files .
NAME                                                KIND                       VERSION                        REPLACEMENT               REMOVED   DEPRECATED  
authcodes.dex.coreos.com                            CustomResourceDefinition   apiextensions.k8s.io/v1beta1   apiextensions.k8s.io/v1   false     true        
authrequests.dex.coreos.com                         CustomResourceDefinition   apiextensions.k8s.io/v1beta1   apiextensions.k8s.io/v1   false     true
...

❯ pluto detect-helm -owide
NAME                                         NAMESPACE        KIND      VERSION              REPLACEMENT            DEPRECATED   DEPRECATED IN   REMOVED   REMOVED IN  
dex/dex                                      dex              Ingress   extensions/v1beta1   networking.k8s.io/v1   true         v1.14.0         false     v1.22.0     
opendistro-es/opendistro-es-client-service   elastic-system   Ingress   extensions/v1beta1   networking.k8s.io/v1   true         v1.14.0         false     v1.22.0     
opendistro-es/opendistro-es-kibana-ing       elastic-system   Ingress   extensions/v1beta1   networking.k8s.io/v1   true         v1.14.0         false     v1.22.0     

❯ CK8S_AUTO_APPROVE=true ./bin/ck8s ops helmfile sc template --skip-deps | pluto detect - -owide
...
NAME                           NAMESPACE   KIND      VERSION              REPLACEMENT            DEPRECATED   DEPRECATED IN   REMOVED   REMOVED IN  
dex                            <UNKNOWN>   Ingress   extensions/v1beta1   networking.k8s.io/v1   true         v1.14.0         false     v1.22.0     
opendistro-es-client-service   <UNKNOWN>   Ingress   extensions/v1beta1   networking.k8s.io/v1   true         v1.14.0         false     v1.22.0     
opendistro-es-kibana-ing       <UNKNOWN>   Ingress   extensions/v1beta1   networking.k8s.io/v1   true         v1.14.0         false     v1.22.0
```

**Comment by OlleLarsson** [comment]
Okay, so to sum up I'd say that in terms of creating a deprecation awareness dashboard in Grafana our only real option is to use the suggested apiserver metric that was introduced  in k8s 1.19. Alongside that table it is also possible to get the number requests sent to each endpoint by also letting prometheus capture `apiserver_request_total`, that would however would introduce a lot of timeseries
```bash
❯ kubectl get --raw /metrics | prom2json | jq '.[] | select(.name=="apiserver_request_total").metrics' | jq length
894
```
As I've mentioned it is not possible to see the actual offending objects in kubernetes and therefore it's not possible for a user to say that it is him/her who's resposible for using the deprecated apis.

Regaring OPA I don't see any value in it over the warning that [kubectl](https://kubernetes.io/blog/2020/09/03/warnings/) gives when accessing deprecated apis. 
```bash
❯ kubectl apply -f old-ingress.yaml 
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
ingress.extensions/kubecost-ingress created
```

When not nessecarily thinking about dashboards, Pluto could be a tool that we might recommend users to use to check their manifests and or helm charts.

**Comment by tordsson** [comment]
Here is an attempt to use OPA (well rego at least) for the purpose: https://github.com/swade1987/deprek8ion
along with link to a similarly scoped project: https://github.com/doitintl/kube-no-trouble

k8s deprecation detection seems to be a busy space...

**Comment by OlleLarsson** [comment]
> If there is more time for this issue, can you investigate if OPA/Gatekeeper could be used to detect deprecated APIs (i.e., via dryrun constraints)? Would they offer at least the granularity of apiserver_requested_deprecated_apis, i.e., namespace and cluster name? I see great potential in this approach also for future ideas that I heard.

Yes, there's more time left for this investigation, i'll look into it.

**Comment by OlleLarsson** [comment]
So, this moring I tried adding a rego template and gatekeeper constraints for deprecated Ingress APIs and No it does not work as you expect. You can checkout what I deployed [here](https://github.com/elastisys/compliantkubernetes-apps/compare/ol/test-gatekeeper-deprek8?expand=1).

In my cluster i have the following ingresses
```
ingress-srv      <-- networking.k8s.io/v1
kubecost-ingress <-- extensions/v1bet1
kubeapi-metrics  <-- Don't know

When looking at the violations from the constraints this is what's shown
```bash
❯ kubectl get testpolicy.constraints.gatekeeper.sh -A -oyaml
...
    violations:
    - enforcementAction: dryrun
      kind: Ingress
      message: 'Ingress/ingress-srv: API extensions/v1beta1 for Ingress is deprecated,
        use networking.k8s.io/v1beta1 instead.'
      name: ingress-srv
      namespace: default
    - enforcementAction: dryrun
      kind: Ingress
      message: 'Ingress/kubecost-ingress: API extensions/v1beta1 for Ingress is deprecated,
        use networking.k8s.io/v1beta1 instead.'
      name: kubecost-ingress
      namespace: default
    - enforcementAction: dryrun
      kind: Ingress
      message: 'Ingress/kubeapi-metrics: API extensions/v1beta1 for Ingress is deprecated,
        use networking.k8s.io/v1beta1 instead.'
      name: kubeapi-metrics
      namespace: kube-system
```

The expected outcome should of course not include the `ingress-srv` as it does not use any deprecated apis.

I have not looked into the details of the gatekeeper dry-run feature so I don't know what APIs it uses (maybe it cycles version?).

**Comment by cristiklein** [comment]
I'm definitely not an expert in rego or OPA, but your policies look "different" than what I expected: https://github.com/naquada/deprek8/blob/master/policy/deprek8.rego

For example, those examples use `input.apiVersion` instead of `input.review.object.apiVersion`. Also, there is some special handing for lists.

Like I said, I have insufficient expertise in rego or how the webhook is presented to it, but I can't help wonder if some of these differences could be the culprit.

**Comment by OlleLarsson** [comment]
> I'm definitely not an expert in rego or OPA, but your policies look "different" than what I expected: https://github.com/naquada/deprek8/blob/master/policy/deprek8.rego
> 
> For example, those examples use `input.apiVersion` instead of `input.review.object.apiVersion`. Also, there is some special handing for lists.
> 
> Like I said, I have insufficient expertise in rego or how the webhook is presented to it, but I can't help wonder if some of these differences could be the culprit.

For plain OPA you should use `input.whatever`, but for gatekeeper it is `input.review.object.whatever`.
You can checkout [our policies](https://github.com/elastisys/compliantkubernetes-apps/tree/main/helmfile/charts/gatekeeper-templates/policies) and [gatekeeper policy library](https://github.com/open-policy-agent/gatekeeper-library/tree/master/library) to see that's true.

**Comment by cristiklein** [comment]
Thanks for the clarification! I'll see if I can try your code out.

**Comment by viktor-f** [comment]
I quickly looked at https://github.com/doitintl/kube-no-trouble , which was linked above. There they also seem to indicate that you cannot really get this from the apiserver. But the approach of looking at `last-applied-configuration` annotation or helm information could be a way forward for us.

> This tool will be able to detect deprecated APIs depending on how you deploy your resources, as we need the original manifest to be stored somewhere. In particular following tools are supported:
    file - local manifests in YAML or JSON
    kubectl - uses the kubectl.kubernetes.io/last-applied-configuration annotation
    Helm v2 - uses Tiller manifests stored in K8s Secrets or ConfigMaps
    Helm v3 - uses Helm manifests stored as Secrets or ConfigMaps directly in individual namespaces
