### ISSUE TITLE
Devise a plan for upstreaming to OpenDistro

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#305]
**What should be investigated.**

Currently we maintain our own [fork of OpenDistro](https://github.com/elastisys/opendistro-build). This means reduced visibility, increased maintenance burden on our side and less sticking to upstream, as we promise our users.

Let us devise a clear plan on what can be upstreamed and what we should maintain ourselves. If we decide to keep things for ourselves, please come up with a solution to reduce maintenance burden. For example, we might be better off with an [Umbrella Charts](https://helm.sh/docs/howto/charts_tips_and_tricks/) instead of a full fork.

Please look at:
* The current features of OpenDistro
* The [roadmap of OpenDistro](https://github.com/elastisys/opendistro-build)
* Our current requirements on OpenDistro
* Our own fork of OpenDistro

Also, please engage with the OpenDistro community.

**What artifacts should this produce.**

* A set of Compliant Kubernetes requirements on OpenDistro
* A mapping between said requirements and the current feature of OpenDistro
* A mapping between said requirements and features on the roadmap of OpenDistro
* Identified gaps, i.e., requirements not satisfied by current or predicted features, and whether the OpenDistro community is interested in them.
* A plan on supporting the non-community gaps.

**Comment by cristiklein** [comment]
Some security configs are not properly reloaded and need manual action (https://github.com/elastisys/compliantkubernetes/pull/98). Would be great if upstreaming helped fix that.

**Comment by OlleLarsson** [comment]
> Some security configs are not properly reloaded and need manual action ([elastisys/compliantkubernetes#98](https://github.com/elastisys/compliantkubernetes/pull/98)). Would be great if upstreaming helped fix that.

Manual intervention can be circumvented by the solution that I propse [here].(https://github.com/elastisys/ck8s-apps/issues/51#issuecomment-735653101)
Perhaps such a solution can be upstreamed to the helm chart.

Getting rid of securityadmin for reloading configuration is probably no easy task ;)
Here's the invoking [shell script](https://github.com/opendistro-for-elasticsearch/security/blob/main/tools/securityadmin.sh) and the [java code](https://github.com/opendistro-for-elasticsearch/security/blob/main/src/main/java/com/amazon/opendistroforelasticsearch/security/tools/OpenDistroSecurityAdmin.java).

**Comment by tordsson** [comment]
Postpone until an OpenSearch chart is available

**Comment by tordsson** [comment]
Deprecated by #588
