### ISSUE TITLE
Workload cluster Issuer for user alertmanager and kubeapi-metrics

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#311]
**Is your feature request related to a problem? Please describe.**
We don't have a way of choosing between Issuer/ClusterIssuer for [user-alertmanager](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/examples/user-alertmanager/templates/ingress.yaml#L6) or [kubeapi-metrics](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/kubeapi-metrics.yaml.gotmpl). It would be nice to be able to use Issuers in WC since users cannot abuse them, whereas they can use any ClusterIssuers in the cluster.

**Describe the solution you'd like**
To make the configuration more flexible, allow specifying `extraAnnotations` instead of just the Issuer/ClusterIssuer for both these charts. I would also suggest changing the default values for WC so that an Issuer is created for kubeapi-metrics. For user-alertmanager I think it is better to not create it unless the user asks for it.

**Describe alternatives you've considered**
- We could add an option for "issuer type", but this feels more brittle and complex than just taking in the whole annotation.

**Additional context**

**Definition of done:**
It is possible to choose between using an Issuer or ClusterIssuer with kubeapi-metrics and/or user-alertmanager.

**Comment by tordsson** [comment]
Direction for this pending completion of: https://github.com/elastisys/compliantkubernetes-apps/issues/242

**Comment by OlleLarsson** [comment]
Alertmanager should no longer be exposed via ingress.
