### ISSUE TITLE
Rework version validation

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#32]
`./bin/ck8s` performs version validation as follows:

1. It retrieves the script's version by performing `git describe --tags --abbrev=0 HEAD | sed 's/^v//'`
2. It retrieves the configuration version by looking at `global.ck8sVersion`
3. It mandates that the two be equal.

This is problematic for two reasons:
1. `compliantkubernetes-apps` might be checked out shallow or might be included as a submodule, hence its own version may be unreliable.
2. Version mismatch should be allowed according to Semantic Versioning rules.

**Comment by lentzi90** [comment]
I think this is a duplicate of #10 or at least very much related.

**Comment by cristiklein** [comment]
Agreed. I'm closing this one.
