### ISSUE TITLE
Add S3 bucket management

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#321]
**Is your feature request related to a problem?**
We should move S3 bucket management back to this repositoy.

**Describe the solution you'd like**
Move the S3 manager from our private repo `bucket-manager` to this repo.
Functionality wise nothing needs to be changed (I think), we need to update the README with new instuction on how to create and remove buckets.
The script(s) should be put under `scripts/`, it is probably not nessecary to make the creation and deletetion of buckets into a sub-command of `bin/ck8s`.

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
S3 buckets are managed from within this repository.

**Comment by lentzi90** [comment]
Please remember to update the pipeline also! :slightly_smiling_face:
