### ISSUE TITLE
[1] Logs from FluentD are being shipped to S3

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#332]
**Describe the bug**
Fluentd logs are being shipped to S3.

**To Reproduce**
1. Start cluster with fluentd enabled in the service cluster
2. List logs in bucket
    ```ash
    ❯ s3cmd -c ~/.s3cfg-exo.ini ls s3://olle-dev-sc-logs/logs/20210317/ | grep fluentd
                       DIR   s3://olle-dev-sc-logs/logs/20210317/kubernetes.var.log.containers.fluentd-0_fluentd_fluentd-58cf3a6b77696e6eddd33699bb6ba86c0c58ff0d06661f96af1dbb267829efd5.log/
                       DIR   s3://olle-dev-sc-logs/logs/20210317/kubernetes.var.log.containers.sc-logs-retention-1615939200-zfkv8_fluentd_aws-cli-ad0fda5da417604e5061e07a9a33e257d7fbd5ce0dd57bd753cdcbe4b33670fd.log/
                       DIR   s3://olle-dev-sc-logs/logs/20210317/kubernetes.var.log.containers.fluentd-mdgvj_fluentd_fluentd-ed5dd2f9fc7e11ce75e1cc7d2cb90fac3868dc79ff0c7113401f2c3e9fc25867.log/
    ```

**Expected behavior**
Fluentd logs are not being stored.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.11.0

**Additional context**
I do think that we want to exclude fluentd logs, and i guess that it was just that the match was not updated when we moved to the bitnami helm chart.

**Solution**
Update [fluentd configuration](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/fluentd-configmap.yaml.gotmpl#L18-L20) to match fluentd (aggergator containers only?) containers, e.g.
```bash
<match kubernetes.var.log.containers.fluentd-**>
  @type null
</match>
```

**Comment by robinelastisys** [comment]
https://github.com/elastisys/compliantkubernetes-apps/pull/357
