### ISSUE TITLE
CK8s Apps on top of IONOS Managed Kubernetes

### ISSUE THREAD

**Issue by llarsson** [elastisys/compliantkubernetes-apps#336]
**What should be investigated.**

IONOS, a huge German cloud provider, offers a managed Kubernetes service. A managed control plane, essentially. Connects to auto-scaled worker node groups. Has support for their load balancing service and dynamically provisioned storage. 

Can we (a) easily deploy CK8s Apps, and if so, (b) what parts may not be needed? 

https://www.ionos.com/enterprise-cloud/managed-kubernetes

**What artifacts should this produce.**

 - Documentation that outlines how to install CK8s Apps on top of IONOS Managed Kubernetes. For future publication on compliantkubernetes.io
 - Operational insights documented in a text document to inform the rest of the organisation: would we be ready to manage node groups on top of this cloud for customers? If no, what are the blockers?

**Comment by raviranjanelastisys** [comment]
Sign up for ionos cloud provider done , Done with setting up the 2 managed cluster - one for service and other for workloads . CK8S apps deployment in progress

**Comment by raviranjanelastisys** [comment]
Able to deploy the ck8 on the managed k8 cluster offered by IONOS cloud , with dynamic storage class "ionos-enterprise-hdd" provisioning and dynamic provisioning of loadbalancer . In progress-state

**Comment by llarsson** [comment]
What kind of performance do you get for etcd in this setup, can you see whether the etcd component seems "happy" and is not complaining about operations taking too long?

**Comment by raviranjanelastisys** [comment]
<img width="766" alt="etcd_performance_SSD" src="https://user-images.githubusercontent.com/75951259/115831156-d68dcc00-a42e-11eb-9c5d-7da27cbd6df2.PNG">

99th percentile of fdatasync durations is 8.029ms which is < than 10ms - Which should be considered the storage is fast enough.

**Comment by OlleLarsson** [comment]
@llarsson still relevant :) ?

**Comment by llarsson** [comment]
@OlleLarsson, that's more a question for @simonekman -- I don't think we have a large enough pool of interested customers to add more time to this.

**Comment by simonekman** [comment]
@OlleLarsson @llarsson @tordsson. I would say we can pause this until further notice, IONOS support will not be relevant for many months. At the moment we should focus on adding support for one more cloud and that will likely be UpCloud. That means we have no real need for IONOS until we want to hire sales people in Germany and I don't see that happening any time soon.

**Comment by OlleLarsson** [comment]
I'll close this now
