### ISSUE TITLE
Elasticsearch-slm job doesn't fail on error

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#339]
**Describe the bug**
Issue #337 was discovered only after the elasticsearch-slm jobs started to hit their deadline. Before that they have run for several days just looping through all snapshots and erroring on the malformed `MAX_AGE_SECONDS`. The Job should fail if there is an [error in the script](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/elasticsearch-slm/scripts/slm-retention.bash).

**To Reproduce**
1. Create an environment with elasticsearch and elasticshearch-slm
2. Set the `MAX_AGE_SECONDS` to something weird, like `2.592e+06`
3. Trigger an SLM job. You can do this with `./bin/ck8s ops kubectl sc -n elastic-system create job manual-slm --from=cronjob/elasticsearch-slm`
4. Check what happens with the Job. Does it complete "successfully"?

**Expected behavior**
The Job should not be counted as successfully completed if the script has errors.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.9.0

**Additional context**
I'm not really sure why the script doesn't exit with an error since it looks like we specify the necessary parameters [here](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/elasticsearch-slm/scripts/slm-retention.bash#L13)

**Comment by OlleLarsson** [comment]
Would it make sense to change the [restart policy](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/elasticsearch-slm/templates/cronjob.yaml#L19) to `Never`?

**Comment by OlleLarsson** [comment]
It doesn't fail becuse of [this ](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/elasticsearch-slm/scripts/slm-retention.bash#L83).

**Comment by lentzi90** [comment]
Not sure what impact that would have. It doesn't look like it has restarted, it just thought it was successful and stopped after looping though all snapshots and logging errors.

```
/scripts/slm-retention.bash: line 68: [: 2.592e+06: integer expression expected
/scripts/slm-retention.bash: line 88: [: 2.592e+06: integer expression expected
...
```

If it restarted the Job there would be multiple Pods with just the one error line and then exit I think.

**Comment by OlleLarsson** [comment]
```bash
❯ if [ "12345" -gt "123345.0" ]; then echo hej; fi; echo $?
bash: [: 123345.0: integer expression expected
0
```
This does not throw an error

**Comment by lentzi90** [comment]
Ah I see, then that is the problem! Thanks for looking into it!

**Comment by OlleLarsson** [comment]
Using the extended test seems to return an appropriate error code on such errors.
```bash
❯ [[ "12345" -gt "123345.0" ]]; echo $?
bash: 123345.0: syntax error: invalid arithmetic operator (error token is ".0")
1
```

**Comment by tordsson** [comment]
Check addition scripts for the same error...

**Comment by Xartos** [comment]
> Using the extended test/comparison seems to return an appropriate error code on such errors.

I think it's still an issue since you need to include the if statement that eats that error code

```bash
$ if [[ "12345" -gt "123345.0" ]]; then echo hej; fi; echo $?
bash: [[: 123345.0: syntax error: invalid arithmetic operator (error token is ".0")
0

$ if [ "12345" -gt "123345.0" ]; then echo hej; fi; echo $?
bash: [: 123345.0: integer expression expected
0
```

I'd suggest we just use `printf` to always remove all decimals

```bash
$ if [ "12345" -gt "$(LC_ALL=C printf '%.0f\n' 123345.0)" ]; then echo hej; fi; echo $?
0
```
