### ISSUE TITLE
SC log retention doesn't work with some S3 "compatible" implementations

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#340]
**Describe the bug**
The [sc-logs-retention](https://github.com/elastisys/compliantkubernetes-apps/tree/main/helmfile/charts/sc-logs-retention) CronJob runs successfully without deleting all old logs. You can see this by checking the logs from multiple runs and notice that they remove logs from the same days. This probably only happens with some providers that have a faulty or incomplete implementation of the S3 API.

**To Reproduce**
1. Make sure there are lots of logs stored in the bucket.
2. Run the retention job, either manually or wait for it to run multiple times.
3. Compare the logs between the runs.
4. See that even though Job 1 claims to have deleted logs from day xx.yy.zzzz, Job 2 also finds and deletes logs from this day.

**Expected behavior**
The Job should remove all logs from the days outside of the retention period, not just some.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.9.0

**Additional context**

The problem is probably due to a faulty/not complete implementation of [list-objects-v2](https://docs.aws.amazon.com/cli/latest/reference/s3api/list-objects-v2.html).

**Comment by tordsson** [comment]
1 file per container and 5 minutes, summing up to quite a few due to curator, etc. 

Suggested solution: loop over delete until all files gone...
