### ISSUE TITLE
Disabling retention breaks influxDB

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-apps#350]
**Describe the bug**
In sc-config, it is possible to disable retention (influxdb.retention.enabled: false). However, this leads to a broken influxDB installation as a number of configmaps are not installed, while the container still tries to mount them on creation.

**To Reproduce**

Set influxdb.retention.enabled: false in sc-config for a new instatllation 
./bin/ck8s apply sc

Verify that influxdb-0 refuses to start

**Expected behavior**
Either it should be possible to deploy influxDB to a working state without retention or de option to disable it should be removed.

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version [e.g. v0.12.0] (and probably all earlier too)

**Additional context**

**Comment by tordsson** [comment]
There are long-running production clusters with disabled retention that does not experience this problem, some recent config update caused this?

**Comment by viktor-f** [comment]
The problems seems to be that we always add some extra containers that try to mount some config maps https://github.com/elastisys/compliantkubernetes-apps/blob/5d9d5a0f2408db4a61e9679859302497487225b7/helmfile/values/influxdb.yaml.gotmpl#L127
But the configmaps are only created if we set retention to false
https://github.com/elastisys/compliantkubernetes-apps/blob/5d9d5a0f2408db4a61e9679859302497487225b7/helmfile/values/influxdb.yaml.gotmpl#L26
https://github.com/elastisys/influxdb-helm-charts/blob/4ee46c171439c8c2cca192d0717eec18080a299a/charts/influxdb/templates/elastisys_custom/cronjob-cm.yaml#L1

**Comment by tordsson** [comment]
Possibly evaluate InfluxDB v2 and see if it is leaner in memory usage, etc.
