### ISSUE TITLE
[1] Add kube-bench-metrics chart

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#353]
**Is your feature request related to a problem? Please describe.**
We want to use [kube-bench-metrics](https://github.com/ibrokethecloud/kube-bench-metrics) in compliantkubernetes in order to run the kubernetes benchmark and show the results in a dashboard.

**Describe the solution you'd like**
Add the chart to our helmfile and add any necessary config.
We will need to add it to our [chart-repo](https://github.com/elastisys/chart-repo) as well.

**Describe alternatives you've considered**
We could try to add the chart to some other chart repository.

**Additional context**
Depends on https://github.com/elastisys/compliantkubernetes-apps/issues/352

**Definition of done:**
When kube-bench-metrics is installed with the rest of the apps.

**Comment by viktor-f** [comment]
#352 is done so we can proceed with this one now.

**Comment by crssnd** [comment]
I need to have a discussion with @viktor-f about this.

**Comment by crssnd** [comment]
@pettersv, @viktor-f  I updated the docker image for kube-bench-metrics, as discussed yesterday, but the new image fails to expose the metrics.

**Comment by crssnd** [comment]
We will need to invest time in updating/maintaining the kube-bench-metrics project.

**Comment by crssnd** [comment]
@tordsson @cristiklein 
How important is this feature for us?
This will take a continuous maintenance to keep this project up to date and we need to decide how that will look for us.

**Comment by cristiklein** [comment]
Thanks @crssnd 

I am happy to close this feature request, but I'd like to replace it with a task where we run `kube-bench` and check if there is room for improvement.

Do you agree @tordsson ?

**Comment by viktor-f** [comment]
> Thanks @crssnd
> 
> I am happy to close this feature request, but I'd like to replace it with a task where we run `kube-bench` and check if there is room for improvement.
> 
> Do you agree @tordsson ?

So have it as more of a manual task that we run periodically (maybe once per kubernetes release)?

**Comment by cristiklein** [comment]
@viktor-f That would be perfect!

**Comment by viktor-f** [comment]
Ok, sounds like a good plan.
@tordsson we will still wait for your opinion before closing this and creating a new task.

**Comment by tordsson** [comment]
Sure, once per release is fine as of now. Thanks!
