### ISSUE TITLE
[1] Add kube-bench dashboard

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#354]
**Is your feature request related to a problem? Please describe.**
We want to use [kube-bench-metrics](https://github.com/ibrokethecloud/kube-bench-metrics) in compliantkubernetes in order to run the kubernetes benchmark and show the results in a dashboard.

**Describe the solution you'd like**
Copy the grafana dashboard from kube-bench-metrics and add it to our grafana dashboard helmchart: https://github.com/elastisys/compliantkubernetes-apps/tree/main/helmfile/charts/grafana-ops
It should be possible to use the dashboard directly from  kube-bench-metrics, but if we want to do any changes then they should also be upstreamed.

**Describe alternatives you've considered**

**Additional context**
Depends on https://github.com/elastisys/compliantkubernetes-apps/issues/352 (a PR in kube-bench-metrics needs to be merged).

**Definition of done:**
When a dashboard is automatically added (when kube-bench-metrics is enabled) and we can see the results of the kubernetes benchmark.
We are using the same dashboard as the one available upstream.

**Comment by viktor-f** [comment]
#352 is done so we can proceed with this one now.

**Comment by crssnd** [comment]
Depends on  [#353 ](https://github.com/elastisys/compliantkubernetes-apps/issues/353)
