### ISSUE TITLE
Move away from "pulling" charts

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-apps#355]
**What should be investigated.**

*Task from arch meeting 2021-03-25*
We currently pull the 3:rd party helm chart on apply. If a link is broken or the chart removed upstream the install will fail. Also, it is not possible to "grep" for values in the charts as they are not present in our repo. Investigate if there is another way to do this.

**What artifacts should this produce.**
A proposal and feasibility study of an alternate apporach, perhaps "vendoring" the charts.

**Comment by cristiklein** [comment]
Thanks @pettersv !
