### ISSUE TITLE
[1] Default to object storage disabled

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#361]
**Is your feature request related to a problem? Please describe.**

To improve DX (developer experience), it would be great to make it quicker to set up Compliant Kubernetes for quick issues. Currently, S3 buckets are enabled by default, which requires a developer to worry about things like creating S3 buckets, creating S3 bucket access credentials, etc. It would be great to disable this *by default* and enable it only when needed.

For QA and production, we now have the [backup dashboards](https://compliantkubernetes.io/ciso-guide/backup/) and the [QA checklist](https://compliantkubernetes.io/operator-manual/qa/), which should allow us to not forget about testing and enabling this feature when required.

**Definition of done:**

* S3 is disabled by default.
* Documentation exists on how to enable and verify it.
* All backups (InfluxDB, Harbor, etc.) which depend on S3 are disabled by default.
* Harbor (which is the biggest consumer of S3) is either using PVCs for persistence or is disabled by default.
* The ["at the minimum you should configure"](https://compliantkubernetes.io/operator-manual/exoscale/#configure-the-apps) sections in documentation are way shorter.

**Comment by lentzi90** [comment]
Makes sense at least for the dev flavor! It's not like short-lived dev clusters really test backups anyway as backup jobs are run during the night.

**Comment by viktor-f** [comment]
I agree with @lentzi90 that it makes sense for the dev flavor. 
It would give us less "passive" testing of the object storage features, but as long as we still have it enabled in the daily pipeline and in our release QA I think it's fine.

**Comment by cristiklein** [comment]
Please make sure object storage is tested in the daily pipeline and release QA.
