### ISSUE TITLE
[3] Test backups

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#374]
Related to #373 and #317.

**Is your feature request related to a problem? Please describe.**
We don't currently test backups (neither that the backup jobs run successfully, or that it is possible to restore from them) as part of the QA process. This is obviously extremely important in case of disasters so we should add it.

**Describe the solution you'd like**
Come up with one or more suitable test cases that we can include in QA.

**Describe alternatives you've considered**

- Automated tests as part of the pipeline. This unfortunately seems infeasible until we get a long running cluster. It would likely be too much of an effort to add logic that triggers backups early and automatically restores them to a new cluster in the current pipeline. Not to mention that it would make the pipeline duration skyrocket.

**Additional context**

**Definition of done:**

- Documentation for backup and disaster recovery, including
  - All stateful applications that are part of ck8s (elasticsearch, influxdb, grafana, harbor, anything else?)
  - User resources (alerting rules, applications, config, volumes, etc.)
- Add necessary steps to the [release and quality assurance doc](https://docs.google.com/document/d/16_rtMmcjdZmLb-I_aV0wpmgsIBTk6AX3L857XGWYvQU/edit) (or elsewhere if it makes sense).
- A training session for the DevOps team so that everyone is familiar with the above.

**Comment by pettersv** [comment]
hold this task until the long running test cluster is up, and see if it can be automated as per Lennarts suggestion.

**Comment by crssnd** [comment]
@crssnd add a note in the QA release doc about restoring elasticsearch and influxdb.

**Comment by viktor-f** [comment]
We now have disaster recovery exercises once every 3 months. There we do test this. We also test some of the backups during QA
