### ISSUE TITLE
[5] Monitoring Rook and Ceph

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#381]
**Is your feature request related to a problem? Please describe.**
We use Rook and Ceph to provide persistent storage in environments where this is not available from the cloud provider. However, we gather no metrics about the Ceph cluster or Rook outside of the generic data we have on everything that runs in the cluster. There is nothing about the Ceph cluster health, remaining disk space or such. No alerts either.
In order to keep the storage clusters happy, we need insights into how they are performing and a way to detect issues early.

**Describe the solution you'd like**
Configure Rook/Ceph to expose metrics and tell Prometheus to scrape them. Set up alerts for the most obvious things that we need to react to and maybe add a dashboard as well. [This should be a good place to start.](https://github.com/rook/rook/blob/master/Documentation/ceph-monitoring.md)

**Describe alternatives you've considered**
- Rely on existing, generic, data. With this it is possible to tell if Pods are crashing, how much resources they use and if disks on the Nodes are getting full. But these things can be hard to interpret and/or come too late. Available capacity on the Node disks does not translate directly to available capacity in Ceph, for example, since the data is replicated.

**Definition of done:**
Compliant Kubernetes has basic alerts for Ceph cluster health and a dashboard with an overview.

**Comment by cristiklein** [comment]
Grafana dashboards to start with: https://grafana.com/grafana/dashboards?search=ceph
