### ISSUE TITLE
[1] Improve diff in dryrun script

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-apps#382]
In the dryrun.sh script we currently use `helmfile diff`. This will not check agianst what the actual state of the cluster is. Change this to use `helmfile template | kubectl diff` instead.

In the apply.sh script, we should use `helmfile sync` instead of `helmfile apply`

**Comment by viktor-f** [comment]
See this issue for more context and inspiration: https://github.com/databus23/helm-diff/issues/176
