### ISSUE TITLE
[2] Replace stable/dex with dex/dex

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#385]
Self-explanatory issue:
- Replace deprecated helm chart stable/dex with the official [dex/dex](https://github.com/dexidp/helm-charts/tree/master/charts/dex) chart
- Ensure upgrade path

**Comment by Xartos** [comment]
Another reason to do this is to be able to upgrade above vulnerable version https://github.com/dexidp/dex/security/advisories/GHSA-m9hp-7r99-94h5

**Comment by cristiklein** [comment]
When doing this task, please be mindful of ADR #0012 “Do not persist Dex”. We discussed and agreed on this back in April, and I finally managed to document it: https://github.com/elastisys/compliantkubernetes/pull/134 :tada:
