### ISSUE TITLE
Rework Harbor restore script

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#386]
**Is your feature request related to a problem? Please describe.**
The current restore script for Harbor feels a bit clunky and adds dependencies on a postgres CLI and the AWS CLI.

**Describe the solution you'd like**
I propose to change the script to do the following:
1. download the backup using s3cmd instead of the AWS CLI (since we use that in other places as well).
2. Upload the backup to the database pod
3. Excec into the pod and restore from the backup (then we don't need the postgres client locally)
4. Clean up backup files locally and in the pod.

We should probably also add support for GCS since our backup scripts support storing backups there.

**Describe alternatives you've considered**
We could do just the change with s3cmd or the change with the postgres client instead of both.

**Additional context**

**Definition of done:**
We have a restore script that has less dependencies on other tools.
We have clear instructions on how to use the script, both in this repository and in the official documentation (complinatkubernetes.io)

**Comment by OlleLarsson** [comment]
Maybe a k8s job would be perfect for this?

**Comment by viktor-f** [comment]
> Maybe a k8s job would be perfect for this?

Yes, that's also a good option
