### ISSUE TITLE
ck8s init does not update config version and does not set new variables

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#390]
**Describe the bug**

Config version is not updated when issuing `ck8s init`. Various variables are not set.

**To Reproduce**
1. Start from an older config.
2. Set `CK8S_CONFIG_PATH`
3. Run `./bin/ck8s init`
4. Run `./bin/ck8s apply sc`

**Expected behavior**

Apply start running.

**Actual behavior**

```shellSession
$ ./bin/ck8s apply sc
[ck8s] ERROR: Version mismatch!
[ck8s] Config version: 0.7.0
[ck8s] CK8S version: 0.13.0

# After manually fixing version
$ ./bin/ck8s apply sc
[ck8s] Validating sc config
[ck8s] WARN: harbor.oidc.groupClaimName is not set in /home/cklein/elastisys/ck-exoscale-config-ng/sc-config.yaml
[ck8s] WARN: alerts.opsGenieHeartbeat.name is not set in /home/cklein/elastisys/ck-exoscale-config-ng/sc-config.yaml
[ck8s] WARN: alerts.slack.channel is not set in /home/cklein/elastisys/ck-exoscale-config-ng/sc-config.yaml
[ck8s] WARN: ingressNginx.controller.service.type is not set in /home/cklein/elastisys/ck-exoscale-config-ng/sc-config.yaml
[ck8s] WARN: ingressNginx.controller.service.annotations is not set in /home/cklein/elastisys/ck-exoscale-config-ng/sc-config.yaml
[ck8s] Do you want to abort? (y/n): 
```

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.13.0

**Comment by OlleLarsson** [comment]
They are set to "set-me", meaning you should probably have a look at them and set an appropriat value.

**Comment by cristiklein** [comment]
@OlleLarsson That is true, however:

* I have `ingressNginx.controller.service.enabled==false`. Is it possible not to be forced to set service type and annotation, and have good default values instead? We discussed preferring template validation for validating such cases (e.g., https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/issuers/templates/_helpers.tpl#L29). Is this not usable in this case?
* Similarly, I have `alerts.alertsTo=="null".

I kind of like the `harbor` warning, since that feels like a "new feature" warning. :smile:

**Comment by cristiklein** [comment]
We moved this to "Re-evaluate" since this feels part of a larger discussion on expectation management on compliantkubernetes-apps.

Personally, I like to keep all configs in git. Then I do:
```
git checkout config
./aggressive-command-that-changes-too-many-configs.sh

# manually review, accept or reject changes
git diff
git checkout -p
git add -p
git commit -m "Updated config"
```

Seems like some prefer a more conservative config command.

**Comment by tordsson** [comment]
Pending outcome of #407 .

**Comment by Xartos** [comment]
Also related #607

**Comment by crssnd** [comment]
@aarnq did you also fix this with your split config work?

**Comment by aarnq** [comment]
@crssnd Yes, the version is updated and the default configs are updated with new values after init.
