### ISSUE TITLE
[1] Default retention values for other* and authlog* are larger than the prod flavor

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-apps#401]
The default retention values for other* and authlog* in sc-config.yaml are larger than in prod-sc.yaml which is a bit strange. For the other* index just change the default to match dev-sc.yaml. For authlog* have a look in kibana how quickly the index grows over a period of 24-48 hrs and make an estimate on how large values are needed for default, dev and prod.

**Comment by robinelastisys** [comment]
**Maj 4**
health status index                             uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   authlog-default-2021.05.04-000001 KeKH-uiIQLuPO48zwe8Bjw   1   1      14157            0      2.4mb          2.4mb

health status index                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   other-default-2021.05.04-000001 Pu2BMU0aTe-iTN4OExTIug   1   1       4899            0      1.5mb          1.5mb
