### ISSUE TITLE
Try out Debricked for Vulnerability Management

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#406]
**What should be investigated.**

Does it make sense to use [Debricked](https://debricked.com/) for advancing our vulnerability management story?

> Is Debricked free for open source?
> Yes, Debricked provides unlimited access to maintainers of open source projects. Just start a trial and contact support@debricked.com to get unlimited scans!

**What artifacts should this produce.**

* A report with vulnerabilities found by Debricked
* A demo

**Comment by tordsson** [comment]
Debricked not scaning terraform, helm, etc.
