### ISSUE TITLE
Come up with a plan on how to move towards simple-ck8s

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#407]
**What should be investigated.**

During the arch meeting on 2021-04-22, Lennart presented `simple-ck8s`, which brought the following concepts:
- "Bare" usage commands: `kubectl apply -f`, `helmfile`.
- Full exposure of Helm Releases' values file, minimal values templating
- No "big config", rather layered, per-Release configs.
- Compliant Kubernetes would (more-or-less) become the per-environment config repository.

There was consensus that such an approach better supports our needs to set up highly customized Compliant Kubernetes clusters.

However, such an approach also brings lots of uncertainties:

- How should a new cluster be created?
- How should an existing cluster be re-configured?
- How should an existing cluster be upgraded, being mindful of merging upstream Compliant Kubernetes features, and environment-specific overrides?
- How can we make this as risk-free as possible?
- How can we ensure that we can keep track of everything, e.g., only those configurations that matter for each Helm Release?

**What artifacts should this produce.**

- A demo consisting of:
  - The (current or improved) "upstream" simple Compliant Kubernetes repo
  - Two pairs of vanilla Kubernetes clusters
  - Show us how to create a simple Compliant Kubernetes cluster-pair, re-configure, update, etc.
- A plan on what actions are necessary to move today's Compliant Kubernetes in the direction of simple-ck8s

**Comment by viktor-f** [comment]
I think that this could be a good task to do in a pair to have as much discussion as possible.

**Comment by pettersv** [comment]
> I think that this could be a good task to do in a pair to have as much discussion as possible.

I agree, this is not a one-man job :)

**Comment by cristiklein** [comment]
> > I think that this could be a good task to do in a pair to have as much discussion as possible.
> 
> I agree, this is not a one-man job :)

Agreeing with your agreement. :)

**Comment by lentzi90** [comment]
This looks great! Also agreeing that more than one person should work on this. :slightly_smiling_face: 

> Compliant Kubernetes would (more-or-less) become the per-environment config repository.

I would rather say that Compliant Kubernetes would become:
- common/default values
- example config/secrets
- multiple flavors or layers of common values (like current dev/prod but these could actually be merged when it makes sense, e.g. dev prometheus + prod opendistro)
- documentation
- helper tools (e.g. templating tool for initializing environments, config validator, secret generator, etc.)

The actual config for each environment would be separate.

**Comment by cristiklein** [comment]
@lentzi90 Good point! We kind of have that for [`compliantkubernetes-kubespray`](https://github.com/elastisys/compliantkubernetes-kubespray/tree/main/config). That could serve as inspiration.

**Comment by OlleLarsson** [comment]
Still relevant @cristiklein ?

**Comment by cristiklein** [comment]
@OlleLarsson No, good to close from my side.
