### ISSUE TITLE
Investigate letsencrypt limits

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-apps#408]
**What should be investigated.**
Investigate where the limits are for letsencrypt, i.e. rate limits and other limits that might affect us if running too many clusters on the same domain.

**What artifacts should this produce.**
A clear presentation of what they are and any recommendations on how to handle them if it is a problem.

**Comment by tordsson** [comment]
https://compliantkubernetes.io/adr/0009-use-cluster-issuers-for-letsencrypt/

50 certs per **registered** domain and week is the limit.

**Comment by tordsson** [comment]
There exists official documentation for this, linked from the above ADR.

**Comment by cristiklein** [comment]
https://letsencrypt.org/docs/rate-limits/

> The main limit is Certificates per Registered Domain (50 per week). A registered domain is, generally speaking, the part of the domain you purchased from your domain name registrar. For instance, in the name www.example.com, the registered domain is example.com. In new.blog.example.co.uk, the registered domain is example.co.uk. We use the Public Suffix List to calculate the registered domain. Exceeding the Certificates Per Registered Domain limit is reported with the error message too many certificates already issued, possibly with additional details.

We'll briefly discuss the implications during today's arch meeting.
