### ISSUE TITLE
Lists in default config can cause validation errors

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#41]
We do some validation of the users config by checking that all config options are present in the user config files.

However if we have lists in the default config, then the validation will fail if the user has less items in their list. 
E.g. if we have this default config:
```
dex:
  allowedDomains:
    - example.com
    - elastisys.com
```
And the user has this config:
```
dex:
  allowedDomains:
    - elastisys.com
```
Then they will get this error `[ck8s] ERROR: dex.allowedDomains.[1] is not set in <config-path>/sc-config.yaml`, which is not something we want.

I'm not sure how to best solve this and it becomes more complex if we ever would like to have some lists with more complex data that we actually want to validate. A first step would perhaps be to skip validations against anything inside a list, but check that the list key exists (`allowedDomains` in the example above).

**Comment by lentzi90** [comment]
Part of #24
