### ISSUE TITLE
InfluxDB does not cleanup backups on failure

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#414]
**Describe the bug**
We use a persistent volume for temporary storage of the InfluxDB backup to avoid disk pressure for the Nodes (and possibly also avoid redoing the dump if upload to S3 fails). This has one caveat: the volume is not guaranteed to be emptied between Jobs. The volume is cleared [only after uploading to S3](https://github.com/elastisys/influxdb-helm-charts/blob/elastisys_extensions/charts/influxdb/templates/backup-cronjob.yaml#L138). If it never gets to this stage, the volume will just fill up with more and more backups. This in turn will make the upload take longer and increase the risk that something goes wrong. So we get a bad spiral of ever increasing risk of failing backups.

**To Reproduce**
1. Make an InfluxDB backup fail before it reaches the part where it empties the backup volume.
2. Notice that the volume usage keeps growing for each backup Job.

**Expected behavior**
A failed backup should not impact the next. This could for example be solved by emptying the volume *before* every new dump, just to be sure, or switch to a non-persistent volume instead.

**Screenshots**
![influxdb-backup-pvc-usage](https://user-images.githubusercontent.com/9117693/116075104-35f01400-a69b-11eb-8972-2b67e9d75fbd.png)

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.13.0

**Additional context**
Our fork of the upstream influxdb helm chart is located here: https://github.com/elastisys/influxdb-helm-charts
The code for backups seems come from the upstream though so we should preferably upstream any changes to it.

**Comment by OlleLarsson** [comment]
Closed by https://github.com/elastisys/influxdb-helm-charts/commit/70d2b148c631744faa5c8089a5968ecfc868c494, right @Xartos ?
