### ISSUE TITLE
Try out PostgreSQL for metrics storage

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#419]
**What should be investigated.**

InfluxDB is currently the elephant in the room. We are not perfectly happy with it, but it is good enough to not warrant replacing it with something like Thanos or Cortex. These solutions have not proven to bring enough value to offset the cost in getting knowledgeable in them and devising processes around them.

In the meanwhile, we are getting better at managing PostgreSQL. We have knowledge and processes for high-availability and disaster recovery. It would be nice to have a single solution which stores "precious state".

Can we replace InfluxDB with PostgreSQL for long-term metrics storage?

**What artifacts should this produce.**

* A demo of Compliant Kubernetes, but with PostgreSQL instead of InfluxDB. Feel free to use the Zalando operator.
* An analysis on the pros and cons of this approach.

**Useful resources**

* https://severalnines.com/database-blog/which-time-series-database-better-timescaledb-vs-influxdb
* https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage (see PostgreSQL)

**Comment by tordsson** [comment]
Not to be done by @OlleLarsson for increased knowledge sharing... :-)

**Comment by raviranjanelastisys** [comment]
Here are my findings :- 

Validated the integrations of prometheus scraped data to store in remote storage postgres timescale database .

1. **Using Zalando Postgres operator** :- TimescaleDB ext is basically available in two licenses Apache and TSL(https://www.timescale.com/legal/licenses)  and Zalanado uses apache. 
    
Promscale works with plain vanilla PG and TimescaleDB TSL license . This could be one of the reason it's not working integrations of zalando postgres operator with promscale .

![image](https://user-images.githubusercontent.com/75951259/119159768-ddbcef80-ba57-11eb-941d-0dbe34cfa029.png)

Solution :- 

                 -  The easiest way is to manually update the TimescaleDB extension to TSL or drop TimescaleDB ext as Promscale works without TimescaleDB ext too - Need to figure how to DO this . 
                 
                 -  Ideal of running in zalando is to upgrade Timescale extension to community version. Running without TimescaleDB extension creates scalability issues. As Promscale is back end store for Prometheus data, the data keeps flowing for every 10-15 secs, so we need all compression and scalability features offered by TimescaleDB.

2. **Standalone Timescale DB** :- Integrations of promscale ( via connector ) with standalone timescaledb cluster works fine and we are able to store the prometheus scrapped metrics data to remote timescale db .

![image](https://user-images.githubusercontent.com/75951259/119161846-09d97000-ba5a-11eb-9b39-5e9d37b2213b.png)

![image](https://user-images.githubusercontent.com/75951259/119162047-39887800-ba5a-11eb-9b34-36a2bdc0d980.png)

**Comment by cristiklein** [comment]
After discussing a bit more with Ravi, we determined that using PostgreSQL for metrics storage currently needs deploying TimescaleDB with their special license called [TSL](https://www.timescale.com/legal/licenses). I am currently unsure about the legal implications thereof, i.e., how viral the license is. Would TSL have implications on the rest of Compliant Kubernetes? What exactly is a "Value Added Products or Services", as defined in TSL and are we in any way affected by it. Even if this does not have factual implications on Compliant Kubernetes, this might weaker our message that Compliant Kubernetes is a fully open-source project.

The community has plans to make Promscale work with the open-source (Apache 2.0) version of TimescaleDB. I recommend we wait for that one. (See [here](https://github.com/timescale/promscale/issues/583#issuecomment-819477145)).

**Comment by tordsson** [comment]
I'd say wait and see. Moving from InfluxDB is not worth the additional risk of TSL license implications at this point IMHO.

**Comment by Harkishen-Singh** [comment]
@cristiklein note the OSS fix: https://github.com/timescale/promscale/pull/659

**Comment by cevian** [comment]
We are in the process of creating a PR for this. But just to clear some things up:

**Comment by cevian** [comment]
We are in the process of fixing the OSS version but I wanted to clear some things up about the TSL:
1) It is not viral in any way.
2) A "Value Added Products or Services" is one that is /not/ just DBaaS. So if you host a TSL product it should have some value added for the customer, and not just a hosted TimescaleDB. In the license, we define this on a technical level as a product that does not give users /direct/ access to DDL (create table, add column) operations. It sounds to me like this project would qualify. You can always email me (mat@timescale.com) if you want to discuss further.

On a technical level the big problem with using TimescaleDB-OSS is the lack of compression, so your data will be significantly bigger on-disk. We see 95%-99% compression on these datasets.

**Comment by raviranjanelastisys** [comment]
https://github.com/timescale/promscale/issues/635 - seems like this is fixed in release version 0.5.1 and Promscale integartion with timescaleDB ext with Apache 2.0 liecense is resolved .
