### ISSUE TITLE
Add dashboard for node-local-dns

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#422]
**Is your feature request related to a problem? Please describe.**

When looking at grafana, there's no way of checking how the node-local-dns is performing. Even though it has metrics exposed.

**Describe the solution you'd like**

Add service/service monitor for metrics for node-local-dns

**Describe alternatives you've considered**

Not implementing this task

**Definition of done:**
I can check performance of node-local-dns in grafana.

**Comment by Zash** [comment]
How about [this one?](https://grafana.com/grafana/dashboards/12007-node-local-dns/)
