### ISSUE TITLE
Remove NFS-client-provisioner

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-apps#423]
We do not use the NFS-client-provisioner anymore and much prefer Rook to it for projects where the cloud provider is missing storage. Therefore we should remove all traces of NFS from Compliant Kubernetes Apps.

**Comment by OlleLarsson** [comment]
@cristiklein @tordsson shall we keep NFS?

**Comment by cristiklein** [comment]
Architectural decision here. :smile: Please remove NFS from this repo. If we get customer requests for NFS support, we will simply add the [NFS client chart](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/tree/master/charts/nfs-subdir-external-provisioner) as a manual step after Kubespray, similarly to how we proceed with Rook.

**Comment by cristiklein** [comment]
Amen! :smile:
