### ISSUE TITLE
Investigate HA harbor setup

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#433]
**What should be investigated.**
To make our services more stable I suggest that we investigate running Harbor in HA. I don't think we necessarily always need to run Harbor in HA. But it would be very nice if we in our config could chose to scale up harbor when we want to.

The harbor helm chart has some notes on how to do this: https://github.com/goharbor/harbor-helm/blob/master/docs/High%20Availability.md

In short we can scale up all Harbor pods via the chart, except for the database and redis, as long as we use s3 for image and chart storage (or use ReadWriteMany disks). If we want HA database(postgres) and redis for harbor, then we need to run that ourselves (the chart supports "external" database/redis).

Things to investigate:
- Can we run the Harbor pods (excluding database and redis) in HA? Is it significantly harder/more complicated?
- Could we have config that supports both HA and non-HA setups?
- Is it worth to try to run our own database/redis to get HA for them as well?

**What artifacts should this produce.**
Document with answers to the above questions and rough instructions for what was done (e.g. what config that needed changes).

**Comment by tordsson** [comment]
Revisit based on clustered database and redis services.

**Comment by viktor-f** [comment]
Closing in favor of https://github.com/elastisys/compliantkubernetes-apps/issues/854
