### ISSUE TITLE
[1] Investigate Azure AD with Dex

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#449]
**What should be investigated.**
Integrating Azure AD with Dex.

**What artifacts should this produce.**
Possible: yes/no.
If yes: dex configuration example.

**Comment by Xartos** [comment]
Snippet on how to set this up exists [here](https://github.com/elastisys/compliantkubernetes-apps/blob/main/config/secrets/sc-secrets.yaml#L88-L98)
