### ISSUE TITLE
[1] Enable additional static clients for dex

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#456]
**Is your feature request related to a problem? Please describe.**

Since users might want to enable their own applications to be able to use dex, it would be nice to add a `additionalStaticClients` for dex

**Describe the solution you'd like**

Configuration for dex where you can add additional static clients.
It should add it to this list https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/dex.yaml.gotmpl#L69

And since there's some secret information included in each entry this should really reside in `secrets.yaml`

**Describe alternatives you've considered**

Not have this option. This would not enable users to utilize the SSO of ck8s in their applications.

**Additional context**

**Definition of done:**

I'm able to add arbitrary amount of static clients to dex (with any config)

**Comment by tordsson** [comment]
use case: ArgoCD CLI needed another Dex client
