### ISSUE TITLE
[1] Many grafana dashboards are broken

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#466]
**Describe the bug**

A lot of our dashboards are using the variable `__rate_interval` [which was introduced in grafana 7.2](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/) while we are running grafana 7.0

This breaks a lot of our dashboards with the error `parse error: missing unit character in duration`

This can be fixed by either change all these variables to `__interval` or we can upgrade grafana to a later version (I would refer the latter)

**To Reproduce**
1. Go to Grafana
2. Go to the dashboard `Kubernetes / Compute Resources / Namespace (Workloads)`
3. Scroll down to the network dashboards on the bottom

**Expected behavior**

No error to show

**Screenshots**

![screenshot_2021-05-26-162809](https://user-images.githubusercontent.com/2071713/119678165-9a8bc380-be3f-11eb-8c12-959b19c8c9eb.png)

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.15.0

**Additional context**

**Comment by tordsson** [comment]
Only kube-prometheus-stack affected.

Update chart is the preferred solution.

**Comment by Xartos** [comment]
> Only kube-prometheus-stack affected.

The rook monitoring dashboard is also affected.

**Comment by viktor-f** [comment]
> > Only kube-prometheus-stack affected.
> 
> The rook monitoring dashboard is also affected.

He meant that only the ops grafana (which is installed by the kube-prometheus-stack chart) is affected, the user grafana is running v7.3.3.
