### ISSUE TITLE
Starboard: Make it possible to disable starboard

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#492]
I'd like to have the option to disable starboard and its corresponding exporter and dashboards.

https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/50-applications.yaml#L112-L132

**Comment by tordsson** [comment]
Not scanning container images runtime would weaken the security and data protection promises of ck8s.

**Comment by OlleLarsson** [comment]
Opening again due to starboard crashing in too many cluster and for seemingly different reasons.
Until starboard is more stable it would be desirable for the ops team to simply disable it until then.
