### ISSUE TITLE
Race condition between user-rbac and user-alertmanager

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#500]
**Describe the bug**
There is a race condition between the installation of `user-rbac` and `user-alertmanager` releases.

**To Reproduce**
1. Configure namepsace `production` to be created. https://github.com/elastisys/compliantkubernetes-apps/blob/main/config/config/wc-config.yaml#L119
2. Enable user alertmanager and specify it to be installed in namespace production.https://github.com/elastisys/compliantkubernetes-apps/blob/main/config/config/wc-config.yaml#L131
3. Run apply on a fresh cluster
4. Enjoy (possible) error :D
  ```
  COMBINED OUTPUT:
  Release "user-alertmanager" does not exist. Installing it now.
  W0621 14:14:51.990712  146099 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
  Error: create: failed to create: namespaces "production" not found
exit status 1
  ```

**Expected behavior**
You can install user-alertmanager in user namespace and apply step won't fail.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.16.0

**Comment by OlleLarsson** [comment]
Hint: use the `needs` directive in helmfile to say that user-alertmanager NEEDS user-rbac :)

**Comment by robinelastisys** [comment]
Seems to have been fixed already
