### ISSUE TITLE
Encryption of backups

### ISSUE THREAD

**Issue by tordsson** [elastisys/compliantkubernetes-apps#506]
As a compliant kubernetes administrator, I would like to ensure that all backups (Elastic, Velero, Postgres, etc.) are encrypted at rest and in transit. This has been requested several public sector software vendors. 
Some cloud providers support encrypted s3 services, but not all. A possible solution would be to use min.io
to encrypt data before sending to s3. 

**Definition of done:**
All backup data is encrypted at rest + in transit.

**Comment by Xartos** [comment]
If we're setting this up with min.io lets also create separate credentials for each application and give access only to the bucket it's using.

**Comment by OlleLarsson** [comment]
We probably need to configure some applications to pass the encryption header.
[Fluentd ](https://github.com/fluent/fluent-plugin-s3/blob/5542b4a1f354e9c149e637c1be9ce199b32f44eb/docs/output.md#use_server_side_encryption)
[Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-repository.html#repository-s3-repository)
etc...

**Comment by Xartos** [comment]
@OlleLarsson There seems to be different type of sever-side encryption modes. https://docs.min.io/docs/minio-security-overview.html

And one mode is that min.io does the key handling and not the client. And then it should work without updating any of our clients. Although then min.io needs some key management system, seems like they recomend running vault in the cluster to solve this. https://docs.min.io/docs/minio-kms-quickstart-guide.html

I guess this will be up to the one picking up this task to decide what seems more resonable/time efficient.

**Comment by Xartos** [comment]
There were some more issues regarding this than initially though and thus can't be easily integrated into apps.

I have instead created a separate repo https://github.com/elastisys/ck8s-minio with how to install it manually and some notes on how to make it automated enough for us to integrate it into apps.

**Comment by llarsson** [comment]
See this comment: https://github.com/elastisys/roadmaps/issues/21#issuecomment-1025693340
