### ISSUE TITLE
What's up with Loki?

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#507]
**What should be investigated.**

Compliant Kubernetes provides user with the capability of full-text search over their logs. Right now we implement this using OpenDistro. However, OpenDistro is discontinued and it's follow-up project -- OpenSearch -- [does not have a Helm Chart yet](https://github.com/opensearch-project/OpenSearch/issues/561).

Let us "shop for other options" and investigate if [Loki](https://grafana.com/docs/loki/latest/) is a viable alternative.

One idea would be to set up a Kubernetes cluster running Loki and directing the logs of all production service clusters to this Loki cluster, so as to get our hands dirty and test Loki beyond day 1.

**What artifacts should this produce.**

* A working Loki cluster
* Some logs -- e.g. service clusters -- being directed to it.
* A demo highlighting the good, the bad and the ugly of Loki vs OpenDistro.

**Comment by viktor-f** [comment]
@cristiklein is this still something that we want to look at?

**Comment by cristiklein** [comment]
@llarsson This is low-prio for MS, but valuable knowledge to have overall. Is this something CNOSA can do in their "spare" time? 😁

**Comment by cristiklein** [comment]
Since we decided to move forward with OpenSearch, this issue is no longer of interest.
