### ISSUE TITLE
Fix 0.16 to 0.17 migration issues

### ISSUE THREAD

**Issue by robinelastisys** [elastisys/compliantkubernetes-apps#516]
**Describe the bug**
To make 0.16 to 0.17 migration work, dex needs to be removed before applying the updated version and the migrate-openid.sh script needs to be modified slightly.

**To Reproduce**
1. Setup a cluster using version 0.16
2. Go through the steps in upgrade-apps.md

**Expected behavior**
0.16 to 0.17 migration goes smooth.

**Version (add all relevant versions):**
 - Compliant kubernetes apps version 0.16 .

**Comment by viktor-f** [comment]
For future reference: you don't need to create issues for the fixes done during release QA, we count that as part of the QA process.
But if you find problems during QA that will not be fixed for that release, then it's very good to create an issue for it.
