### ISSUE TITLE
Get dex to work in Kibana in release-0.17 on a new cluster automatically

### ISSUE THREAD

**Issue by robinelastisys** [elastisys/compliantkubernetes-apps#523]
**Describe the bug**
As of now, dex work halfway in Kibana on a new cluster. You can fix it easily by running migrate-openid.sh but before that, Kibana will say "Unauthorized" when you try to enter it. Feels like a "kubectl apply" race condition error.

**To Reproduce**
1. Setup a new exoscale cluster with "git checkout release 0.17" and configure dex
2. Try enter your Kibana page
3. You will get a page saying "Unauthorized"
4. Fix it by running /migration/v0.16.x-v0.17.x/migrate-openid.sh

**Expected behavior**
That you can log in to Kibana using your google account by dex without having to run /migration/v0.16.x-v0.17.x/migrate-openid.sh on a fresh cluster.

**Comment by viktor-f** [comment]
I think I have seen the same (or a similar) issue before as well. I I remember correctly it could be fixed by just restarting Kibana.
