### ISSUE TITLE
[3] Add node pressure dashboard

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#525]
**Is your feature request related to a problem? Please describe.**

Add a new dashboard that shows, at a glance the current pressure of all the nodes in the cluster.

**Describe the solution you'd like**

I would like to have a simple dashboard that shows the current pressure of a node with basic metrics for all nodes at the same time.
Add CPU (%), Memory (%), IOPS, Network bandwith on separate panel, where each panel shows a graph of the metric for all nodes.
This would be good if an operator wants to quickly get a grasp of the pressure of all nodes in the cluster.

**Describe alternatives you've considered**

Not having this dashboard and using the existing dashboards where you need to click through all the nodes one by one.

**Additional context**

**Definition of done:**

There's a dashboard in ops grafana that shows node pressure for all nodes in the cluster

**Comment by crssnd** [comment]
@Xartos we already have a dashboard that shows this information: "USE Method / Cluster"
the dashboard should be fixed by #547

**Comment by crssnd** [comment]
@Xartos the graph will be fixed by #664
this is how it looks like:
![image](https://user-images.githubusercontent.com/77267293/142198597-5806fbea-f014-4ec2-940e-e65680fe2155.png)
Let me know if this is not what you want.

**Comment by Xartos** [comment]
@crssnd Yes, this seems like a good dashboard for this

**Comment by crssnd** [comment]
ok I will close this issue
