### ISSUE TITLE
Update pipeline alerts to include more error info

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#526]
**Is your feature request related to a problem? Please describe.**
I would like to see more information in slack when the pipeline fails. I can of course click the link and check what went wrong, but it would be nice with a small summary directly in slack. Especially so you can quickly see if some new feature broke the pipeline or if it was one of our regular "random" errors that sometimes occurs (which we can't really control).

**Describe the solution you'd like**
When a pipeline fails I would like to see which job failed, which step in that job failed, and around the last 10 log lines from the failed step. That is hopefully enough to identify the general error, but feel free to alter this.

There is sometimes several steps that fails because the error cascades. So it is probably enough to just show the first failed step in a job, but that can be discussed.

**Describe alternatives you've considered**
Skip this and continue to always check the error in github.

**Additional context**

**Definition of done:**
The alerts contain more information when there is an error.

**Comment by robinelastisys** [comment]
This task may be best suited for someone that is in control of the pipeline end-to-end.

**Comment by viktor-f** [comment]
@crssnd are you still working on this?

**Comment by crssnd** [comment]
@viktor-f yes, I need to fix a regex in my code and test it. I hope I will create a PR for this tomorrow.
