### ISSUE TITLE
A lot of broken dashboards

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#534]
**Describe the bug**

Since we upgraded kube-prometheus-stack and grafana we have some broken dashboards.

From what I can see these are:

* Elasticsearch: Probably just stat panels that are incorrectly setup
* Kubernetes cluster status: Some metrics have been updated to specify resource type as a metric label rather than having it in the metric name e.g. `kube_pod_container_resource_requests_cpu_cores` is now `kube_pod_container_resource_requests{resource="cpu"}`
* Proxy
* Uptime and status: Stat panel values mapping is wrong
* USE dashboards

**To Reproduce**
1. Set up a cluster with ck8s v0.17.0
2. Go to grafana and look at the broken dashboards

**Expected behavior**

Dashboards should work

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.17.0

**Additional context**

**Comment by crssnd** [comment]
I fixed some of the dashboards and created a PR (#546)
For the Kubernetes and USE Method dashboards I created a new issue (#547) because it needs more discussion and updates.
