### ISSUE TITLE
[3] Ingress-nginx - enable modsecurity

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#536]
**What should be investigated.**
Enabling [modsecurity](https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/modsecurity/) for ingress-nginx.

**Definition of Done**
Is is feasible to enable modsecurity?
Can we enable/disabled enable-owasp-core-rules per domain? How easy?
What is the performance impact of enabling this?

**Comment by crssnd** [comment]
@cristiklein how long are you willing to wait for bunkerized-nginx kubernetes integration go stable?

**Comment by cristiklein** [comment]
@crssnd Is it as simple as adding two lines in the Ingress ConfigMap?

```yaml
enable-modsecurity: "true"
enable-owasp-modsecurity-crs: "true"
```

If yes, then I wouldn't wait any longer.

**Comment by crssnd** [comment]
@cristiklein according to the docs:
"It can be enabled for a particular set of ingress locations. The ModSecurity module must first be enabled by enabling ModSecurity in the ConfigMap. Note this will enable ModSecurity for all paths, and each path must be disabled manually."

the short answer is yes, but let's see what the investigation will reveal :)
