### ISSUE TITLE
Add/update resource requests/limits

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#545]
**Is your feature request related to a problem? Please describe.**
We should ensure that all pods we install have some sane default resource requests/limits, currently we lack it in many pods.
This is important to make sure that the scheduling of pods is good and to show our users that we take it seriously (especially since we recommend other to do this).

**Describe the solution you'd like**
Look at a few running clusters to see which pods are missing resource requests/limits and add some default based on actual usage. We can easily gather this information by looking at the grafana dashboard "Kubernetes cluster status". There we can also check for existing resource requests that are much higher/lower than the actual usage, for those we should do some adjustments.

The defaults do not have to be perfect, something that is ok is much better than nothing. If we check both dev clusters and prod cluster while doing this and discover that they you very different amount of resources, then add different requests/limits to different flavors. We should also for most pods still have the option to change the requests/limits through config.

We have had some discussion on if we should have limits, just memory limits, or no limits. Also if the limits should be the same as the requests or a bit higher. I'll leave that decision as a discussion point while doing this task.

**Describe alternatives you've considered**
Just add resource requests where it is missing (i.e. skip updating existing ones)
Ignore this and let some pods run without request/limits.

**Additional context**

**Definition of done:**
- All pods have sane default requests/limits
- A decision regarding limits is taken, recorded, and implemented.

**Comment by crssnd** [comment]
this seems to be related to #580 in ck8s
@viktor-f  let's discuss more on this

**Comment by viktor-f** [comment]
I assume you mean https://github.com/elastisys/ck8s/issues/580, in that case yes. I added a comment there as well.
