### ISSUE TITLE
kube-prometheus-stack - make upgrading the upstream chart easier

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#547]
**Describe the bug**
Many of the default Prometheus rules that come with the kube-prometheus-stack chart are not installed on the cluster. This breaks a series of grafana dashboards (mainly Kubernetes and USE method).

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup a ck8s cluter
2. Open a Kubernetes dashboard ( eg: Kubernetes/API server )
3. Open Prometheus and check is the rules used by the dashboard exist (eg: apiserver_request:availability30d)

**Expected behaviour**
All Kubernetes and USE Method dashboards work and show data 

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.17.0

**Additional context**
To fix the broken Grafana dashboard we need to upgrade the kube-prometheus-stack chart. That is covered by #664 
In this task we will focus on installing the default rules directly from the upstream chart not by using the prometheus-alerts chart.
This should make the upgrading of the upstream chart much easier.

**Comment by crssnd** [comment]
@robinelastisys what is the status if this ticket? I want to take it if still not solved.

**Comment by robinelastisys** [comment]
> @robinelastisys what is the status of this ticket? I want to take it if still not solved.

Sure, u can take it if u want!
