### ISSUE TITLE
Check immutable storage on SafeSpring for better protection of backups

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#559]
**What should be investigated.**

SafeSpring recently launched [immutable storage](https://www.safespring.com/whitepaper/immutable-storage/). As part of [ISO 27001, A.12.3.1 Information Backup](https://www.isms.online/iso-27001/annex-a-12-operations-security/), we should strengthen our security posture and leverage immutable storage for better protection of backups.

**What artifacts should this produce.**

* A demo that illustrates how to use immutable backups with CK8s and that credentials available to a CK8s environment cannot be used to erase or corrupt backups.
* A list of identified gaps.

**Comment by OlleLarsson** [comment]
@cristiklein how much do you want to know?
I quickly tested this 
I have tested this on safespring and the biggest difference is that with object logging enabled, versioning is (automatically) enabled as well. 

```
❯ aws s3api create-bucket --bucket olle-test-with-lock --object-lock-enabled-for-bucket --endpoint=https://s3.sto2.safedc.net

❯ aws s3api get-object-lock-configuration --bucket olle-test-with-lock  --endpoint=https://s3.sto2.safedc.net
{
    "ObjectLockConfiguration": {
        "ObjectLockEnabled": "Enabled"
    }
}

❯ aws s3api put-object-lock-configuration --bucket olle-test-with-lock --endpoint=https://s3.sto2.safedc.net --object-lock-configuration '{ "ObjectLockEnabled": "Enabled", "Rule": { "DefaultRetention": { "Mode": "COMPLIANCE", "Days": 2 }}}'

❯ aws s3api get-bucket-versioning  --bucket olle-test-with-lock  --endpoint=https://s3.sto2.safedc.net
{
    "Status": "Enabled",
    "MFADelete": "Disabled"
}

❯ aws s3api get-object-lock-configuration --bucket olle-test-with-lock  --endpoint=https://s3.sto2.safedc.net                                                            {
    "ObjectLockConfiguration": {
        "ObjectLockEnabled": "Enabled",
        "Rule": {
            "DefaultRetention": {
                "Mode": "COMPLIANCE",
                "Days": 2
            }
        }
    }
}

❯ aws s3api put-object --key test.txt --bucket olle-test-with-lock  --endpoint=https://s3.sto2.safedc.net
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "VersionId": "8iKMCSn4jJXjzN4H18NvRRoS3veUxF9"
}

❯ aws s3api list-objects --bucket olle-test-with-lock  --endpoint=https://s3.sto2.safedc.net
{
    "Contents": [
        {
            "Key": "test.txt",
            "LastModified": "2022-01-12T14:35:18.337000+00:00",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "findout-dev.elastisys.se",
                "ID": "4b2f3a10-2a83-4464-93d6-0b0f629314a1"
            }
        }
    ]
}

❯ aws s3api delete-object --key test.txt --bucket olle-test-with-lock  --endpoint=https://s3.sto2.safedc.net
{
    "DeleteMarker": true,
    "VersionId": "Vwfno.d3gPz.Yi0xIrossVkS46SGDH5"
}

# Can still fetch the delete marked object, assume that the version will be deleted after 2 days.
❯ aws s3api get-object --key test.txt --version-id 8iKMCSn4jJXjzN4H18NvRRoS3veUxF9 fetched.txt --bucket olle-test-with-lock  --endpoint=https://s3.sto2.safedc.net
{
    "AcceptRanges": "bytes",
    "LastModified": "2022-01-12T14:34:45+00:00",
    "ContentLength": 0,
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "VersionId": "8iKMCSn4jJXjzN4H18NvRRoS3veUxF9",
    "ContentType": "binary/octet-stream",
    "Metadata": {},
    "ObjectLockMode": "COMPLIANCE",
    "ObjectLockRetainUntilDate": "2022-01-14T14:34:45+00:00"
}

```

**Comment by cristiklein** [comment]
@OlleLarsson This looks great! Do I understand correctly that we could make this part of our onboarding process to add an additional layer of protection to our backups and long-term storage? I'm thinking ransomware attacks, where the attacker tries to corrupt backups. It's true that they would need to dig quite a few layers, but it would be nice to make corrupting backups from "almost impossible" to "actually impossible". :smile:

**Comment by OlleLarsson** [comment]
> @OlleLarsson This looks great! Do I understand correctly that we could make this part of our onboarding process to add an additional layer of protection to our backups and long-term storage? I'm thinking ransomware attacks, where the attacker tries to corrupt backups. It's true that they would need to dig quite a few layers, but it would be nice to make corrupting backups from "almost impossible" to "actually impossible". smile

Possibly. I would like to try using object locking buckets in an actual environment first.

**Comment by cristiklein** [comment]
@OlleLarsson Excellent!

**Comment by OlleLarsson** [comment]
I will close this one and open another for actually trying it out in an environment.
