### ISSUE TITLE
[13] Migrate from OpenDistro for ElasticSearch to OpenSearch

### ISSUE THREAD

**Issue by tordsson** [elastisys/compliantkubernetes-apps#588]
**Is your feature request related to a problem? Please describe.**
As a Compliant Kubernetes  Operator, I want to be able to install a ck8s cluster that uses OpenSearch instead of Open Distro for Elasticsearch for all log management.

**Describe the solution you'd like**
OpenSearch replacing OpenDistro 

**Additional context**
OpenDistro is a dead project. Updates,  security patches etc. are not be available.

OpenSearch now has an official helm chart: 
https://opensearch.org/docs/opensearch/install/helm/ 

**Definition of done:**
 OpenSearch installable and configurable for ck8s with corresponding Helm chart as the one used for OpenDistro.

**Comment by OlleLarsson** [comment]
Don't forget [OpenSearch Dashboards](https://opensearch.org/docs/dashboards/install/helm/) (Kibana) :D

**Comment by viktor-f** [comment]
Rough list of subtasks to complete (might need more)
- [ ] Try to install opensearch (no special config) with upstream helmchart
- [ ] Try to install opensearch dashboards (no special config) with upstream helmchart
- [ ] Configure opensearch and fluentd to send logs to opensearch
- [ ] investigate and implement configuration of opensearch (users, dashboard config)
- [ ] Fix metrics and alerts
- [ ] Test backup/restore
- [ ] Test and document migration from opendistro
