### ISSUE TITLE
[1] Create a user facing changelog

### ISSUE THREAD

**Issue by pettersv** [elastisys/compliantkubernetes-apps#590]
Create a customer-facing changelog, including all changes to kubernetes, or our apps that might affect customer apps. Communicate this well in advance to the customer so they have a chance to test/modify their apps.

* Add a WIP-USER-CHANGELOG.md to the apps repo and update the PR template to include this.

**Comment by viktor-f** [comment]
This is done https://compliantkubernetes.io/release-notes/
