### ISSUE TITLE
[8] Investigate migrating metrics to PostgreSQL / TimescaleDB

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#591]
**What should be investigated.**

We are increasingly unhappy with InfluxDB for metrics storage because:

- InfluxDB v1 is getting deprecated and InfluxDB v2 does not have all features we need yet.
- We don't want to sprawl skills and operate too many databases.
- InfluxDB is not community-driven.
- The open source version of InfluxDB is not HA.

Therefore, we want to find a new home for metrics. [TimescaleDB](https://docs.timescale.com/timescaledb/latest/) a layer on top of PostgreSQL feels like the most natural choice because:

- It is built on top of PostgreSQL and we already have good skills in PostgreSQL.
- We know how to set up PostgreSQL with HA, PITR, etc.

However, TimescaleDB seems to introduce a few new components, TimescaleDB and Promscale, which seem to introduce state and require special considerations to run in HA.

Before we can take a decision, a more thorough investigation is warranted.

**What artifacts should this produce.**

- A demo of running Compliant Kubernetes with InfluxDB replaced with TimescaleDB.
- A list of tasks (writing code, taking training, taking architectural decisions) that need to be performed for seeing TimescaleDB in production.

**Comment by lucianvlad** [comment]
Hello,
Results of the investigation are here:
https://docs.google.com/document/d/16M81LnhBY-X5c7QaUKWiVOEuEVBQDBDMQPrVMXZYiTI/edit?usp=sharing
The arch meeting discussion is here:
https://docs.google.com/presentation/d/17EEzfutwT3s92-4sbHfLLypRphFPHs2LOSftmPwzy1c/edit?usp=sharing

Regards
