### ISSUE TITLE
Update script shebang to allow user to define a custom bash

### ISSUE THREAD

**Issue by JonasKop** [elastisys/compliantkubernetes-apps#6]
When running the scripts the binary `/bin/bash` is used in some places. If the user wants to use another installed bash version (ex if there are multiple installed versions) it should be allowed so that the first bash executable in the users `$PATH` is used and not a hard coded one. This is a big problem if the user is running macOS, openBSD or some linux distros.

The scripts are also not consistent since some of them use `#!/bin/bash` and some `#!/usr/bin/env bash`.

Solution:
- Change all shebangs from `#!/bin/bash` to `#!/usr/bin/env bash`

Something like this would fix it: [COMMIT](https://github.com/elastisys/compliantkubernetes-apps/commit/b16f153ba4299a457c8331b06b70ea3b4f30d423)

**Comment by cristiklein** [comment]
Instead of making Compliant Kubernetes tooling more portable, we will package Compliant Kubernetes tools in a container image. This will have the nice side-effect that `/bin/bash` always exists.
