### ISSUE TITLE
Make curator delete indices based on name timestring instead of creation date

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#603]
**Is your feature request related to a problem? Please describe.**
We had this before we migrated to opendistro, see [this](https://github.com/elastisys/ck8s/pull/526/files) pr.
With the migration to opendistro I seem to have made a mistake and not include that change in the curator action config.

**Describe the solution you'd like**
Apply changes [here](https://github.com/elastisys/opendistro-build/commit/9ae1fbac51a81b4dd838fe2c2c9f33cec2d6a8a1#diff-52b31dc31f80a27245ea4d395fc885d2a831c171cc645df79112b0fb525e1ad6).

**Describe alternatives you've considered**
None.

**Additional context**
This ensures that old logs are removed before newer ones even if certain indices have been reindexed.

**Definition of done:**
Curator removes indices (age-wise) based on timestring instead of creation date.

**Comment by tordsson** [comment]
Wait until #588 is done
