### ISSUE TITLE
[3] Investigation: Move some compliantkubernetes-apps components to Kubernetes addons

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#61]
kubespray advocates using addons for certain "system" Pods. See full list [here](https://github.com/kubernetes-sigs/kubespray/tree/master/roles/kubernetes-apps).

This task consists in figuring out what is better to keep in compliantkubernetes-apps and what should be moved "down" into kubespray.

Acceptance criteria:

- The pros and cons of Kubernetes addons vs. Helm Charts is known.
- We have a list of candidate components to move as Kubernetes addons.

**Comment by Pradyumnakashyap** [comment]
With the limited time in this sprint , I have come up with some pros and cons of replacing the application charts with the addons (for a few applications) - https://docs.google.com/document/d/1zy4pwOzlSh10R-tnLHlS3CtfVwINktLl9lkota4Z5wY/edit?usp=sharing
