### ISSUE TITLE
[5] Investigate namespace creation aaS: hierarchical namespaces

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#613]
**What should be investigated.**
What technology/product/concept should be investigated?

We might want to give our customers the ability to create namespaces themselves, without giving them access to the whole cluster. This is very difficult (impossible?) to do with just RBAC so we will need some other tool.

Try adding [hierarchical namespaces](https://github.com/kubernetes-sigs/hierarchical-namespaces) to solve this problem and try it as a user. 

We would like answers to the following:
- Is it possible to install in compliant kubernetes?
- Does installing it produce any security concerns or other problems?
- Does it solve the problem for our users?
- Is it lacking any features and if so, how important are those features?

**What artifacts should this produce.**
- The answers to the questions above should be documented.
- The artifacts used to install it should be saved for potential future implementation.
- The results should be discussed with the team and a decision should be made to either move forward with adding this to compliant kubernetes or investigate other alternatives. Follow up issues should be created based on the decision.

**Comment by cristiklein** [comment]
The HNC moved to its own repo: https://github.com/kubernetes-sigs/hierarchical-namespaces

Currently it is at v0.8, with plans to release a v1.0 "Likely late Q2 or early Q3 2021: HNC recommended for production use."

We decided to wait for HNC to be production-ready before working on self-service namespaces.

Until then, let us document a snippet that allows the Compliant Kubernetes administrator to quickly create namespaces. Next person tasked to create a namespace will also document how to do it.

**Comment by viktor-f** [comment]
I rewrote the issue to focus on testing hierarchical namespaces for now, if that is not the right fit for us then we can try other options.

**Comment by viktor-f** [comment]
Investigation doc: https://github.com/elastisys/ck8s-ops/blob/main/docs/investigations/hierarchical-namespaces.md (private repo).

Conclusions:
HNC seems rather straight forward to add to compliant kubernetes, even though we will have to make our own helm chart. I do not think HNC creates any security issues for us (it does have a lot of RBAC permissions, but that can be locked down). Maybe most importantly HNC solves the problem of letting users create their own namespaces without escalating their privileges in the cluster.

On the negative side I miss some things related to monitoring (alerts, grafana dashboards and service monitor), but that should be easy for us to fix (and maybe upstream). More importantly I'm slightly unsure of the velocity/stability of the project. It is still a rather young project, I'm unsure how many actually use it, and it seems like it is maintained by a rather small group of people. Although it is an official kubernetes project, which is very positive.

As a final conclusion I think that this is a good enough project for us to add to compliant kubernetes and I do not think that we need to do any deep investigations of other alternatives for now.

**Comment by cristiklein** [comment]
Somewhat late to the party. Nice investigation @viktor-f !
