### ISSUE TITLE
Investigate using AlertmanagerConfig for user alerts

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#621]
**What should be investigated.**

We currently allow users to configure AlertManager via a Secret. User experience might be improved by using [AlertmanagerConfig](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md) instead. Let us investigate the benefits, downsides and potential migration path to AlertmanagerConfig.

**What artifacts should this produce.**

* A demo showing how to use AlertmanagerConfig. The demo should also show if RBACs can be used to sufficiently protect Alertmanager, so that even a big user misconfiguration does not affect administrator's ability to receive alerts.
* A list of steps -- including actions required from the user and documentation updates -- that are necessary to migrate to AlertmanagerConfig.

**Comment by Pavan-Gunda** [comment]
An initial investigation on this revealed that this custom resource is namespaced and therefore we can create appropriate roles for a ck8s user to only configure alertmanager in his namespace. I wrote a bit more [here](https://docs.google.com/document/d/196MAcfWXZLCu4HwL_pFhRjgy84-usO1-VxJEsXPc9uU/edit)

**Comment by cristiklein** [comment]
Thanks @Pavan-Gunda . Feel free to insert the results of the investigation in this ticket.

I'm not sure to have understood the following: Is `AlertmanagerConfig` only picked up by the Alertmanager running in the same namespace? Otherwise put, would the user be able to interfere with operator-owned AlertManager and Prometheus in any way?
