### ISSUE TITLE
blackbox - apiserver health check fails

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#622]
**Describe the bug**
The blackbox check https://kube-apiserver.example.com:/healthz fails because it returns 200 and not 401.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any cluster Promethues alerts and check the EndpointDown alert

**Expected behaviour**
This should not fail if the endpoint is up and running.

**Version (add all relevant versions):**
 - v0.17.0

**Comment by OlleLarsson** [comment]
In my own environment this happens were an OK status is returned. For some reason the basic auth seems to be out of play.
In other environments v0.18.2 it works as expected and returns unatorized.

**Comment by OlleLarsson** [comment]
I had had just messed up DNS.
@crssnd could it be the same for you?
