### ISSUE TITLE
Elasticsearch does not start properly on citycloud with encrypted disks

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#628]
**Describe the bug**
When using encrypted disks on citycloud, the pods take a lot longer time to start. This seems to be a problem for elasticsearch who will not start up properly and you then seem to have to run the security admin script to fix it.

```bash
kubectl exec opendistro-es-master-0 -it -n elastic-system -- /bin/bash

chmod +x ./plugins/opendistro_security/tools/securityadmin.sh
./plugins/opendistro_security/tools/securityadmin.sh \
    -cd plugins/opendistro_security/securityconfig \
    -icl -nhnv \
    -cacert config/admin-root-ca.pem \
    -cert config/admin-crt.pem \
    -key config/admin-key.pem
```

**To Reproduce**
1. Start cluster on citycloud with encrypted disks
2. Install ck8s-apps
3. Notice that elasticsearch does not start properly by looking at the logs of any ES pods or the configurer job.
4. Run SecurityAdmin script and rerun configurer to see that it now works.

**Expected behavior**
We should not have to do any manual intervention to make elasticsearch start properly.

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.17

**Additional context**

**Comment by viktor-f** [comment]
It would be nice to solve this upsteam if possible.

**Comment by Xartos** [comment]
We don't run encrypted disks on citycloud anymore
