### ISSUE TITLE
namespace not found when deploying workload-cluster-np

### ISSUE THREAD

**Issue by DutchEllie** [elastisys/compliantkubernetes-apps#630]
**Describe the bug**
Ever since the commit of 025743ac30e6942835935277c4582433d515090a the deployment is failing. When following the instructions in the Administrator Manual for AWS on [kubernetes.io ](kubernetes.io), when running ```./bin/ck8s apply wc``` the newly added release ```workload-cluster-np``` fails and crashes the entire deployment. The following error is displayed:
```
FAILED RELEASES:
NAME
workload-cluster-np
in ./00-psp_rbac_np.yaml: failed processing release workload-cluster-np: command "/usr/local/bin/helm" exited with non-zero status:

PATH:
  /usr/local/bin/helm

ARGS:
  0: helm (4 bytes)
  1: upgrade (7 bytes)
  2: --install (9 bytes)
  3: --reset-values (14 bytes)
  4: workload-cluster-np (19 bytes)
  5: charts/networkpolicy (20 bytes)
  6: --version (9 bytes)
  7: 0.1.0 (5 bytes)
  8: --timeout (9 bytes)
  9: 600s (4 bytes)
  10: --create-namespace (18 bytes)
  11: --namespace (11 bytes)
  12: kube-system (11 bytes)
  13: --values (8 bytes)
  14: /tmp/helmfile802080186/kube-system-workload-cluster-np-values-6988f787b7 (72 bytes)
  15: --history-max (13 bytes)
  16: 10 (2 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: namespaces "demo3" not found

COMBINED OUTPUT:
  Release "workload-cluster-np" does not exist. Installing it now.
  Error: namespaces "demo3" not found
exit status 1
```

I am not sure how to fix this issue, but it is clear as day this doesn't work at all. I'm sure this was either not tested or the tests are not working properly before getting this in main.

**To Reproduce**
1. Follow the instructions for deploying CK8S on AWS in the Administrator Manual.
2. See problem when running ```./bin/ck8s apply wc```

**Expected behavior**
It should succeed and deploy without issues.

**Version (add all relevant versions):**
 - Compliant kubernetes apps: git branch main

**Comment by aarnq** [comment]
Thanks for catching this one as well @DutchEllie, it was an dependency issue of the new network policies being applied before the namespaces were created.
