### ISSUE TITLE
Look through all current versions of apps and suggest upgrades

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#649]
We should look through the versions we are using now of all apps and figure out if we should upgrade to the latest version or if it can wait.

Create issues for the ones that we should upgrade and document the process/findings.

**Comment by aarnq** [comment]
I've created new separate issues and an epic for prioritized upgrades in preparation K8s v1.22, the rest of the recommendations are in a separate issue.
