### ISSUE TITLE
[2] Upgrade to kubernetes v1.19

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#66]
With 1.20 coming up we should support 1.19

Maybe we already do. So this task will be to investigate what needs to be changed to support 1.19 and create new issues if there are any bigger changes that is needed.

Relevant info:
https://kubernetes.io/docs/setup/release/notes/
(might be this link when 1.20 is released) https://v1-19.docs.kubernetes.io/docs/setup/release/notes/

# Acceptance criteria

* Test to deploy onto a kubernetes 1.19 cluster
* Fix the things that doesn't work
* Create issues if there are any bigger changes needed

**Comment by ewnetu** [comment]
Deployed and tested apps. Nothing breaks!
