### ISSUE TITLE
[2] Upgrade gatekeeper to v3.6.0

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#663]
**What Chart should be upgraded?**
upstream / gatekeeper: [gatekeeper/gatekeeper](https://github.com/open-policy-agent/gatekeeper/tree/master/charts/gatekeeper)
v3.3.0 (2021/01/28) -> v3.6.0 (2021/08/31)

**Why should this Chart be upgraded?**

- [ ] We need to perform a security upgrade.
- [ ] We need it for a new feature: *which feature (link to blocked issue)*.
- [x] We need to keep up to prevent future issues.
- [ ] Other: *Write the reason here*

Need to upgrade this to support K8s v1.22 going forward.

Introduces many new features and fixes.

**Acceptance criteria**

- I checked the migration of the new Chart:
    - [ ] I upgraded a Chart and determined that no migration steps are needed.
    - [ ] I upgraded a Chart and added [migration steps](https://github.com/elastisys/compliantkubernetes-apps/blob/main/migration).
- [ ] I tested the functionality provided by the new Chart (e.g., Auth flow, Grafana dashboards, etc.)

**Comment by OlleLarsson** [comment]
I upgraded to latest 3.7.0
