### ISSUE TITLE
Update user-alertmanager ingress version

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#667]
**Is your feature request related to a problem? Please describe.**
~~User-alertmanager uses a deprecated API version of ingress, and this should be updated to be compatible with K8s v1.22.~~

**Describe the solution you'd like**
~~User-alertmanager updated to new ingress API version.~~

**Describe alternatives you've considered**
Drop support for ingress if we don't want/feel the need to offer that feature on user-alertmanager.
This is already an issue: #639

**Definition of done:**
~~User-alertmanager has an updated ingress API version.~~

**Comment by aarnq** [comment]
Also can't this chart be moved out of `examples/`?

**Comment by OlleLarsson** [comment]
We will remove the ingress for alertmanager-

**Comment by OlleLarsson** [comment]
> Also can't this chart be moved out of `examples/`?

Yes :)

**Comment by aarnq** [comment]
OK, I'll update it.
