### ISSUE TITLE
Rename nginx release

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#67]
It appears as if we did not change the name of the relase when we moved to the new nginx helm chart.
I am all for making the change from `nginx-ingress` to `ingress-nginx`, so basically replace everything in the release specification: https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/01-applications.yaml#L48-L58

Cause right now we get these ugly names of `nginx-ingress-ingress-nginx...`

**Comment by danielharr** [comment]
Sounds good :slightly_smiling_face:
