### ISSUE TITLE
Split falco alerts into individual alerts for each event

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#671]
**Is your feature request related to a problem? Please describe.**
Currently we get all falco alerts in one big alert via alertmanager. This makes it harder to view and manage.

**Describe the solution you'd like**
Split the alerts into individual falco events. I'm not sure if this is to be changed/implemented in alertmanager or falco.

**Describe alternatives you've considered**
Leave it as it is.

**Additional context**

**Definition of done:**
Alerts from falco that go through alertmanager contain only a single falco event, not multiple.

**Comment by Xartos** [comment]
Done with changes to alertmanager group_by
