### ISSUE TITLE
Replace deprecated stable/elasticsearch-exporter helm chart

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#68]
It seems as if the stable/elasticsearch-exporter helm chart does not have a new home
I think it make sense to tackle this issue by bundling it in the opendistro helm chart, and I am also slightly positive that this is somehting that we can upstream.

WIP - need to add action points

**Comment by Ajarmar** [comment]
Changed title since elasticsearch-exporter was moved to the [prometheus-community repo](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-elasticsearch-exporter), so the old deprecated chart should just be updated rather than bundling it into the opendistro chart.
