### ISSUE TITLE
[1] Enable dex persistence

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#680]
**Describe the bug**

When dex is restarted, you'll need to manually delete the cached tokens for stuff.

**To Reproduce**

1. Log in to kubernetes with dex
2. Delete the dex pod
3. try to access kubernetes again and it will fail.

**Expected behavior**

Dex sessions should persist through restarts

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.18.0

**Additional context**

**Comment by OlleLarsson** [comment]
Revisit [ADR-0012](https://elastisys.io/compliantkubernetes/adr/0012-do-not-persist-dex/) @cristiklein?

**Comment by cristiklein** [comment]
I'm confused. When I tried it out it worked, i.e., once the JWT token was issued restating Dex was fine. (See [negative consequences in ADR-0012](https://elastisys.io/compliantkubernetes/adr/0012-do-not-persist-dex/#negative-consequences)). Have I missed something (e.g. JWKS rotation)?

**Comment by Xartos** [comment]
Don't really know, but often after an master reboot, or dex upgrade you get this, "Unauthorized" in kubectl. But deleting the cached jwt token resolves the issue.
It's not uncommon that we get these kind of service tickets from customers saying that they can't access the cluster after the first node reboot.

**Comment by cristiklein** [comment]
Folks, you are right, we need to supersede [ADR-0012](https://elastisys.io/compliantkubernetes/adr/0012-do-not-persist-dex/). Seems like Dex "loses" the keys when restarted, which leads to the user being forced to eventually re-log in. I say here "eventually" since it really depends on when the WC apiserver chooses to refresh the Dex keys.

Since we want to both frequently reboot Nodes (as required for security patching) and we want good developer experience, we need to persist Dex. I'll draft an ADR which supersedes ADR-0012. 

Here is the experiment to reproduce the issue:

```console
$ curl https://dex.$DOMAIN/.well-known/openid-configuration > before-openid-configuration.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1092  100  1092    0     0   9254      0 --:--:-- --:--:-- --:--:--  9176
$ curl https://dex.$DOMAIN/keys > before-keys.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2553  100  2553    0     0  23638      0 --:--:-- --:--:-- --:--:-- 23859

$ kubectl delete pods -n dex -l app.kubernetes.io/instance=dex

$ curl https://dex.$DOMAIN/.well-known/openid-configuration > after-openid-configuration.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1092  100  1092    0     0   9413      0 --:--:-- --:--:-- --:--:--  9413
$ curl https://dex.$DOMAIN/keys > after-keys.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   525  100   525    0     0   4525      0 --:--:-- --:--:-- --:--:--  4525

$ diff -y before-openid-configuration.json after-openid-configuration.json 
[empty output, no differences]

$ diff -y before-keys.json after-keys.json 
[all keys are replaced]
```
