### ISSUE TITLE
[5] Upgrade - change the upgrade and migration process

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#682]
**What should be investigated.**
Automate the upgrade process by creating scripts instead of code snippets to be run manually.
Separate the init and config steps from the apply steps and scripts as the CD solution should only run the apply steps and scripts.

**Addition**
All steps that affect the cluster should be scripts.
There should exist a script `upgrade-apps.sh` part of the migration path folder that runs all steps affecting the cluster. 
Example:
Delete deployment sets
Directly updating config maps
Apply sc/wc

**Definition of done:**
1. a process on how and who should create this migration scripts, separated config and apply scripts
2. Separate config migration scripts and cluster changes scripts into two folders.
3. There exists a script `upgrade-apps.sh` to run all cluster changes scripts.
4. ~create templates for the migration scripts that can be reused for the main or patch releases~
5. ~template migration scripts for how to change yaml config in apps~
6. ~add the test steps in a script to run before and after the upgrade~

**Comment by cristiklein** [comment]
Folks, I upgraded the demo environment to v0.19.0. I feel the migration scripts are going in the right direction.

I have the following suggestions on how to move forward.

1. Number the scripts in the order in which an administrator is expected to run them, e.g., `10_migrate_to_opensearch.sh`.
2. Put the instructions as comment (or strings) as the start of each migration scripts. Then the "main" migration script could be as simple as `for $SCRIPT in [0-9][0-9]*.sh; do ./$SCRIPT; done`.

My 2 cents.
