### ISSUE TITLE
kube-prometheus-stack - cluster label for sc is not applied to all metrics

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#684]
**Describe the bug**
Not all metrics coming from the sc have the cluster label set. e.g blackbox-exporter, calico-accountant, calico-felix-metrics, ingress-nginx. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Grafana
2. Open the Kubernetes / Compute Resources / Cluster dashboard
3. Check the Headlines. you will see that for some panels there is not data for sc

**Expected behaviour**
All sc metrics to contain the cluster label.

**Screenshots**
![image](https://user-images.githubusercontent.com/77267293/141957518-65b67c8c-74f4-4850-86d2-d4bfe6976ab9.png)

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.17.0

**Additional context**
The easiest way to do this would be setting the externalLabels for sc as we do in wc, but we will not see this label when we query the sc prometheus directly.

**Definition of done**
- all sc metrics have the cluster label set

**Comment by Xartos** [comment]
This is fixed in 0.20.0 (and 0.19 if you use thanos)
