### ISSUE TITLE
Make indices.query.bool.max_clause_count configurable

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#690]
**Is your feature request related to a problem? Please describe.**
By default, when free text searching, all fields are searched through.
If there are more then 1024 fields, query shard exceptions will rise.
You can change the default query field from `*` to something else, but then again that might not fit the customer in all situations.

**Describe the solution you'd like**
`indices.query.bool.max_clause_count` is made configurable.

**Describe alternatives you've considered**
Not allowing to increase the limit.

**Additional context**
Increasing  the limit will increase the load on elasticsearch.

**Definition of done:**
`indices.query.bool.max_clause_count` is configurable.

**Comment by cristiklein** [comment]
We decided to move this to re-evaluate for the following reasons:

- We really need to do this after we migrate to OpenSearch. We will re-evaluate once that is done.
- Having more than 1024 fields might be an indicator of a greater problem, and we might actually do our users a disservice to simply bump this limit without better understanding the underlying cause.
- We are working on educating our users how to enable structured logging, which we expect to both help us scale operations and help our users get the most "bangs for the bucks": https://elastisys.io/compliantkubernetes/getting-started/#prepare-your-application

**Comment by Xartos** [comment]
@OlleLarsson @aarnq Is this issue still relevant now with opensearch?

**Comment by aarnq** [comment]
> @OlleLarsson @aarnq Is this issue still relevant now with opensearch?

Yes, the same limit applies to OpenSearch.
