### ISSUE TITLE
What are the risks with exposing Prometheus to users?

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#691]
**What should be investigated.**

Lens integration can be improved by exposing Prometheus to the user. What are the risks of doing this? How can these risks be mitigated?

**What artifacts should this produce.**

* How can we hide the `remote_write` password in the Prometheus UI?
* A list of risks and path to mitigation. When evaluating risks, please start from our [General Principle](https://elastisys.io/compliantkubernetes/user-guide/demarcation/#general-principle)

**Comment by OlleLarsson** [comment]
They now have access to it
https://github.com/elastisys/compliantkubernetes-apps/pull/1163
