### ISSUE TITLE
kibana - error when downloading a csv report

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#692]
**Describe the bug**
When a user tries to download a csv report it gets and "Download error"
`{"type":"log","@timestamp":"2021-11-25T12:41:14Z","tags":["error","plugins","opendistroReportsKibana"],"pid":1,"message":"TypeError: Cannot read property 'settings' of undefined\n    at getMaxResultSize (/usr/share/kibana/plugins/opendistroReportsKibana/server/routes/utils/savedSearchReportHelper.ts:163:35)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}`

**To Reproduce**
Steps to reproduce the behaviour:
1. login to kibana
2. search for some logs and save that search
3. try to download the csv report

**Expected behaviour**
An user should be able to generate and download a csv report.

**Screenshots**
![image](https://user-images.githubusercontent.com/77267293/143468231-5115ef1f-d6c5-4807-bb66-f03e7b363982.png)

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.17.0

**Definition of Done**
An user being able to generate and download a csv report.

**Comment by crssnd** [comment]
depends on https://github.com/elastisys/compliantkubernetes-apps/issues/588

**Comment by Xartos** [comment]
Seems to be working at least in `v0.18.2`
