### ISSUE TITLE
Make it possible to have one index per namespace

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#693]
**Is your feature request related to a problem? Please describe.**

Currently, all application logs end up in the same Elasticsearch index pattern `kubernetes*`, e.g., `kubernetes-default-2021.11.25-000010`.

In certain environments, it is desirable to have one index per namespace. This brings the following short-term benefits:

- Less index mapping issues: Each application team can have their own fields convention, without causing index mapping headaches.

This also opens up the path to long-term benefits, including:

- Per-namespace retention, e.g., via separate curator jobs.
- Access control to logs, e.g., `team1` -- identified via OpenID group -- can only see logs in `demo1`.

**Describe the solution you'd like**

- A configuration flag that enables per-namespace indexes.

**Describe alternatives you've considered**

- Not offering this feature, but customers seem to really want it and it seems to open up quite some benefits..

**Additional context**

**Definition of done:**

- I can configure Compliant Kubernetes to write container logs to an index named based on the namespace in which the containers are running.
- A screenshot is available (in this issue) showing that the `user-demo` (NodeJS) deployed in `demo1` and `user-demo-dotnet` (.NET) deployed in `demo2` write logs to separate indices.

**Comment by cristiklein** [comment]
Implementation hint:

This *might* be as simple as replacing in [`fluentd-wc.yaml`](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/fluentd-wc.yaml.gotmpl#L323)

```
index_name kubernetes
```

with something like:

```
target_index_key @target_index
index_name fallback
```

(Gated by some Go template configuration, of course.)

We plan to roll this out as an optional feature. If the feature gets accepted, we eventually roll it out to all environments.

Otherwise, we rollback. If needed ,we can use [elasticsearch-dump](https://github.com/elasticsearch-dump/elasticsearch-dump) to copy the log entries in the per-namespace indices back to a single `kubernetes*` index.

**Comment by OlleLarsson** [comment]
Are we going for daily indices for each namespace?
If not the retention will not be rolling and we will just delete one index that contains let's say 7 days worth of logs.

**Comment by cristiklein** [comment]
> Are we going for daily indices for each namespace? If not the retention will not be rolling and we will just delete one index that contains let's say 7 days worth of logs.
> 
> Changing Fluentd is probably easy, but it's the entire setup in elasticsearch that IMO would be cumbersome and complex. If we want daily rolling indices/namespace we need to have some way of assinging kubernetes templates to these indicies. I would imagine that having Fluentd write to `some_prefix-namespace` makes it easier as we can then just have one template that targets `index_name: some_prefix*` (we can't use only use `*`).

I'm unsure to understand what is easier for us. `kubernetes-demo1-2021.11.25-000010`? I agree that fluentd is the easier part and that we need to make sure Elasticsearch/Curator is happy with the index pattern.

Please suggest an index template that would fulfill this requirement.

> 
> > Per-namespace retention, e.g., via separate curator jobs.
> 
> Not really sure about this. Like would an apply in wc also trigger a change in the sc config which then creates another curator cronjob? Or should we have the list of namespaces in the global config? Now that I think about it having shared namespaces config might solve the issue mentioned above as well.

Okay, let's drop this idea for now. Way too early.

**Comment by raviranjanelastisys** [comment]
[https://github.com/elastisys/ck8s-apps/issues/267](url)

**Comment by nlarzon** [comment]
I believe that in order to use dynamic index the `logstash_format` needs to be enabled and ´logstash_prefix` set to "${record['kubernetes']['namespace_name']}" this will override the `index_name`
Maybe this can be achieved within the gotemplate?

**Comment by OlleLarsson** [comment]
Using the dynamic elasticsearch output it works using placeholders
```yaml
    <match kubernetes.**>
      @type elasticsearch_dynamic
      ...
      logstash_format true
      logstash_prefix ${record['kubernetes']['namespace_name']}
      ...
    </match>
```
I haven't checked how much for resource intense the dynamic configuration is.

With this in mind Fluentd will need to have it's permissions increased in Elasticsearch.
```
cluster_permissions:
  - "cluster:monitor/main"
  - "indices:data/write/bulk"
index_permissions:
  - index_patterns:
    - "*"
    allowed_actions:
    - "indices:admin/create"
    - "index"
```

I would also say that using logstash format settings is preferred over trying to get ILM to work with dynamic indices. We loose rolling over based on size (and the rest of the features that it provides such as force merge), but that is a worthwhile sacrifice IMO.

I still haven't looked at how retention could be handled for this index/namespace feature.

**Comment by OlleLarsson** [comment]
For retention I will try and make it so that the curator configuration is made configurable with an arbitrary amount of index patterns. The customer that has this new feature enabled will have to provide us with the retention settings desired for the namespaces (needs to fit within the resource limitations of Elasticsearch of course).
