### ISSUE TITLE
[2] Enabled kured for automated node reboots

### ISSUE THREAD

**Issue by Pavan-Gunda** [elastisys/compliantkubernetes-apps#694]
**Is your feature request related to a problem? Please describe.**
Enable usage of Kured in compliant Kubernetes for automatic node reboots

**Describe the solution you'd like**
Add the Kured helm chart and set the default values of when to reboot the nodes to a desired time in default configs. 

**Definition of done:**
- added Kured helm chart to the upstream charts and enabling user to set values through sc and wc config. 
- enable metrics, add a Grafana dashboard
- create alerts for the relevant metrics (e.g. when kured was triggered)
- make `force-reboot` and `drainGracePeriod` (+ other relevant options) configurable via the common config
- keep `force-reboot: false` by default

**Comment by tordsson** [comment]
Did we not close the "automatic reboot" issue as well? If so, I would propose we close this one for now...

**Comment by viktor-f** [comment]
> Did we not close the "automatic reboot" issue as well? If so, I would propose we close this one for now...

This issue is to actually make this a part of ck8s-apps. So it is not done yet.
