### ISSUE TITLE
[5 each] Investigate alternative metrics databases

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#709]
**What should be investigated.**

We are still unhappy with our metrics database. We currently use InfluxDB v1 and TimescaleDB hasn't convinced us. Let's dig more before taking a decision.

Investigate **1 week** on each $candidate of:
- [ ]  [Cortex](https://github.com/cortexproject/cortex) [#717](https://github.com/elastisys/compliantkubernetes-apps/issues/717)  
- [x]  [Thanos](https://thanos.io/) [#718](https://github.com/elastisys/compliantkubernetes-apps/issues/718)
- [x]  [VictoriaMetrics](https://victoriametrics.com/) [#719](https://github.com/elastisys/compliantkubernetes-apps/issues/719)
- [ ]  [M3DB](https://m3db.io/) [#720](https://github.com/elastisys/compliantkubernetes-apps/issues/720)

and assess the following:

* Long-term “Health”
  * Governance; prefer in this order: CNCF project, community-driven, end-user-driven (e.g., Apple, Uber, Zalando)
  * License; prefer in this order: Apache 2.0, another open source license
  * Security patching history / policy
  * Popularity / adoption (GitHub contributors / commits / stars, who uses it?)
* MUST HAVEs:
  * Either Prometheus `remote_read` support or “direct” PromQL, so we can reuse Grafana dashboards
  * `remote_write` support
  * Compression, i.e., a lossless process to reduce storage space, at the expense of increased query latency
  * Aggregation, i.e., a lossy process to reduce storage space, at the expense of details. Aggregation can be done either by reducing time series sample rate or aggregating by label.
   * De-duplication, i.e., if two Prometheuses produce the same sample, one is discarded
* NICE TO HAVEs:
  * Comes with its own alert manager
* InfoSec questions:
  * How easy is it to configure **high availability**?
  * How easy is it to configure **backups** or **long-term archival to S3**?
  * How easy is it to perform **disaster recovery**?
  * How easy is it to perform **security patching**?
  * How easy is it to perform **upgrades**?
  * Can it be configure to be **tamper-proof**? I.e., the workload cluster cannot remove or override past metrics.
* Hands-on:
  * Actually replace InfluxDB with $candidate
* Implications:
  * What changes are necessary in Compliant Kubernetes, e.g., `helm install`?
  * What capacity is needed compared to InfluxDB?

**What artifacts should this produce.**

* A big Google Sheet with one row per candidate and all assessment criteria.
* A Google Presentation with one slide per candidate: pros, cons, and own thoughts for each solution.

**Comment by tordsson** [comment]
Closing this as sufficient investigation is done.
