### ISSUE TITLE
[1] velero - backup storage aws not found error

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#740]
**Describe the bug**
The Velero pods generate a lot of error:
```console
time="2022-01-11T13:11:54Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=gc-controller error="error getting backup storage location: BackupStorageLocation.velero.io \"aws\" not found" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/gc_controller.go:145" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*gcController).processQueueItem" key=velero/velero-daily-backup logSource="pkg/controller/generic_controller.go:140"
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to a cluster
2. And check the logs for the velero pod

**Expected behaviour**
Velero not to generate this error

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.18.2

**Additional context**
I think this problem was addressed in #557 

**Definition of Done**
- the error is not generated any-more

**Comment by Xartos** [comment]
Investigate if this issue is fixed with this one https://github.com/elastisys/compliantkubernetes-apps/pull/557
