### ISSUE TITLE
[3] Enable log-based alerts

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#747]
**Is your feature request related to a problem? Please describe.**

Now that the migration to OpenSearch is [almost complete:tm:](https://github.com/elastisys/compliantkubernetes-apps/issues/588), it's a good time to enable log-based alerting.

**Describe the solution you'd like**

The user can access the [alerting feature](https://opensearch.org/docs/latest/monitoring-plugins/alerting/index/) provided in OpenSearch.

**Describe alternatives you've considered**

* Not provide this feature to users.
* Enable it on a case-by-case bases without proper configuration management in CK8s.

**Definition of done:**

1. The risks of enabling log-based alerting is [well-understood](https://opensearch.org/docs/latest/monitoring-plugins/alerting/security/)
2. Log-based alerting is enabled by default.
3. Public documentation briefly describes log-based alerting, points to upstream documentation, and show how to perform log-based alerting with the user demo.

**Comment by raviranjanelastisys** [comment]
Draft Public Documentation for now - https://docs.google.com/document/d/1uTX3ReqLwgavtcIMp7-4SWCLuhcXLCl_qJGmC8C4ki4/edit?usp=sharing

Will open the PR soon in the repo - https://github.com/elastisys/compliantkubernetes

**Comment by raviranjanelastisys** [comment]
PR has been opened now - https://github.com/elastisys/compliantkubernetes/pull/316
