### ISSUE TITLE
Investigate what to do with deprecated stable/dex helm chart

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#75]
This chart is deprecated https://github.com/helm/charts/tree/master/stable/dex and it does not contain a link to a new home.

What to do?
- Fork and maintain it ourselves
- ...

**Comment by Xartos** [comment]
Relevant PR https://github.com/dexidp/dex/issues/1709

**Comment by sagikazarmark** [comment]
We are going to provide an official chart as soon as we can. Until then you can use our maintained fork: https://github.com/banzaicloud/banzai-charts/tree/master/dex

**Comment by anthr76** [comment]
the dex-shim image sadly doesn't have multi-arch support

**Comment by tordsson** [comment]
See https://github.com/dexidp/helm-charts

**Comment by tordsson** [comment]
Replaced by: https://github.com/elastisys/compliantkubernetes-apps/issues/274
