### ISSUE TITLE
[3] Safeguard: Do not allow 'latest'

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#763]
**Is your feature request related to a problem? Please describe.**

We have all kinds of safeguards in place, to ensure application developers don't compromise platform security and stability due to trivial mistakes. Currently, we place no restrictions regarding the image tag. This means that users can accidentally run Pods which the `latest` tag, which is a bad practice and can cause issue with change management.

**Describe the solution you'd like**

```yaml
opa:
  blockLatest:
    enforcement: deny  # default dryrun
```

Should trigger an error if a Deployment and/or Pod with the container image tag `latest` is created.

**Describe alternatives you've considered**

* Not implementing the present solution.
* Issuing recommendations via public docs

**Additional context**

* From the user's perspective, the feature should feel similar to [this safeguard](https://elastisys.io/compliantkubernetes/user-guide/safeguards/enforce-trusted-registries/)
* This [OPA policy](https://cloudsecops.com/block-latest-image-tag/) might be useful as a starting point.

**Definition of done:**

* Compliant Kubernetes supports the above configuration (please include a screenshot as evidence).
* Public docs are updated accordingly.

**Comment by viktor-f** [comment]
Remember to apply this for all containers (including init containers) for all types of resources that creates pods (pods, deployments, statefulsets, daemonsets, replicaset, cronjob, job). See [this policy](https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/charts/gatekeeper-templates/policies/image-registry.rego) for inspiration.

**Comment by raviranjanelastisys** [comment]
PR in progress - https://github.com/elastisys/compliantkubernetes-apps/pull/831

**Comment by raviranjanelastisys** [comment]
PR approved and merged . so closing it now .
