### ISSUE TITLE
[2] fluentd - add alerts and dashboard

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#781]
**Is your feature request related to a problem? Please describe.**
We would like to receive alerts when something is wrong with fluentd (e.g doesn't collect logs) and also see some stats in Grafana.

**Describe the solution you'd like**
- fluentd alerts
- fluentd grafana dashboard

**Describe alternatives you've considered**
Not have any.

**Definition of done:**
- have relevant fluent alerts
- have a Grafana dashboard with all the relevant information

**Comment by viktor-f** [comment]
We have some alerts in wc from the fluentd elastisearch helm chart. But that does not helpus in the ops alerts.
Look at this (or just copy) https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/upstream/fluentd-elasticsearch/templates/prometheusrule.yaml
