### ISSUE TITLE
Running init will add extra entries and comments under dex connectors

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#794]
**Describe the bug**
Running init will update the `secrets.yaml` file and add empty list entries and comments under `dex.connectors`.

**To Reproduce**
1. Run init
2. Edit secrets
3. Run init again
4. See changes in secrets

**Expected behavior**
The secrets file should not change if there are no updates.

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version main (2022-02-01)

**Additional context**
It might be that it only happens if you actually have connectors configured.

**Comment by OlleLarsson** [comment]
@aarnq solved by the move to yq4?
I have tried running init a few times and I do not encounter the described behavior.

**Comment by aarnq** [comment]
> @aarnq solved by the move to yq4? I have tried running init a few times and I do not encounter the described behavior.

I sure looks like it, I can't replicate it either. :+1:
