### ISSUE TITLE
Test cert-manager certificates

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#795]
**Is your feature request related to a problem? Please describe.**
We do not currently have any test for checking if cert-manager can successfully get certificates from Let's Encrypt. It has happened before that this functionality has been broken without anyone noticing.

**Describe the solution you'd like**
We should add test(s) to check that the certificates we request actually become ready.

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
We have tests that check all certificates.

**Comment by aarnq** [comment]
Should we close this in favour of https://github.com/elastisys/compliantkubernetes-apps/issues/1191?

**Comment by viktor-f** [comment]
Sounds good.
