### ISSUE TITLE
Go over and decide wich plugins to have installed in opensearch

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#801]
**What should be investigated.**
Go though all plugins in opensearch so we can decide which to keep.

**What artifacts should this produce.**
Pros and cons for all of the plugins, presented at an architecture meeting

**Comment by OlleLarsson** [comment]
I did a quick initial check and I would say that we can keep all of them except for the performance-analyzer.
It's a process that runs locally and collects performance metrics that can be vied in some PerfTop program.
There are some plugins that are available that customers need additional permissions for but I do think we can keep them installed.

Alerting and Monitoring:

- opensearch-alerting: OK, people are already using
- opensearch-reports-scheduler: OK, people are already using
- opensearch-anomaly-detection: OK to keep, people have no permissions yet, needs some additional permissions to store results on custom indices
- opensearch-performance-analyzer: Won’t use

Searching:
- opensearch-sql: Okay
- opensearch-asynchronous-search: Probably OK, I don't really see anyone needing this running our platform. This is used only via the API so they would have to issue API calls from the Dev tools page. They do not have permissions for this.
- opensearch-knn: Why machine learning!? I didn't read to carefully about this one but it looks to require a combination of API calls along with index settings to function and train models or whatever. I did not find any permission in the security plugin so I assume that everyone can use the knn api. I don't know if we should keep this around or not, it is not visible in any tab in opensearch. 

Replication:
- opensearch-cross-cluster-replication: Okay I would say, won't every be used by us.

Observability:
- opensearch-observability: Okay should require any additional permissions

Non negotiable:
- opensearch-index-management (OK)
- opensearch-job-scheduler (OK)
- opensearch-security (OK)
- repository-s3 (OK)

**Comment by OlleLarsson** [comment]
I guess my verdict after thinking about this a bit more is that unless we feel strongly about disabling some plugin I would just let upstream be upstream so to speak. Also I'm not a huge fan of the way to disable pluging using inti containers and copying files, see [how we did it with elasticsearch](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.18.0/helmfile/values/opendistro-es.yaml.gotmpl#L58-L105).
