### ISSUE TITLE
Fluentd json logging

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#809]
**Describe the bug**
I'm not sure if this is a bug or something else, but it seems like fluentd does not only log in json format.

We have this in the systems config
```
❯ k -n fluentd get cm fluentd-fluentd-elasticsearch -oyaml|grep -A 6  system.conf
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
      <log>
        format json
      </log>
    </system>
```

But you can see non json logs when looking

```
{"time":"2022-01-31 14:36:03 +0000","level":"warn","message":"dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error=\"400 - Rejected by Elasticsearch [error type]: mapper_parsing_exception [reason]: 'failed to parse field [keyValues.newToDate] of type [date] in document with id 'ZxyQsH4BKvTs0LJccfOE'. ...}
...
2022-01-31 14:36:03.688200120 +0000 fluent.warn: {"error":"#<Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError: 400 - Rejected by Elasticsearch [error type]: mapper_parsing_exception [reason]: 'failed to parse field [keyValues.newToDate] of type [date] in document with id 'ZxyQsH4BKvTs0LJccfOE'. ...}
```

**To Reproduce**
Install in any cluster.
Wait for some  error or warning.
Observe that there seems to be non json logs.

**Expected behavior**

**Screenshots**

**Version (add all relevant versions):**
 - Compliant kubernetes apps version 0.18.2

**Additional context**
Again, not sure if this is working as expected or if there is something strange happening.

**Comment by robinAwallace** [comment]
Closing this, look at the discussion in this issue: https://github.com/elastisys/compliantkubernetes-apps/pull/999.
