### ISSUE TITLE
[2] fluentd - 400 - Rejected by Elasticsearch

### ISSUE THREAD

**Issue by crssnd** [elastisys/compliantkubernetes-apps#811]
**Describe the bug**
fluentd generates 400 - Rejected by Elasticsearch errors:
- failed to parse field [source] of type [text] in document ... gatekeeper-controller-manager

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to kibana/opensearch
2. Filter after thr pod name fluentd
3. Search for `Rejected`
4. See error logs

**Expected behaviour**
No error

**Version (add all relevant versions):**
 - Compliant kubernetes apps version v0.19

**Definition of Done**
- error reason identified
- the error is fixed or mitigated

**Comment by robinAwallace** [comment]
I looked in Sartorius and Long-running environments, both on v0.19, and found no rejected errors from fluentd.

**Comment by robinAwallace** [comment]
I have looked at 3 separate v0.19 clusters and they were able to parse the JSON document and searchable. Moving this in stale for now.
