### ISSUE TITLE
Give user access to prometheus UI

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#819]
**Is your feature request related to a problem? Please describe.**
To allow users to themselves be able to confirm that prometheus picks up their servicemonitors we should give them access to the prometheus UI.
The reason as to why we have not done it previously is becuase of the fact that InfluxDB credentials were directly visible under the prometheus configuration tab.
This is no longer the case when we are running Thanos.

Releated: https://github.com/elastisys/compliantkubernetes-apps/issues/691

**Describe the solution you'd like**
Customers can port-forward to prometheus in the workload cluster.

**Describe alternatives you've considered**
Not giving them access.

**Additional context**

**Definition of done:**
Customers can port-forward to prometheus in the workload cluster.

**Comment by llarsson** [comment]
Related: #691
