### ISSUE TITLE
[1] Limit concurrent scans in starboard-operator and upgrade the helm chart

### ISSUE THREAD

**Issue by aarnq** [elastisys/compliantkubernetes-apps#830]
**Is your feature request related to a problem? Please describe.**
Starboard-operator by default can generate a lot of vulnerability scans. By default it run 10 concurrently, with a delay of 30 s on failure. This is _a lot_, and there has been instances where this have overwhelmed a control-plane node to reach OOM.

**Describe the solution you'd like**
We need to expose the options to limit the number of concurrent jobs starboard-operator can make, and increase the time between failures. This is not available in the v0.12.0 chart so we have to upgrade it.

**Describe alternatives you've considered**
Beef up the control-plane nodes.

**Definition of done:**
The number of concurrent jobs and the delay between failed ones can be configured for starboard operator.
Upgrade the helm chart to 0.14.1

**Comment by crssnd** [comment]
also check  https://github.com/elastisys/compliantkubernetes-apps/issues/585
