### ISSUE TITLE
[2] Allow allowlisting (pun intended) on SC endpoints

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#840]
**Is your feature request related to a problem? Please describe.**

Grafana and Kibana had some recent vulnerabilities. We can reduce blast radius and provide for a calmer vulnerability management process, by only allowing certain IP addresses to access SC endpoints, specifically:

```
dex.$DOMAIN
harbor.$DOMAIN
opensearch.$DOMAIN
grafana.$DOMAIN
opensearch.ops.$DOMAIN
thanos.ops.$DOMAIN
influxdb.ops.$DOMAIN  # to be deprecated
```

**Describe the solution you'd like**

This is just an example. Please decide on a suitable API.

```
# sc-config.yaml
endpointsAllowlist:
- 192.88.99.1/32
- 192.88.99.10/32
```

This adds the `nginx.ingress.kubernetes.io/whitelist-source-range` annotation on all SC endpoints.

**Describe alternatives you've considered**

* SecurityGroups on SC worker Nodes: Useless, since traffic usually comes from a LB via PROXY protocol.
* Firewall or application-level filtering on the LBs: This is extremely provider-specific. Not all LBs support all types of filtering.

**Additional context**

* Discussions on source IP preservation: https://elastisys.io/compliantkubernetes/user-guide/network-model/#ingress (search for "Some load-balancers fronting Compliant Kubernetes do not preserve source IP.")

**Definition of done:**

* As a Compliant Kubernetes administrator, I can configure IP allowlist on SC endpoints.
* Screenshot showing that traffic is allowed from allowlisted IPs and blocked from other IPs to all SC endpoints.

**Comment by Xartos** [comment]
Depends on https://github.com/elastisys/compliantkubernetes-apps/issues/841

**Comment by cristiklein** [comment]
@Xartos I don't see this issue depending on #841. We can have SC endpoint allowlisting both with HTTP01 (as today) and DNS01.
