### ISSUE TITLE
[2] Sketch a Welcome to Compliant Kubernetes dashboard!

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#851]
**Is your feature request related to a problem? Please describe.**

Let us help users be more productive with Compliant Kubernetes and point them to the most popular topics on our public docs.

**Describe the solution you'd like**

- An OpenSearch dashboard with a Markdown vizualization which welcomes the user to Compliant Kubernetes (see screenshot)
- The OpenSearch default route should point to this dashboard (see screenshot)
- **Update from retrospective 2022-03-24**: Please add the version number of various Compliant Kubernetes components.

**Describe alternatives you've considered**

- Plenty, and we do all in parallel. :smile:

**Additional context**

![image](https://user-images.githubusercontent.com/1660833/155563429-41d1a46e-659d-4632-8d6d-dbf662fd5b7f.png)
![image](https://user-images.githubusercontent.com/1660833/155563526-6be6547b-26cd-415a-9cf9-93a9d2223f39.png)
[welcome.md](https://github.com/elastisys/compliantkubernetes-apps/files/8134077/welcome.md)

**Definition of done:**

- Updating or installing a fresh Compliant Kubernetes gives the welcome dashboard and sets it as default route.
- It is easy to update the `welcome.md` file in future releases of Compliant Kubernetes.

**Comment by viktor-f** [comment]
Please add links to all other services (grafana, harbor, opensearch)
If possible, add a similar welcome page to grafana as well (if possible on the first page, otherwise in a dashboard).

**Comment by viktor-f** [comment]
Also add a note saying that users can get to see their cluster config (without secrets) if they ask for it.
