### ISSUE TITLE
Add pod restarts and reason to dashboard

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#852]
**Is your feature request related to a problem? Please describe.**

Long time ago we had pod restarts in the "compute resource / Pods" dashboard but not any more.
We would like to have that back. 

**Describe the solution you'd like**

Check if there's already new updates to the mixin-dashboards that already has this.
If not add the restarts and reason to the "compute resource / Pods"  and upstream.
If that's not possible or for some other reason not what we want, add a new dashboard that shows it.

**Describe alternatives you've considered**

Not adding it.

**Additional context**

**Definition of done:**
When could this feature be considered done.

* There's some way of seeing pod restarts and the reason for it in grafana

**Comment by crssnd** [comment]
I think we already have this added now

**Comment by Xartos** [comment]
Yes, should've been fixed by https://github.com/elastisys/compliantkubernetes-apps/pull/1467

Closing this
