### ISSUE TITLE
[0]Adding new repo - "quay.io/jetstack/cert-manager-acmesolver" to the safeguard

### ISSUE THREAD

**Issue by raviranjanelastisys** [elastisys/compliantkubernetes-apps#881]
**What should be investigated.**
Currently , We have safeguard policy to pull the images from the ONLY  allowed repository `harbor.$DOMAIN.com` but looks like  that user application in WC cluster  might need this repo -`quay.io/jetstack/cert-manager-acmesolver` as well to be also allowed to generate the certificates . - https://github.com/elastisys/compliantkubernetes-apps/blob/main/config/config/wc-config.yaml#L123-L126  

This new repo- `quay.io/jetstack/cert-manager-acmesolver` might be needed to be allowed by default , so user application certificates are generated successfully.

**What artifacts should this produce.**
It should be able to generate the certificates for the user applications running in wc cluster with `AllowedRepo` policy already enabled in safeguard. 
validate - `kubectl get certificates -n <user-app-namespace>`

**Comment by OlleLarsson** [comment]
https://github.com/elastisys/compliantkubernetes-apps/blob/main/config/config/wc-config.yaml#L123-L126

**Comment by crssnd** [comment]
@cristiklein can we discuss this issue in the next arch meeting?

**Comment by cristiklein** [comment]
@crssnd Sure, let's discuss it. I'm confused what is the issue. I was operating under the assumption that we decided to allowlist `quay.io/jetstack/cert-manager-acmesolver` when using the trusted repo safeguard.

**Comment by raviranjanelastisys** [comment]
Yeah looks like !! Because long-running deployed on the 0.19.1 latest available release and we did't have the allowed repo - `quay.io/jetstack/cert-manager-acmesolver` !! We can discuss more in the architecture meeting !!

**Comment by cristiklein** [comment]
At the arch meeting from 2022-03-10, we decided to make it default for `quay.io/jetstack/cert-manager-acmesolver` to be trusted.

**Comment by raviranjanelastisys** [comment]
PR - https://github.com/elastisys/compliantkubernetes-apps/pull/890
