### ISSUE TITLE
[3] Falco: Filter out "easy" alerts (1)

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#896]
**Is your feature request related to a problem? Please describe.**

We want to improve our security posture and intrusion detection is vital for this. Currently we run Falco in the workload cluster, however, it needs careful tuning to ensure good signal-to-noise ratio. Falco alerts should eventually become alert-worthy. :smile: 

This issue consists in filtering a few "obvious" false-positives.

**Describe the solution you'd like**

Some of these filters are valuable for the whole Falco community and should be **upstreamed**. Others are Compliant Kubernetes specific and should stay **local**.

1. "Contact K8S API Server From Container" should be ignored for container images which are known "controllers".

Specifically, please try to upstream a patch to [k8s_containers](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.19.1/helmfile/upstream/falco/rules/falco_rules.yaml#L2359)

```
quay.io/jetstack/cert-manager-cainjector
velero/velero
weaveworks/kured
ingress-controller/controller
quay.io/prometheus-operator/prometheus-operator
k8s.gcr.io/ingress-nginx/kube-webhook-certgen
quay.io/spotahome/redis-operator
registry.opensource.zalan.do/acid/postgres-operator
registry.opensource.zalan.do/acid/postgres-operator-ui
rabbitmqoperator/cluster-operator
```

Also, please add the following image locally to [user_known_contact_k8s_api_server_activities](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.19.1/helmfile/upstream/falco/rules/falco_rules.yaml#L2372).

```
elastisys/curl-jq
```

2. "DB program spawned process" should be ignored for wal-g running in the Zalando PostgreSQL operator.

Specifically, please upstream `sh -c envdir \"/run/etc/wal-e.d/env\" wal-g wal-push` to [`postgres_running_wal_e`](https://github.com/elastisys/compliantkubernetes-apps/blob/v0.19.1/helmfile/upstream/falco/rules/falco_rules.yaml#L1462). Make sure to use `and proc.cmdline startswith`.

**Describe alternatives you've considered**

* Filter out by namespace, but that feels like the wrong solution here.

**Additional context**

* [FalcoAlert Table (private)](https://docs.google.com/document/d/1OrH5OGf24Cik5XHD7Hd0eO4ieIamgDShBSp3vSD4xag/edit)
* [FalcoAlert Logs (private)](https://docs.google.com/document/d/1R7rG7_zgbVo8spDfPx8AJi4jCi-E3Kp6jWtPoimX1D0/edit#heading=h.i7iaon8ap2v8)
* [FalcoAlert Sheet (private)](https://docs.google.com/spreadsheets/d/1ybn4lxsd9vRkGR-D4H6zo_kWhdlq2oBrul_N56cdnJI/edit#gid=1451483292)

**Definition of done:**

1. Above rules which are to be upstreamed are upstreamed in Falco.
2. Above rules which are to be locally implemented are in Compliant Kubernetes's by default.
3. Compliant Kubernetes imports a Falco Chart with upstreamed rules.

**Comment by Xartos** [comment]
Dependent on https://github.com/elastisys/compliantkubernetes-apps/issues/889
