### ISSUE TITLE
[3] Falco: Investigate "hard" alerts

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#898]
**What should be investigated.**
Why do we get these alerts from Falco? Are they expected? Should we simply filter them? Or should we fix something?

1. This looks like snapd on the host activity. We don't really use snapd. Remove/tame snapd or filter alert?
```
Change thread namespace
{"output":"06:47:29.507412073: Notice Namespace change (setns) by unexpected program (user=root user_loginuid=-1 command=snap-update-ns lxd parent=snapd k8s.ns=<NA> k8s.pod=<NA> container=host container_id=host image=<NA>:<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host","priority":"Notice","rule":"Change thread namespace","time":"2022-03-04T06:47:29.507412073Z", "output_fields": {"container.id":"host","container.image.repository":null,"container.image.tag":null,"evt.time":1646376449507412073,"k8s.ns.name":null,"k8s.pod.name":null,"proc.cmdline":"snap-update-ns lxd","proc.pname":"snapd","user.loginuid":-1,"user.name":"root"}}
```

2. This looks like a [bug in Falco](https://github.com/falcosecurity/falco/issues/1550). Filter? Fix?

```
Non sudo setuid
{"output":"07:15:18.117099526: Notice Unexpected setuid call by non-sudo, non-root program (user=<NA> user_loginuid=-1 cur_uid=4294967295 parent=<NA> command=<NA> uid=root container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host","priority":"Notice","rule":"Non sudo setuid","time":"2022-03-07T07:15:18.117099526Z", "output_fields": {"container.id":"host","container.image.repository":null,"evt.arg.uid":"root","evt.time":1646637318117099526,"k8s.ns.name":null,"k8s.pod.name":null,"proc.cmdline":"<NA>","proc.pname":null,"user.loginuid":-1,"user.name":null,"user.uid":4294967295}}
```

3. No clue why falco seems to report itself.

```
System procs network activity
{"output":"09:35:53.150945964: Notice Known system binary sent/received network traffic (user=root user_loginuid=0 command=sh -c curl -d @- falcosidekick:2801/\n connection=10.233.96.3:35756->10.233.0.129:2801 container_id=19111ca43330 image=falcosecurity/falco) k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330 k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330 k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330 k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330","priority":"Notice","rule":"System procs network activity","time":"2022-02-26T09:35:53.150945964Z", "output_fields": {"container.id":"19111ca43330","container.image.repository":"falcosecurity/falco","evt.time":1645868153150945964,"fd.name":"10.233.96.3:35756->10.233.0.129:2801","k8s.ns.name":"falco","k8s.pod.name":"falco-2w7sr","proc.cmdline":"sh -c curl -d @- falcosidekick:2801/\n","user.loginuid":0,"user.name":"root"}}
```

**What artifacts should this produce.**

For each of the alerts above:

1. An explanation of what the alert means. What causes it? What risk does it indicate?
2. A recommendation: filter upstream, filter in Compliant Kubernetes or fix something in Compliant Kubernetes.

**Comment by Xartos** [comment]
Dependent on https://github.com/elastisys/compliantkubernetes-apps/issues/889

**Comment by raviranjanelastisys** [comment]
Based on the investigations @cristiklein 

**1.** The rule - `Change thread namespace` is not enabled by default in our compliant k8s apps and also  not enabled in the falco community . Also , we cannot fix the upstream as it will be subjective topic for falco community .

But in compliant k8s apps , we can enable this rule  & add the exceptions accordingly in our apps - Link to open PR - https://github.com/elastisys/compliantkubernetes-apps/pull/1057/files#diff-a0855c995ac3e268d05ab0716ef603704977925629d74feb42d46c4afc6db97cR232 

**2.** Regarding `Non sudo setuid` investigations  - I’ve been doing some research  and I found a couple of interesting details. The most relevant is that there are situations where events streams are dropped and that might be the reason why Falco doesn’t have all the available information from the event, like which command generated it, or the uid (which is actually a parameter of the syscall setuid in this case).

Also, in below log 

```
Non sudo setuid
{"output":"07:15:18.117099526: Notice Unexpected setuid call by non-sudo, non-root program (user=<NA> user_loginuid=-1 cur_uid=4294967295 parent=<NA> command=<NA> uid=root container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host","priority":"Notice","rule":"Non sudo setuid","time":"2022-03-07T07:15:18.117099526Z", "output_fields": {"container.id":"host","container.image.repository":null,"evt.arg.uid":"root","evt.time":1646637318117099526,"k8s.ns.name":null,"k8s.pod.name":null,"proc.cmdline":"<NA>","proc.pname":null,"user.loginuid":-1,"user.name":null,"user.uid":4294967295}}
``` 
That’s not an error, but rather an incomplete log from Falco), cur_uid (the user id of the process using that call) is 4294967295, which means that the user was running before AuditD was started. This could be used as a condition to filter out this kind of message.

So, to summarize, the reason why this log is not filtered is that the command and the uid information are missing, and therefore, Falco cannot apply the exception properly.

 **Conclusion** - It depends on how big the environment is where Falco is running & how much CPU/other resources are allocated to Falco or  anything else that could help  to customize the allocated resources so this issue doesn’t occur !! No action needed to fix the upstream falco rather  customize the allocated resources to our falco instances.

**3 .** Regarding `No clue why falco seems to report itself` investigations
```
System procs network activity
{"output":"09:35:53.150945964: Notice Known system binary sent/received network traffic (user=root user_loginuid=0 command=sh -c curl -d @- falcosidekick:2801/\n connection=10.233.96.3:35756->10.233.0.129:2801 container_id=19111ca43330 image=falcosecurity/falco) k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330 k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330 k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330 k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330","priority":"Notice","rule":"System procs network activity","time":"2022-02-26T09:35:53.150945964Z", "output_fields": {"container.id":"19111ca43330","container.image.repository":"falcosecurity/falco","evt.time":1645868153150945964,"fd.name":"10.233.96.3:35756->10.233.0.129:2801","k8s.ns.name":"falco","k8s.pod.name":"falco-2w7sr","proc.cmdline":"sh -c curl -d @- falcosidekick:2801/\n","user.loginuid":0,"user.name":"root"}}
```

**Conclusion** - Falco doesn’t assume you are going to use it together with Falco Sidekick and therefore that rule doesn’t have an exception for that out of the box. It’s safe to set an exception for it filtering by a tuple using: [container.image.repository, k8s.ns.name, and proc.cmdline]. Since Falco community won't add the exception as it is subjective topic and so I have opened the PR to fix this in our compliant kubernetes apps - https://github.com/elastisys/compliantkubernetes-apps/pull/1057/files#diff-a0855c995ac3e268d05ab0716ef603704977925629d74feb42d46c4afc6db97cR252

**Comment by raviranjanelastisys** [comment]
PR in progress - https://github.com/elastisys/compliantkubernetes-apps/pull/1057

**Comment by cristiklein** [comment]
> Based on the investigations @cristiklein
> 
> **1.** The rule - `Change thread namespace` is not enabled by default in our compliant k8s apps and also not enabled in the falco community . Also , we cannot fix the upstream as it will be subjective topic for falco community .
> 
> But in compliant k8s apps , we can enable this rule & add the exceptions accordingly in our apps - Link to open PR - https://github.com/elastisys/compliantkubernetes-apps/pull/1057/files#diff-a0855c995ac3e268d05ab0716ef603704977925629d74feb42d46c4afc6db97cR232

I'm a bit worried about why we have snapd running on the host to being with. I wouldn't expect this to be part of the Ubuntu Cloud Image. Also, I think it would be better -- from a security posture perspective -- to not have snapd on our Kubernetes Nodes. Could we double-check why we have snapd before adding the exception?

> 
> **2.** Regarding `Non sudo setuid` investigations - I’ve been doing some research and I found a couple of interesting details. The most relevant is that there are situations where events streams are dropped and that might be the reason why Falco doesn’t have all the available information from the event, like which command generated it, or the uid (which is actually a parameter of the syscall setuid in this case).
> 
> Also, in below log
> 
> ```
> Non sudo setuid
> {"output":"07:15:18.117099526: Notice Unexpected setuid call by non-sudo, non-root program (user=<NA> user_loginuid=-1 cur_uid=4294967295 parent=<NA> command=<NA> uid=root container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host","priority":"Notice","rule":"Non sudo setuid","time":"2022-03-07T07:15:18.117099526Z", "output_fields": {"container.id":"host","container.image.repository":null,"evt.arg.uid":"root","evt.time":1646637318117099526,"k8s.ns.name":null,"k8s.pod.name":null,"proc.cmdline":"<NA>","proc.pname":null,"user.loginuid":-1,"user.name":null,"user.uid":4294967295}}
> ```
> 
> That’s not an error, but rather an incomplete log from Falco), cur_uid (the user id of the process using that call) is 4294967295, which means that the user was running before AuditD was started. This could be used as a condition to filter out this kind of message.
> 
> So, to summarize, the reason why this log is not filtered is that the command and the uid information are missing, and therefore, Falco cannot apply the exception properly.
> 
> **Conclusion** - It depends on how big the environment is where Falco is running & how much CPU/other resources are allocated to Falco or anything else that could help to customize the allocated resources so this issue doesn’t occur !! No action needed to fix the upstream falco rather customize the allocated resources to our falco instances.

Agreed!

> 
> **3 .** Regarding `No clue why falco seems to report itself` investigations
> 
> ```
> System procs network activity
> {"output":"09:35:53.150945964: Notice Known system binary sent/received network traffic (user=root user_loginuid=0 command=sh -c curl -d @- falcosidekick:2801/\n connection=10.233.96.3:35756->10.233.0.129:2801 container_id=19111ca43330 image=falcosecurity/falco) k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330 k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330 k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330 k8s.ns=falco k8s.pod=falco-2w7sr container=19111ca43330","priority":"Notice","rule":"System procs network activity","time":"2022-02-26T09:35:53.150945964Z", "output_fields": {"container.id":"19111ca43330","container.image.repository":"falcosecurity/falco","evt.time":1645868153150945964,"fd.name":"10.233.96.3:35756->10.233.0.129:2801","k8s.ns.name":"falco","k8s.pod.name":"falco-2w7sr","proc.cmdline":"sh -c curl -d @- falcosidekick:2801/\n","user.loginuid":0,"user.name":"root"}}
> ```
> 
> **Conclusion** - Falco doesn’t assume you are going to use it together with Falco Sidekick and therefore that rule doesn’t have an exception for that out of the box. It’s safe to set an exception for it filtering by a tuple using: [container.image.repository, k8s.ns.name, and proc.cmdline]. Since Falco community won't add the exception as it is subjective topic and so I have opened the PR to fix this in our compliant kubernetes apps - https://github.com/elastisys/compliantkubernetes-apps/pull/1057/files#diff-a0855c995ac3e268d05ab0716ef603704977925629d74feb42d46c4afc6db97cR252

Agreed!
