### ISSUE TITLE
Cannot make Pie Chart for application-specific logging field

### ISSUE THREAD

**Issue by llarsson** [elastisys/compliantkubernetes-apps#910]
**Describe the bug**
As a user, I am trying to create a pie chart in OpenSearch Dashboards of an application-specific logging field. In this particular case, the "status-code" field that our [demo application](https://github.com/elastisys/compliantkubernetes/blob/main/user-demo/app.js#L20) outputs. 

But that is not possible, it seems.

Likely cause? It is not indexed. And due to my permission level, I am not allowed to create such an index myself, either.

**To Reproduce**
1. Go to https://opensearch.long-running.dev-ck8s.com/app/opensearch_dashboards_overview#/
2. Click on 'Dashboards'
3. Click on 'Create dashboard'
4. Click on 'Create new'
5. Click on 'Pie'
6. Click on 'kubernetes*'
7. On 'Buckets', click '+ Add' button
8. Click 'Split slices'
9. Choose 'Terms' for 'Aggregation'
10. See that you can't actually choose 'status-code' for the 'Field'

To see that it is not indexed, but present, you can go to the regular log viewer part, and choose the following filter: 'kubernetes.labels.app_kubernetes_io/name' set to 'ck8s-user-demo' and choose any of the entries.

**Expected behavior**

That I, as a user, could control which of my log fields would be possible to use as input for my dashboards and charts.

**Screenshots**
![image](https://user-images.githubusercontent.com/1425662/159485351-674de6c5-954c-4c7a-8fa7-1090562f40dc.png)

![image](https://user-images.githubusercontent.com/1425662/159485459-dcade357-49eb-4077-bf0a-98cd19997e61.png)

**Version (add all relevant versions):**
 - Whichever is currently deployed on the Long-Running Cluster at the time this bug is filed.

**Additional context**
N/A

**Comment by OlleLarsson** [comment]
We solved this by refreshing the index field list in Kibana/opensearch.
