### ISSUE TITLE
Reduce Starboard TTL to 24h

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#936]
**Is your feature request related to a problem? Please describe.**

As advised by [upstream](https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6917117851711475712/?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6917117851711475712%2C6917930599735312384%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A6917117851711475712%2C6918246424652464128%29&midToken=AQGkxThx1F3dYg&midSig=2LzLb_ozlhuqc1&trk=eml-email_notification_single_mentioned_you_in_this_01-notifications-1-hero%7Ecard%7Efeed&trkEmail=eml-email_notification_single_mentioned_you_in_this_01-notifications-1-hero%7Ecard%7Efeed-null-8unpw%7El1qp3drj%7Epz-null-voyagerOffline).

**Definition of done:**

- Starboard uses a TTL of 24h by default and in new environments.

**Comment by crssnd** [comment]
@cristiklein is this still relevant?
We are using Trivy-operator now and I wasn't able to open the above url.

**Comment by cristiklein** [comment]
@crssnd This issue can be closed. Thanks for noticing!
