### ISSUE TITLE
[3] Add falco in service cluster

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#949]
**Is your feature request related to a problem? Please describe.**
We currently do not run falco in the service cluster. We should add it there as well to increase our security.

**Describe the solution you'd like**
Add falco in the service cluster and update the rules with relevant exceptions for the other pods we run in the service cluster (so that we do not get spammed with unnecessary alerts). Since we don't really know how many more rules we would need to edit or how much time that would take we want this task to be time boxed to 3 days. If there are more rules that needs updates then those should be noted down in a new issue. Try to focus on the rules that are causing the most amount of alerts.

**Describe alternatives you've considered**

**Additional context**

**Definition of done:**
- Falco is running in the service cluster
- We get alerts from falco in the service cluster
- The falco rules are updated with relevant exceptions (preferably upstream as well).
- An issue is created with any rule updates that was not completed in the time for this task.

**Comment by raviranjanelastisys** [comment]
@cristiklein @lucianvlad Are we good to add these in SC cluster too then right ?

**Comment by cristiklein** [comment]
Yes, please. @raviranjanelastisys

**Comment by lucianvlad** [comment]
Yes. @raviranjanelastisys

**Comment by raviranjanelastisys** [comment]
Thanks for the confirmations !!
