### ISSUE TITLE
[3] What more is needed for zone redundancy?

### ISSUE THREAD

**Issue by cristiklein** [elastisys/compliantkubernetes-apps#962]
**What should be investigated.**

We want to run more clusters stretched across availability Zones, so as to tolerate a whole Zone failure. In contrast to stretched clusters on top of Rook/Ceph, the next clusters won't have a fully-stretched storage provider, i.e., PVCs are "locked" to a Zone.

Hence, to achieve tolerance to Zone failure, we might need to have:

- Deployments that self-heal sufficiently fast and/or have replicas 2 and zone spread.
- StatefulSets that have replicas 2 and zone spread.

Please test:

- Rolling reboot of Nodes -- as done during patching.
- Failing each Zone.

**What artifacts should this produce.**

* Please test zone failure in Compliant Kubernetes (both SC and WC) and determine how well do we tolerate Zone failures.
* Produce a list of tasks which needs to be completed to improve our posture when it comes to tolerating Zone failures.

**Comment by lucianvlad** [comment]
After we have figured what is needed to have cluster stretched across  AZ's,it would be nice to see tests done on:
1. cluster spread across 2 zones:
        - 1 zone has 2 masters and the other has 1 master, the worker nodes spread as even as possible
        - 2 replicas with zone spread for all critical components
        - test1 - failure of zone 1 that has only 1 master
        - test 2 - failure of zone 2 that has 2 masters --> this way we make sure there are no issues related to quorum
        - test 3 - rolling reboot of nodes
2. cluster spread across 3 zones:
        - each zone has 1 master
        - spread the worker nodes across all 3 zone as even as possible
        - 2 replicas with zone spread for all critical components
        - test1 - failure of zone 1
        - test 2 - failure of 2 zones --> this way we test failure of 2 zones and make sure there are no issues related to quorum
        - test 3 - rolling reboot of nodes
        - Consider adding 3 replicas with zone spread for all critical components and note the additional resources needed to accomplish that

**Comment by cristiklein** [comment]
Some comments from me:

> 1. cluster spread across 2 zones:

I'd skip this entirely. Either the cluster runs on a single Zone (and provides single Node failure tolerance) or 3 Zones (and provides single Zone failure tolerance). 2 Zones could provide some benefits, but it's really not the way Kubernetes is meant to be used.

> - test 2 - failure of 2 zones --> this way we test failure of 2 zones and make sure there are no issues related to quorum

Again, Kubernetes is not meant to tolerate 2 Zone failures, so I'd skip this test. However, all other tests in group "2. cluster spread across 3 zones" are very relevant.
