### ISSUE TITLE
[2] Sample roles for Harbor

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#97]
Create two sample role bindings, corresponding to typical access for a developer and admin.
These should then be mapped to OIDC group claims.

The specific names of the group claims that are mapped to roles in harbor should be configurable.

 Aceptance criteria:
- I can login in using my IDP (e.g. google) and either get developer access or admin access based on what roles I have in my IDP.

**Comment by geoff-elastisys** [comment]
Done - user can log in to harbor via OIDC and if their group claims match a group in a project they will have access to that project with the permissions for that group.

Demo:

log in to Harbor as Admin
Go to Default project
go to Members
Add group using name as it matches from OIDC provider and give group appropriate  permissions:
![image](https://user-images.githubusercontent.com/60650907/101653537-b4774c80-3a3f-11eb-869e-dd273e8dcc5d.png)
Note the group name matches group name from provider, in this case, okta
![image](https://user-images.githubusercontent.com/60650907/101653763-f86a5180-3a3f-11eb-9c34-ac2fd104613c.png)

Now logged in via dex as that user, we now are a guest in that project and only have guest permissions:
Example, cannot set anything in configurations.  See here https://goharbor.io/docs/1.10/administration/managing-users/ for more on harbor roles
