### ISSUE TITLE
Tolerate control-plane taint

### ISSUE THREAD

**Issue by Xartos** [elastisys/compliantkubernetes-apps#970]
For k8s 1.24 the `node-role.kubernetes.io/master:NoSchedule` taint will be replaced by `node-role.kubernetes.io/control-plane:NoSchedule`
They recommend to add this toleration in advance so there's no surprises when we upgrade to 1.24 

So lets add it to all components that have the current `master` taint

### Definition of done

* All deployments that are tolerate the `node-role.kubernetes.io/master:NoSchedule` taint should also tolerate the `node-role.kubernetes.io/control-plane:NoSchedule` taint

**Comment by viktor-f** [comment]
During v1.24 both `/master` and `/control-plane` taints will be added, so the apps need to tolerate both until v1.25.

But the `/master` label will be removed in v1.24. So if we have any node affinities or similar (I don't think we have that for control-plane nodes), they need to change.
