### ISSUE TITLE
[2] Sample roles for Kibana/elasticsearch

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#98]
Create two sample role bindings, corresponding to typical access for a developer and admin.
These should then be mapped to OIDC group claims.

The specific names of the group claims that are mapped to roles in harbor should be configurable.

 Aceptance criteria:
- I can login in using my IDP (e.g. google) and either get developer access or admin access based on what roles I have in my IDP.

**Comment by geoff-elastisys** [comment]
added extra role mappings to sc config.  When commented back in they map predefined roles to groups.
Demo:
log in as user belonging to admin group, we can see the roles associated to that group:

![image](https://user-images.githubusercontent.com/60650907/101788909-f1574800-3b00-11eb-86e2-9d7d5e629a21.png)

the mapping in sc_config:
    - mapping_name: all_access
      definition:
        backend_roles:
          - "kibana_admin"  

log in, this time as belonging to dev group:
![image](https://user-images.githubusercontent.com/60650907/101789213-4bf0a400-3b01-11eb-8013-dede39796d91.png)

and the mapping:
    - mapping_name: kibana_user
      definition:
        backend_roles:
          - "kibana_dev"
