### ISSUE TITLE
[2] Sample roles for grafana

### ISSUE THREAD

**Issue by viktor-f** [elastisys/compliantkubernetes-apps#99]
Create two sample role bindings, corresponding to typical access for a developer and admin.
These should then be mapped to OIDC group claims.

The specific names of the group claims that are mapped to roles in harbor should be configurable.

 Aceptance criteria:
- I can login in using my IDP (e.g. google) and either get developer access or admin access based on what roles I have in my IDP.

**Comment by geoff-elastisys** [comment]
Will make assumption that this story is referring to user grafana and will handle ops granfa in a different issue

**Comment by geoff-elastisys** [comment]
demo/test
sign in with dex:
![image](https://user-images.githubusercontent.com/60650907/101046198-23a4fa80-3581-11eb-9c55-2d5fe0657822.png)
redirect to okta (already signed in there)
![image](https://user-images.githubusercontent.com/60650907/101046335-3fa89c00-3581-11eb-89ab-be2183fd7c70.png)
logged in to grafana with editor role
![image](https://user-images.githubusercontent.com/60650907/101046531-65ce3c00-3581-11eb-8214-36cfc9912dee.png)
in Okta we can see that I'm part of a group call grafana_editor
![image](https://user-images.githubusercontent.com/60650907/101046876-a62dba00-3581-11eb-9261-05b7e52251bb.png)

That mapping from group to role is handled in helmfile/values/grafana-user.yaml.gotmpl
Code snippet: 
role_attribute_path: contains(groups[*], 'grafana_admin') && 'Admin' || contains(groups[*], 'grafana_editor') && 'Editor' || 'Viewer'

**Comment by viktor-f** [comment]
> Will make assumption that this story is referring to user grafana and will handle ops granfa in a different issue

Yes, this is only for user grafana. The ops grafana is not connected to dex.

**Comment by geoff-elastisys** [comment]
> > Will make assumption that this story is referring to user grafana and will handle ops granfa in a different issue
> 
> Yes, this is only for user grafana. The ops grafana is not connected to dex.

yep - should we connect it though? or ok at the moment as is?

**Comment by viktor-f** [comment]
> > > Will make assumption that this story is referring to user grafana and will handle ops granfa in a different issue
> > 
> > 
> > Yes, this is only for user grafana. The ops grafana is not connected to dex.
> 
> yep - should we connect it though? or ok at the moment as is?

Ok as is, see separate issue for adding second dex for operators.
