### ISSUE TITLE
Fluentd: Consider restructure fluentd gotmpl values

### ISSUE THREAD

**Issue by robinAwallace** [elastisys/compliantkubernetes-apps#990]
We should restructure fluentds gotmpl values to match the structure of opensearch. 

This means that all fluentds gotmpl files should be located in a directory called `fluentd`.
`values/fluentd/fluentd-configmap.yaml.gotmpl`  
`values/fluentd/fluentd-sc.yaml.gotmpl`  
`values/fluentd/fluentd-user.yaml.gotmpl`  
`values/fluentd/fluentd-wc.yaml.gotmpl`  
`values/fluentd/sc-logs-retention.yaml.gotmpl`

**Comment by Xartos** [comment]
Closing in favor of https://github.com/elastisys/compliantkubernetes-apps/issues/695
